build.xml

A distribution built on the opposite OS has the wrong line endings for refine.ini, refine.bat and refine (which is important), and README.txt and the licenses.  This converts them appropriately during the build.

Convert config file line endings to LF or CRLF for Linux and Windows distributions.

---

refine.bat

When I added `refine.max_form_content_size` to the config file in #908 I forgot to make modifications to `refine.bat` so that the option works for Windows users. My bad! This PR adds the necessary lines to `refine.bat` to make the option work.
This could also potentially fix #970.

Fixes bug where refine.max_form_content_size does not get set on Windows

---

main/webapp/modules/core/scripts/facets/text-search-facet.js

Ignore keystrokes in the TextSearchFacet that do not indicate changes to the search query

Fix #896 - TextSearchFacet refreshes unnecessarily

---

main/src/com/google/refine/expr/MetaParser.java

as agreed in 2013 when writing *Using OpenRefine*
It will be nice to have it part of the 2.6 official release to completed the change of branding.

Changed GREL to *General Refine Expression Language* 

---

main/src/com/google/refine/browsing/Engine.java
main/webapp/modules/core/scripts/util/dialog.js
main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
main/webapp/modules/core/scripts/views/data-table/data-table-view.js

The dialog.js utility provided dismiss function and it's by level(ie if you dismiss the level 2 and the level 3 will be also dismissed). I added one function to allow it dismiss specified level so the "Working" dialog can survive after the main dialog is gone.
For the back end, changed two methods:
public synchronized FilteredRows getAllRows() 
public synchronized FilteredRecords getAllRecords() 
It will handle all the cases which processing the rows and records to prevent the reentry. Hopeful it's not overkill.

prevent the multiple sorting

---

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
extensions/jython/tests/com/google/refine/jython/JythonEvaluableTest.java

Description: any jython function used in the project has implicit name __\__temp\____ which creates issues when there are multiple projects which transforms are applied concurrently.
Fix replaces default name to include hashcode of function code itself and making this safer in concurrent environments.
Created corresponding test which was failing before and now passes.
We are using openrefine on production to apply transformations to datasets and found that during concurrent access sometimes we are getting corrupted data.
Patch will also help to all forks which are trying to make batch processing transformations engine based on openrefine (what we actually did for internal usage)

Concurrent access issue to jython evaluables.

---

main/src/com/google/refine/model/ColumnModel.java
main/src/com/google/refine/operations/cell/KeyValueColumnizeOperation.java
main/tests/server/src/com/google/refine/operations/cell/TransposeTests.java

fixed issue #796 Columnize by key/value columns creates empty lines

fixed issue #796 Columnize by key/value columns creates empty lines

---

main/webapp/modules/core/scripts/index/open-project-ui.js

I found this while reading the code. I haven't tested it, but as this is the only instance of the `encodeURICompnent` string in the codebase, I suppose it's a typo.

Fix typo on encodeURIComponent JS call

---

main/webapp/modules/core/scripts/facets/text-search-facet.js

Checkboxes are small targets. Making the labels clickable for toggling checkboxes improves usability.

Add labels for checkboxes in text facet, making them clickable

---

main/src/com/google/refine/model/ColumnModel.java
main/src/com/google/refine/operations/cell/KeyValueColumnizeOperation.java
main/tests/server/src/com/google/refine/operations/cell/TransposeTests.java

fix #1138 (Transpose > Columnize by Key/Value doesn't work)
Only remove the empty rows and leave the model untouched for undo/redo

fix #1138. column transpose

---

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js

@thadguidry Thanks for the merge! Unfortunately just afterward I noticed a problem with the cluster export functionality in Firefox. The generated link has to be added to the document body in order for the download to work -- now it works on both Firefox and Chrome.

fix PR #1092 to work with Firefox

---

main/src/com/google/refine/commands/column/AddColumnByFetchingURLsCommand.java
main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java
main/webapp/modules/core/langs/translation-default.json
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/langs/translation-fr.json
main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js

This PR introduces a cache while fetching URLs to create a new column. This cache is a simple HashMap which lives during the operation and is cleared afterwards.
Notable changes to discuss:
With this PR, the sleep time is exactly the delay input by the user, without subtracting the time spent doing the request. This is a more responsible rate-limiting strategy because it lets servers reduce the load by taking more time to respond. The querying rate of the client adapts to the load of the server. The benefit might sound dubious but it does make a difference on servers, and it is important to spare the resources of the non-profits running free to use APIs.
This operation does not seem to be currently covered by a test case. If it were, I would have been happy to add a few regarding this new …

Add caching in URL fetching

---

main/src/com/google/refine/expr/functions/booleans/And.java
main/src/com/google/refine/expr/functions/booleans/Or.java
main/src/com/google/refine/expr/functions/booleans/Xor.java
main/tests/server/src/com/google/refine/tests/expr/functions/booleans/BooleanTests.java

In reference to my issue #1183 (which was resolved by editing the Wiki to reflect that `AND`/`OR` operators accept *only* two conditions).
I believe it is possible to allow both `AND`/`OR` allow *two or more* conditions, as the changes in my request establish. 
This is an improvement - there is no need to nest `AND`/`OR` functions within each other, and makes testing more than two conditions simpler and more intuitive. It also matches the functionality of the comparable functions in Excel which allow 2+ arguments.

allow more than 2 AND and OR conditions

---

main/src/com/google/refine/importers/ImportingParserBase.java

The check for a duplicate column was previously being done with an assert which is switched off by default. As a result, tests were always passing.

Fixes #1181

---

main/src/com/google/refine/RefineServlet.java
refine
refine.bat
refine.ini
server/src/com/google/refine/Refine.java

Changes:
* added option for initial java heap space (-Xms) in refine.ini.
* added option for autosave period in refine.ini
Reasons:
* setting -Xms = -Xmx prevents the JVM from wasteful upsizing steps. -Xms was "hardcoded" to 256M in refine shell script
* autosave period defaults to 5 minutes which is a significant performance issue for longlasting transformations. This setting was "hardcoded" in RefineServlet.java
* cf. discussion "[Performance Improvements (initial heap space, autosave, row operations)](https://groups.google.com/forum/#!topic/openrefine/zglQEePk_b4)" in google group

added options for initial java heap space and autosave period

---

main/src/com/google/refine/RefineServlet.java
server/src/com/google/refine/Refine.java

I am very sorry! I have introduced a severe bug with my pull request #1202 recently. This new pull request is a bug fix.
If REFINE_AUTOSAVE_PERIOD is not set in refine.ini, the application won't start.
```
java.lang.NumberFormatException: null
at java.lang.Long.parseLong(Long.java:552)
at java.lang.Long.parseLong(Long.java:631)
at com.google.refine.RefineServlet.init(RefineServlet.java:134)
at javax.servlet.GenericServlet.init(GenericServlet.java:241)
at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:180)
at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
at com.google.refine.RefineServer.configure(Refine.java:296)
at com.google.refine.RefineServer.init(Refine.java:208)
at …
```

bugfix for new option autosave period

---

.gitignore
open-refine.log
start.sh
stop.sh

The script to start OpenRefine is "start.sh". It starts OpenRefine as a background process and logs are created respectively in "open-refine.log" file.
The script to stop OpenRefine is "stop.sh". It kills the OpenRefine process and displays a message like "successfully stopped open-refine".

Added Start and Stop Script For Linux

---

main/tests/server/src/com/google/refine/tests/model/KeyValueColumnizeTests.java

In relation to #1214, this PR just adds a test to demonstrate the way KeyValueColumnize deals with records and therefore requires to see the rows in a particular order to work correctly.
The point is just to make sure that the existing functionality is preserved by future contributors. And increase our test coverage, which seems to be very low at the moment.

Add test for KeyValueColumnize

---

main/webapp/modules/core/scripts/project.js

This fixes the auto-resize code which ensures that history items don't overflow beyond the end of the window. The order of the history items is still preserved (oldest first). According to @Opennat in #1106 it used to be in the reverse order, but I can't find the commit that changed that. I think the current order is less of a problem now that this bug is fixed.

Fix overflow of history items outside the window.

---

main/src/com/google/refine/importers/WikitextImporter.java
main/tests/server/src/com/google/refine/tests/importers/WikitextImporterTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js

This lets users import the individual references of each cell. As OpenRefine does not support adding arbitrary metadata to cells yet (see #499), references are added alongside the values they support, in their own column.
Closes #1243.

Add support for references in Wikitable importer.

---

main/src/com/google/refine/browsing/util/NumericBinIndex.java

If there is only a single numeric value for a numeric range facet, the 'max' value for the facet is set to '1' ( actually _step, but _step is hard coded to be '1'). This leads to the behaviour reported in #1247 (for any situation where all numeric values are equal, not just in the "Best candidate's score" scenario described)
This change ensures that the max value is min+step in this scenario - i.e. one more than 'min' in the case where 'step' is hard coded to '1'

Ensure _max is never less than _min for numeric range facet

---

main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

So the two buttons of #1272 had same label and tooltip but had indeed different meanings, this fixes it.

Fix duplicate item in Reconcile > Actions menu. Closes #1272.

---

main/src/com/google/refine/importers/WikitextImporter.java
main/tests/server/src/com/google/refine/tests/importers/WikitextImporterTests.java

Currently, if citation templates are input without any spaces between template parameters, URL extraction fails because the regex spans beyond the end of the URL.
This PR forbids pipe characters. This is a temporary fix before we do full Wikitext parsing inside references (this needs a change upstream).
See https://github.com/sweble/sweble-wikitext/issues/67 .

Forbid pipe characters in URL references to ease parsing.

---

main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.js
main/webapp/modules/core/scripts/project/process-panel.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js

Expressions from expression-preview are send to server via HTTP GET. Because of this users aren't able to send expressions longer than a few hundreds chars (limit by url length). This fix sends expressions via POST and that solves the problem for longer scripts.

Allow longer expressions by sendig them as POST

---

main/webapp/modules/core/scripts/project.js
main/webapp/modules/core/scripts/project/browsing-engine.js
main/webapp/modules/core/styles/project/sidebar.less

To fix #1203 
- Changes get-rows call to request JSON rather than JSONP
- Catches situations where JSON returned for get-rows or compute-facets includes an 'error' element
- Where there is an error with get-rows, the existing row set is used for the data-table
- Where there is an error with compute-facets, the error message from the JSON is displayed at the top of the facets/filter sidebar (some minor modifications to css and DOM manipulation were needed to achieve this alongside the 'refreshing facets' notification)
Comments welcome

Fix regex filter error

---

main/src/com/google/refine/browsing/facets/TextSearchFacet.java
main/src/com/google/refine/browsing/filters/ExpressionStringComparisonRowFilter.java
main/tests/server/src/com/google/refine/tests/browsing/facets/TextSearchFacetTests.java
main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/facets/text-search-facet.js
main/webapp/modules/core/styles/project/facets.less

Implementing an 'Invert' option for the text search facet (a.k.a filter) as per #952 
* New 'Invert' and 'Reset' options at the top left of the Text filter facet panel
* Click the 'Invert' link to invert the filter - i.e. find all rows which don't match the filter text or regular expression
* When 'Invert' is applied, panel gets an orange header to indicate the filter is inverted. The same device also implemented on text facets. In both cases the 'Invert' link appears struck-through (this latter device is the current behaviour for the Text Facet)
* 'Reset' clears all the options (invert, text in the filter box, case-sensitive, regular expression) of the filter
Comments on the UI welcome (@ettorerizza, @thadguidry, @wetneb)
I want to implement some tests for this functionality, but I can't …

Invert text search facet/text filter

---

README.txt

Stefano Mazzocchi and David Huynh have expressed that they no longer will contribute directly to OpenRefine but would like to be regarded as "Emeritus" status (having retired but allowed to retain their title as an honor)

Update README.txt for Emeritus contributors

---

main/src/com/google/refine/browsing/facets/TextSearchFacet.java
main/src/com/google/refine/util/PatternSyntaxExceptionParser.java
main/tests/server/src/com/google/refine/tests/util/PatternSyntaxExceptionParserTests.java

An attempt to provide users with user-friendly messages for common issues with regular expressions as per #1297 
What I've done here is to parse some of the error messages from java.util.regex.PatternSyntaxException and return a user-friendly equivalent. It does the job, but I'm unsure this is really the best approach.
Feedback welcome including suggestions for alternative approaches.
Currently only implemented for the Text Filter w Reg Expressions, but it could be implemented to do the same for any GREL operations accepting Reg ex by using it in the appropriate part of com.google.refine.grel.Parser

User-friendly regular expression errors

---

main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/tests/importing/ImportingUtilitiesTests.java

In order to apply the same operations while manipulating projects via scheduled jobs using a Python client, the `importOptionMetadata` is needed, e.g.:
```json
{
"name":"acme",
"tags":[
],
"created":"2017-12-18T13:28:40.659",
"modified":"2017-12-18T15:38:05.44",
"creator":"",
"contributors":"",
"subject":"",
"description":"",
"rowCount":50,
"customMetadata":{
},
"importOptionMetadata":[
{
"guessCellValueTypes":false,
"projectTags":[
""
],
"ignoreLines":-1,
"processQuotes":true,
"fileSource":"acme.txt",
"encoding":"",
"separator":"|",
"storeBlankCellsAsNulls":true,
"storeBlankRows":true,
"skipDataLines":0,
"includeFileSources":false,
"headerLines":1,
"limit":-1,
"projectName":"acme"
},
{
"guessCellValueTypes":false,
"projectTags":[
""
],
"ignoreLines":-1,
"processQuotes":true, …
```

Options metadata

---

main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java

This tweaks the URL caching test so that it passes on Appveyor, where random.org returns 503 errors.

Fix appveyor

---

refine.bat

Too often we need to ask multiple questions from folks running OpenRefine on Windows.  Let's make this easier for us from a support perspective and just ask the users to paste the contents of the support.log file to us.  We can expand on any support.log enhancements later as we come across the need to add more.

Support log for Windows folks running refine.bat

---

main/webapp/modules/core/about.html

This PR fixes the list of contributors' LI elements, so that the HTML renders correctly.

about page: closing LI tags

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js

This PR fixes the spelling of a JS property.
I found this using a global search for common misspellings.

Reconciliation panel: spelling of JS property

---

extensions/database/module/MOD-INF/controller.js
extensions/database/module/scripts/database-extension.js
extensions/database/module/scripts/index/database-source-ui.js

The following javascript error occurs on the project page caused by the script extension/database/scripts/database-extension.js.
```
project-bundle.js:41312 Uncaught TypeError: $.contextMenu is not a function
at HTMLDocument.<anonymous> (project-bundle.js:41312)
at fire (project-bundle.js:3121)
at Object.fireWith [as resolveWith] (project-bundle.js:3233)
at Function.ready (project-bundle.js:3445)
at HTMLDocument.completed (project-bundle.js:3476)
```

Javascript error on project page from database extension

---

.classpath
extensions/jython/src/com/google/refine/jython/JythonHasFieldsWrapper.java
extensions/jython/tests/src/com/google/refine/jython/JythonAttributeTest.java

This implements #1377 : fields in Jython are available both as items and as attributes, just like GREL.
In other words, both `return cell.recon.match.id` and `return cell['recon']['match']['id']` are possible in Jython.

Expose fields as attributes in Jython

---

main/src/com/google/refine/importers/WikitextImporter.java
main/tests/server/src/com/google/refine/tests/importers/WikitextImporterTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/langs/translation-fr.json
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js

The wikitable importer was making the assumption that all header cells were at the beginning of the table, which was unsafe. This removes this assumption: header cells are parsed like normal cells. The downside of this is that we do not detect automatically the headers: the user has to select how many lines of input should be parsed as header, just like in the CSV/TSV importer.
This also adds parsing for image links which are treated like templates (they can be either ignored or included in the table).
This should close #1448 - @ostephens let me know if that works for you.

Make Wikitext importer more robust

---

.github/ISSUE_TEMPLATE.md

I was submitting a new issue today when I noticed that the contribution guidelines have been updated - there is now a preferred format for bug reports.
As such, I have put together a simple template that will show up as a comment when contributors attempt to open a new request. It will look like this:
albeit with the corresponding message (as taken from the [updated documentation](https://github.com/OpenRefine/OpenRefine/blob/master/CONTRIBUTING.md#guidelines-for-reporting-a-bug)) and corresponding repository name.
This can possibly help to keep the format of bug reports more consistent since some people just don't want to open an extra page of documentation to read.

Create issue template for bug reports

---

main/src/com/google/refine/expr/functions/strings/Range.java
main/src/com/google/refine/grel/ControlFunctionRegistry.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/RangeTests.java

Fixes #1319 
The original specification that @thadguidry suggested for the `range` function was:
> It will work like this...
>
>can take accept a String form:
>range("2-4") --> [2,3,4]
>
>or a String form in a value
>range(value) --> [2,3,4]
>
>or 2 numbers
>range(2, 4) --> [2,3,4]
>
>and doing join(",") will convert the Array to a String
>range(2,4).join(","). --> 2,3,4
However, because of issues such as [cells being unable to display arrays](https://github.com/OpenRefine/OpenRefine/issues/1088) and the [potential confusion it can cause](https://github.com/OpenRefine/OpenRefine/issues/1475), I have taken the liberty to display the results of `range` as a string with comma-separated values instead.
Hence, my implementation works like this:
**(a) String arguments**
1. `range("2-4") --> 2, …

Add a new range() function to GREL

---

main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/expr/functions/ToNumber.java
main/src/com/google/refine/expr/functions/ToString.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java

Correct behaviour of toNumber and toDate so returns errors rather than nulls if wrong number of arguments provided or attempt to parse null or empty strings.
Also minor change to toString function to look up function name when returning error
Fixes #1506 #1507 #1505

Conversions

---

main/src/com/google/refine/model/recon/StandardReconConfig.java
main/tests/server/src/com/google/refine/tests/model/ReconTests.java

Some background: new version json.lib is required as data package dependency. but the new version of json lib has more strict check when try to convert a string to int

fix issue #1517, limit is written as int and should have been read as int

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/styles/views/data-table-view.less

As discussed in #1544 this PR adds a toggle option for displaying 'null' in cells containing a null value (as opposed to an empty string). Adds option under the All->View menu. Option is persistent while viewing a project (unless the user forces a refresh of the screen via the browser).
Default is to not display the null values to keep the screen from becoming too busy

Added option to toggle show/hide null values in cells in data-table

---

main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/tests/util/ParsingUtilitiesTests.java

Closes #1564.
This fixes the date parsing utility functions used at various places in the code. Both local times and zoned times are accepted. I have also restored the original behavior of `stringToDate` of returning `null` when parsing failed instead of throwing an exception.

Fix date parsing.

---

main/src/com/google/refine/operations/cell/BlankDownOperation.java
main/src/com/google/refine/operations/cell/FillDownOperation.java
main/tests/server/src/com/google/refine/tests/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/tests/operations/cell/FillDownTests.java

Closes #742.
Records are respected if the operation is run in records mode. In rows mode, the behavior is unchanged.

Fix FillDown and BlankDown operations on records.

---

main/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperation.java
main/tests/server/src/com/google/refine/tests/operations/cell/ReconJudgeSimilarCellsTests.java

There is a bug in the operation that marks cells as reconciled to new (discovered by @ostephens): when sharing topics, the identifier space used for the reconciliation is ignored and the default one is used instead. This fixes it (by using the identifier space associated with the column).

Fix identifier space for cells reconciled to New

---

extensions/wikidata/tests/src/org/openrefine/wikidata/qa/WikidataConstraintFetcherTests.java

The inverse constraint on the part of property was removed.

Fix inverse constraint test for Wikidata extension.

---

refine

I've removed support for version 6, and allowed all java versions greater than or equal to 7. Is this the range of java version supported by OpenRefine?

#1604 upgrade java version check to accept all versions greater than 6

---

main/webapp/modules/core/scripts/project/history-panel.js

Currently, if you open a project that, when it was last closed, was "undone" up to the first operation, you will see : 
Opening an old project this morning I was confused and thought it was a recently created one because of this, but in fact I already had many operations on this project, it was just that before closing it I had viewed the file at first operation.
This PR proposes to change the display to the following : 
With 10 in this screenshot being the total number of available operations in the current project. It makes more sense to me, hope I'm not alone!

Total number of operations for Undo / Redo

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateVariable.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbLanguageVariable.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbLocationVariable.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbQuantityExpr.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateVariableTest.java

Raises explicit warnings linking to the docs when Wikibase datavalues are skipped due to format errors.

Give better feedback when values with invalid formats are provided.

---

main/src/com/google/refine/model/changes/DataExtensionChange.java
main/tests/data/changes/data_extension_2.8.txt
main/tests/data/changes/data_extension_3.0.txt
main/tests/server/src/com/google/refine/tests/model/changes/DataExtensionChangeTest.java

It turns out that the part of DataExtension changes that was not serialized consistently is not actually needed to apply and unapply the change. So I have just removed this deserialization and serialization. The code accepts changes made by OR 2.8 and the changes created on master (future OR 3.0) are also retro-compatible with OR 2.8.

Remove DataExtensions from change serialization

---

main/tests/server/src/com/google/refine/tests/recon/DataExtensionTests.java

In Travis these tests are occasionally failing https://travis-ci.org/OpenRefine/OpenRefine/jobs/3896227 which is probably due to the CPU demand spike placed with createProcess.

Increasing to 10 second sleep because of Travis

---

main/src/com/google/refine/util/StringUtils.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java

Changed behaviour of using null.toString() as per #1635
This makes the behaviour constistent with using "string" + null and more intuitive/safer for users

Null to string

---

main/src/com/google/refine/operations/cell/MassEditOperation.java
main/tests/server/src/com/google/refine/tests/operations/cell/MassOperationTests.java

This fix is for #1631 and #180
(clean version of previous PR #1641)

Mass edit fix for blanks, numbers and booleans

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java
extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstraintScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbItemVariable.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstaintScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ValueScrutinizerTest.java

This adds support for a bunch of new Wikidata constraints, so that we can tick a few more boxes in https://www.wikidata.org/wiki/Wikidata:WikiProject_property_constraints/implementations

Add support for new Wikidata constraints

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizer.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/WikidataConstraintFetcherTests.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizerTest.java

Wikidata is changing the way they are representing scope constraints. This PR adapts the code to the new format.
Discussion: https://www.wikidata.org/wiki/Wikidata:Property_proposal/property_scope

Migrate to new scope constraint format

---

extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateVariableTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbReferenceExprTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStatementExprTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java

The wikibase data model lets users store dates with precisions. The Wikidata-Toolkit library and the Wikibase implementation disagreed on the default values for these precisions. This leads to conflicting values being added to the items (see https://www.wikidata.org/w/index.php?title=Q391056&action=history for instance).
This was fixed in Wikidata-Toolkit (https://github.com/Wikidata/Wikidata-Toolkit/pull/375) and this PR brings the fix to OpenRefine.

Change default precision of Wikibase dates to match the UI's defaults.

---

main/src/com/google/refine/browsing/DecoratedValue.java
main/src/com/google/refine/operations/cell/MassEditOperation.java
main/src/com/google/refine/util/StringUtils.java
main/tests/server/src/com/google/refine/tests/browsing/util/ExpressionNominalValueGrouperTests.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java
main/tests/server/src/com/google/refine/tests/operations/cell/MassOperationTests.java

This PR fixes #1632.
This is a surprisingly complex area, as it relates to how dates are transformed to strings. This can happen in different ways in different places in OR. When converting a date to a string results in a different value to the required one, it can result in unexpected behaviour.
This PR:
- Adds tests for how Mass Edits are reconstructed for dates to ensure OR does this correctly. This test fails in OR 3.0 beta
- Changes the behaviour of StringUtils.toString() to convert OffsetDateTime to a string using ParsingUtilities.dateToString -  this helps to standardise behaviour in converting dates to strings in OpenRefine, including for Mass Edits. This makes the test introduced a passing test
- Changes the expected behaviour being tested for in ToFromConversionTests.java to …

Mass edit dates

---

main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java

Closes #1669 and makes it possible to specify other headers via the JSON representation of the operation.
@michaelavoigt could you try this and confirm that it solves the issue on your side? Let me know if you need help to run the development version on this branch.
@ostephens what do you think of this simpler version? It lets users specify arbitrary HTTP headers in the JSON representation of the operation - I guess that could be useful for some APIs using some non-standard headers.

Simplify parsing of HTTP headers in fetch-url operation

---

main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java

This assertion fails if the locale is not English, so I am removing it so that the test suite runs independently.

Remove test assertion that can fail depending on the locale

---

main/src/com/google/refine/clustering/Clusterer.java
main/src/com/google/refine/clustering/ClustererConfig.java
main/src/com/google/refine/clustering/binning/BinningClusterer.java
main/src/com/google/refine/clustering/knn/kNNClusterer.java
main/src/com/google/refine/commands/browsing/ComputeClustersCommand.java
main/tests/server/src/com/google/refine/tests/clustering/BinningClustererTests.java
main/tests/server/src/com/google/refine/tests/clustering/kNNClustererTests.java

This PR is similar to #1729 in that it refactors serialization with the migration to Jackson in mind (#1652).
New classes are introduced to store the configuration of each clusterer. These classes will be improved and simplified once we migrate to Jackson.

Refactor clustering serialization in JSON

---

main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/tests/server/src/com/google/refine/tests/importers/TsvCsvImporterTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js

Sometimes there is the need to change the column names of an importing separator based file or to add them because they are missing (without renaming individually once the file have been imported).
This option allows to define a comma separated string that will be parsed as the column names for the project. The option is only available when the "Parse next" checkbox is not selected. Selecting the "Parse next" checkbox will disable and clear the column names input box:
[demo](https://ibb.co/gxk1aU)

Custom column names for separator based importer

---

main/webapp/modules/core/MOD-INF/controller.js

Fix issue #1717. Solution is to always read the file in UTF8. Otherwise it will cause problem on windows 10 and updated chrome.

force the encoding to UTF8

---

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java

This is a temporary fix until the bug is fixed upstream, in Wikidata-Toolkit.

Temporary fix for HTTP 500 errors from Wikibase. Closes #1746

---

main/src/com/google/refine/commands/recon/ReconUseValuesAsIdentifiersCommand.java
main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java
main/tests/server/src/com/google/refine/tests/operations/recon/ReconUseValuesAsIdsOperation.java
main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

This adds a new operation to reconcile a column of identifiers without hitting the reconciliation service. The operation can be found in the `Reconcile...` menu of each column.
This closes #1596.

Directly use column as reconciliation results

---

main/src/com/google/refine/expr/functions/strings/SmartSplit.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/SmartSplitTests.java

This commit adds the support of String separator in function smartSplit. Previously only char separator is supported. Now smartSplit can support String as well as single char as separator. Changed to existing implementation of overloaded constructor of CSVParser which takes string separator.

Fix: Allow smartSplit() to handle String of chars not just a single char

---

extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java

Closes #1772.
No tests for this one because we don't have a good way to test constraint fetching by mocking HTTP calls at the moment.

Ignore deprecated constraints. 

---

extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.html
extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js

Summaries are remembered and proposed natively to the user in the summary field.
Closes #1778.

Enable autocomplete for Wikidata upload form

---

README.md
extensions/database/pom.xml
extensions/gdata/pom.xml
extensions/pc-axis/pom.xml
extensions/wikidata/pom.xml
main/pom.xml
packaging/pom.xml
pom.xml
server/pom.xml

This tweaks the Maven configuration files so that they are better accepted by Eclipse.
To run OpenRefine from Eclipse, add a new maven execution goal profile with "exec:java" as goal.
It is also possible to run OpenRefine from command line with `mvn compile test-compile exec:java`.
This closes #1805.

Streamline Eclipse setup with Maven

---

main/webapp/modules/core/scripts/util/encoding.js

Restore tab behaviour in encoding dialog.

---

main/src/com/google/refine/operations/cell/BlankDownOperation.java
main/src/com/google/refine/operations/cell/FillDownOperation.java
main/tests/server/src/com/google/refine/tests/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/tests/operations/cell/FillDownTests.java

So the fill down and blank down incorrectly assumed that the first column had cell index 0, which gave the weird bugs observed in #1573. This should fix it.
@msaby can you confirm this fixes the issue on your side?

Fix cell index computation in filldown/blankdown

---

refine.bat

We should be more graceful for those that mistype a refine command.  As I sometimes do and inadvertently start OpenRefine, since :doRun is the default.
(someone else can do the PR for the same thing in the bash script)
Tested Output is:
```console
C:\Users\THAD\OpenRefine>set ACTION=reset
C:\Users\THAD\OpenRefine>setlocal
C:\Users\THAD\OpenRefine>if ""reset"" == ""build"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""server_test"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""extensions_test"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""test"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""clean"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""distclean"" goto doMvn
C:\Users\THAD\OpenRefine>if ""reset"" == ""run"" goto doRun …
```

Add exception handling for "refine" command

---

extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java

This adds one hex digit to each edit group id on Wikidata. My intention is to do this for the next few major versions, so that we can easily tell which OpenRefine was used to upload a given batch.

Increment size of Wikidata edit batch ids

---

refine.bat

This fixes a small regression...Without this fix... just using "refine" will not start OpenRefine as it used to on Windows.

ugh, forgot to still allow just "refine" to start on Windows

---

main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

Fixes #1883 and #1886 
Partially fixes  #1884 (ensures the user can see a value here, but does not implement a transform of epoch time to a more human-readable date stamp)

Fix Reconcile facets affected by change to list facet boolean handling

---

main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java
main/tests/server/src/com/google/refine/tests/io/ProjectMetadataTests.java
main/tests/server/src/com/google/refine/tests/util/ParsingUtilitiesTests.java

Closes #1874.
This effectively disables localization for dates. I think this is the right thing to do, otherwise users might have curious behaviors, such as `datePart(toDate("2012-03-01"), "month")` evaluating to `2` instead of `3`.

Avoid localizing time for dates with unspecified time.

---

main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/tests/importing/ImportingUtilitiesTests.java

Closes #1840. Also protects other importing sources (such as tar archives) from this sort of vulnerability as the `allocateFile` function is used at various places.

Fix zip slip vulnerability

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js

Adding new 'Common transform' in response to #1676. This is a trivial change, my only concern is that the list of "common transforms" that people might want to have from this menu is essentially endless. I feel that adding this one is fine, but feel there is some need here to have something easily extensible that doesn't require adding code to add things to this list (maybe hooked into 'starred' transforms?)
@thadguidry @ettorerizza comments welcome

Add Common transform which replaces smart quotes with ascii equivalent

---

extensions/wikidata/src/org/openrefine/wikidata/updates/ItemUpdate.java
extensions/wikidata/tests/src/org/openrefine/wikidata/updates/ItemUpdateTest.java

Fixes #1917. This makes it possible to override labels, descriptions and add aliases multiple times in the same batch.

Index terms by language code in ItemUpdate.

---

main/src/com/google/refine/model/recon/StandardReconConfig.java
main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java

Fixes #1913.
Reconciliation services should still return results ordered by decreasing score for compatibility with OpenRefine <= 3.1, I have updated the wiki about that:
https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API

Reorder reconciliation results by decreasing score

---

extensions/phonetic/.gitignore
extensions/phonetic/module/MOD-INF/controller.js
extensions/phonetic/module/MOD-INF/module.properties
extensions/phonetic/module/langs/translation-en.json
extensions/phonetic/module/macros.vm
extensions/phonetic/module/scripts/load-language.js
extensions/phonetic/pom.xml
extensions/phonetic/src/org/openrefine/phonetic/keyers/BeiderMorseKeyer.java
extensions/phonetic/src/org/openrefine/phonetic/keyers/DaitchMokotoffKeyer.java
extensions/phonetic/tests/conf/tests.xml
extensions/phonetic/tests/src/org/openrefine/phonetic/keyers/BeiderMorseKeyerTest.java
extensions/phonetic/tests/src/org/openrefine/phonetic/keyers/DaitchMokotoffKeyerTest.java
extensions/pom.xml
main/pom.xml
main/src/com/google/refine/exporters/XlsExporter.java
main/src/com/google/refine/importers/ExcelImporter.java

This adds a `phonetic` extension which adds two phonetic clustering methods (Beider-Morse and Daitch-Mokotoff). These encoders are available from Apache commons-codec so this does not require any new dependency (after upgrading Apache POI, which depends on commons-codec).
We could also implement this directly in main, but the purpose is to show how anyone can add their own clustering methods without changing OpenRefine itself.
@isaomatsunami if you are interested in implementing custom clustering distances or keyers for particular scripts, you could perhaps do it in a similar way. This makes it possible to add dependencies to heavy Java libraries if needed.

Sample extension to add some clustering methods

---

main/webapp/modules/core/scripts/facets/timerange-facet.js

Fixes #1537 
This is my first contribution to OpenRefine, please let me know if I missed anything in the contribution guidelines.
This change was to add a maximum date on the timerange facet shown here:
This is what the change looks like:

Timeline facet - show max date #1537

---

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateVariable.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateVariableTest.java

Do not represent time values with precision > 11.

---

main/src/com/google/refine/model/recon/StandardReconConfig.java
main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java

A null pointer exception could be thrown when computing the features of a recon with no candidates.

Fix Recon features computation for empty recons

---

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
main/webapp/modules/core/externals/suggest/suggest-4_3.js
main/webapp/modules/core/scripts/views/data-table/cell-ui.js
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

Clicking on an item with the middle button leads the user to the page
for this item. This lets users inspect items without selecting them.
By default this is only enabled on suggest widgets for entities (not for types or properties) because reconciliation services do not declare view URLs for types or properties so far. The view URL for entities is derived from the main view URL for reconciliation results.
Reconciliation services can now declare view URLs for all three sorts of suggested things (entities, properties and types) by adding a `view_url` field in the definition of their suggest widgets as follows:
```
entity: {
"service_url": "https://tools.wmflabs.org/openrefine-wikidata",
"service_path": "/en/suggest/entity",
"flyout_service_path": "/en/flyout/entity?id=${id}",
"view_url": …
```

Make suggest items clickable with the middle button.

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js
main/webapp/modules/core/styles/views/data-table-view.less

When hovering unmatched reconciliation candidates and matched cells, the reconciliation preview from the service shows up (if provided).
Clicking on unmatched reconciliation candidates now has the same behaviour as clicking on matched cells: it opens the page of the entity in a new tab.
As argued in #1943 I think this is a much more natural behaviour and I have heard of multiple users who were confused about this. I think it should not be too hard for experienced users to adapt.
Tested in Firefox and Chromium: please test extensively on as many environments as possible and report if anything does not feel natural.
One possible downside of this is that people could feel like the previews pop up too often, when the user inadvertently hovers a reconciliation link without any intent to …

 Show reconciliation previews on hover of reconciliation candidates 

---

main/src/com/google/refine/InterProjectModel.java
main/src/com/google/refine/ProjectManager.java
main/src/com/google/refine/expr/functions/Cross.java
main/src/com/google/refine/util/GetProjectIDException.java
main/src/com/google/refine/util/JoinException.java
main/tests/server/src/com/google/refine/tests/expr/functions/CrossFunctionTests.java

For #1976 
Refactor of cross (and related code) to:
* Fail with clear error to user when attempt to cross with non-existent project name
* Fail with clear error to user when attempt to cross using a non-unique project name
* No longer require the name of source project (from which the cross is being done) is unique

Cross error reporting

---

main/src/com/google/refine/expr/functions/arrays/InArray.java
main/src/com/google/refine/expr/functions/math/RandomNumber.java
main/src/com/google/refine/grel/ControlFunctionRegistry.java
main/tests/server/src/com/google/refine/tests/expr/functions/arrays/InArrayTests.java
main/tests/server/src/com/google/refine/tests/expr/functions/math/RandomNumberTests.java

As per  #1854 and #1853 this PR implements the RandomNumber and InArray GREL functions that were previously part of the GOKb Utils extension

RandomNumber and InArray GREL functions

---

main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js

Implemented "Select All" and "Unselect All" buttons on the Excel Worksheet importer, as described in Issue #1974.

Added Select All/Select None buttons to Excel Worksheet Importer

---

extensions/wikidata/src/org/openrefine/wikidata/editing/NewItemLibrary.java
main/src/com/google/refine/model/Cell.java
main/tests/server/src/com/google/refine/tests/model/CellTests.java

This PR adds more tests for cell serialization for various types of cell data, and ensures that number, date and boolean cells are serialized in the correct way.
Also modifies wikidata extension to only try to compute recon features such as name match, levenshtein distance etc when the cell contains a string

Cell serialization fixes

---

main/pom.xml
main/src/com/google/refine/exporters/XlsExporter.java
main/src/com/google/refine/importers/ExcelImporter.java
main/tests/server/src/com/google/refine/tests/exporters/XlsxExporterTests.java
main/tests/server/src/com/google/refine/tests/importers/ExcelImporterTests.java

This PR fixes #1981 and #1984
* updates the version of poi-ooxml to bring it to the same version as poi (which is required).
* due to deprecation of POIXMLDocument.hasOOXMLHeader in the latest version, this PR changes the method for testing for XLSX vs XLS files
* adds test for import of xlsx
* tidies up some small code issues

Fix XLSX import and export

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
main/src/com/google/refine/io/FileHistoryEntryManager.java
main/src/com/google/refine/model/AbstractOperation.java
main/src/com/google/refine/operations/OperationResolver.java
main/src/com/google/refine/operations/UnknownOperation.java
main/tests/server/src/com/google/refine/tests/history/FileHistoryEntryManagerTests.java
main/tests/server/src/com/google/refine/tests/history/HistoryEntryTests.java

Also adds new logic to preserve the JSON representation of unknown operations, to protect from version downgrading or removal of extensions.
Closes #1990.

Fix JSON history corruption.

---

main/pom.xml

Disable Maven git plugin when .git directory is absent.

---

main/src/com/google/refine/expr/functions/strings/Diff.java
main/tests/server/src/com/google/refine/tests/expr/functions/strings/DiffTests.java

Fixes #1998 
In main/src/com/google/refine/expr/functions/strings/Diff.java:
Replaces code calculating time periods in nanoseconds and converting them to required units with java.time API based approach using `ChronoUnit.between()` method.
`call(Properties bindings, Object[] args)` method will now return EvalError in case if a long overflow occurs when calculating length of time period.
In main/tests/server/src/com/google/refine/tests/expr/functions/strings/DiffTests.java:
Provides additional test cases for:
Incorrect time units.
Long overflow described above.
Reaching 100% test coverage for main/src/com/google/refine/expr/functions/strings/Diff.java

Issue 1998

---

main/src/com/google/refine/io/FileProjectManager.java

Fixes #1989. @felixlohmeier if you want to have a look to confirm the fix is as you expected, that would be great.

Disable error message when workspace.json does not exist.

---

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java

Now that WMDE plans to take the query service lag into account when computing the maxlag, we should be able to speed uploads up and rely on the maxlag throttling to slow down when appropriate. This currently enforces a 60 edits/min instead of the previous 30 edits/min.

Speed up Wikidata uploads

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/module/langs/translation-fr.json
extensions/wikidata/module/langs/translation-it.json
extensions/wikidata/module/scripts/menu-bar-extension.js

Closes #2097.
@sjoerddebruin could you try out this version to see if it works for you?
```
git clone https://github.com/OpenRefine/OpenRefine
cd OpenRefine
git checkout issue-2097-wikidata-export
./refine
```
(assuming you use Linux and have Maven installed)

Wikidata: Use distinct tabs for QS and schema export.

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/CalendarScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/CalendarScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java

* Adds support for dates with custom calendars, such as `1345-03-07_Q1985786`;
* Adds support for special date `TODAY` which evaluates to today's date when edits are made;
* Adds warnings for early dates using the Gregorian calendar.
Closes #2136.

Improved support for Wikidata dates

---

main/webapp/modules/core/externals/suggest/suggest-4_3.js

Will resolve https://github.com/OpenRefine/OpenRefine/issues/2166
Since the data is re-set when an input is edited, it seems safe to not remove the data here.
An alternative for fixing #2166 would be to clear the actual input UI, but that would require re-entering the information after changing the type. I think the solution proposed here is the most user friendly way to fix this.

Don't remove data.suggest in _destroy function

---

extensions/database/module/langs/translation-en.json
extensions/database/module/scripts/index/database-source-ui.js
extensions/database/pom.xml
extensions/database/src/com/google/refine/extension/database/DatabaseUtils.java
extensions/database/src/com/google/refine/extension/database/cmd/SavedConnectionCommand.java
extensions/database/tests/src/com/google/refine/extension/database/cmd/SavedConnectionCommandTest.java

Validate Connection input data from frontend and backend. Sanitize database connection information before adding to the DOM.

Database Extension: input validation for database connection data

---

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java

If network goes down, the editing operation should finish without throwing an exception.
This avoids losing Qids for created items. This makes it possible to re-run the same operation afterwards. This also increases the waiting time with exponential backoff in case of error when fetching documents.
Closes #2205

Change behaviour of Wikidata editing in case of network failure

---

main/src/com/google/refine/commands/lang/LoadLanguageCommand.java
main/tests/server/src/com/google/refine/commands/lang/LoadLanguageCommandTests.java

This allows to keep the same Javascript calls to load languages, so it
does not require any change for extensions to benefit from this.
Closes #1350. Fixes #2209.

Add server-side language fallback.

---

extensions/wikidata/src/org/openrefine/wikidata/commands/LoginCommand.java
extensions/wikidata/tests/src/org/openrefine/wikidata/commands/LoginCommandTest.java

Closes #2228.
The issue was due to the fact that the GET endpoint also required CSRF protection.

Fix Wikidata login CSRF issue.

---

main/src/com/google/refine/commands/cell/EditOneCellCommand.java
main/tests/server/src/com/google/refine/commands/cell/EditOneCellCommandTests.java

Fixes #2163 
```
The implementation for two ways of parsing String to Number 
in cells is inconsistent:
1. 'Edit' cell dialogue and switch type to 'number':
Tries to parse String as a Double.
2. Using 'toNumber()' in cell transformations:
Tries to parse String as a Long, then parse String as a Double.
This PR modifies the 'edit' cell dialogue implementation 
to standardise with the latter, with the aim of eliminating 
inconsistent handling.
```

Standardise 'edit' cell dialogue with 'toNumber()' when parsing String to Number

---

main/webapp/modules/core/scripts/views/data-table/data-table-view.js

Fixes #2233 
```
After a sort is made, the Sort link that is displayed does not
reflect to the corresponding language of the UI.
This PR adds the translation of the corresponding language
of the UI to the Sort link.
```

Translate Sort link to the language of the UI

---

refine

In strict shell environments, the "$?" is reset when evaluated.
Here, the "boolean if" statements compares it to "7", then reset it and compares it to "22".
If the "$?" is intially "22", it is not evaluated and the NOT_RUNNING variable is ignored while it shouldn't. this leads to the error
"Something is already running on http://127.0.0.1:3333/"
To avoid this, the solution is to first affect the value of "$?" to a non-system variable and then evaluate this new variable.

Update the check_running() function in refine

---

main/webapp/modules/core/scripts/views/data-table/data-table-view.js

Resolves #2280 
```
There are use cases where users would want to apply
fill down/blank down operations for all columns. Users
would have to toggle the fill down/blank down operation
for each column in order to achieve that.
Let's add a fill down/blank down operation under the 
'All' > 'Edit Columns' drop down that applies the operation 
for all columns at once which will save the users' effort.
```

[#2280] Add fill down and blank down operations for all columns

---

.gitignore
extensions/wikidata/src/org/openrefine/wikidata/exporters/QuickStatementsExporter.java
extensions/wikidata/tests/src/org/openrefine/wikidata/exporters/QuickStatementsExporterTest.java

Fixes #2320 .
Before this PR, only the first reference is exported for QuickStatements.
For example, if we add a statement with two refs:
The preview will work fine:
However the QuickStatements output will only contain the first ref:
To fix this, we can just duplicate the statement just with different references. QuickStatements prevents to add a duplicate statement but is able to add a second or further reference to the pointing statement.
After the fix, the QuickStatements export now works fine:

Issue 2320 qs refs

---

main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js

changes for issue #898:
* made "Columnize by Key/Value columns" dialog resizable
* set overflow styling, which solves the issue in Chromium-based browsers (Chrome, Edge, Opera) but doesn't work in FireFox and WebKit-based browsers (like Epiphany @ Linux, not tested in Safari but most likely won't work either)

Handle long column names in key/value columnize dialog

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

We will eventually want to support different types of Pull requests (issues, docs, etc.) and GitHub supports a Template directory where many templates can be used for different kinds of PR's and can have different automation flows with query parameters.  This will be a useful starting point as we build out more automation (@ostephens docs effort) and expand our contributors.
Details here: 
- https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
- https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

Create new pull request template

---

extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java
extensions/gdata/tests/src/com/google/refine/extension/gdata/GoogleAPIExtensionTest.java
extensions/gdata/tests/src/com/google/refine/extension/gdata/SpreadsheetRETest.java

Close #2380 .
I changed the regex to extract the spreadSheetId from spreadsheet url and add corresponding tests for the new regex.

fix Google Sheets importer when URL is missing a trailing slash (#2380)

---

main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html

On clicking the `Trim leading & trailing whitespace from strings` checkbox in json importer configuration, the next checkbox i.e. `Parse cell text into numbers, dates, …` gets clicked. This is due to the wrong id in label for trim. This PR fixes that.

Corrects wrong trim label for json importer config

---

extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java
refine
refine.bat
refine.ini

Close #2383 
Now the OAuth client_id/client_secret for gdata extension are configurable at `refine.ini`.

support configurable credentials for gdata

---

refine
refine.ini

Close #2396 .
Just added some comments to clarify the configuration of JAVA_OPTIONS on Unix/Linux.

Use parentheses for JAVA_OPTIONS on Unix/Linux

---

main/webapp/modules/core/MOD-INF/controller.js

This removes a duplicate `set-project-metadata` command during Butterfly initialization, which was already done on L72.
Hmm, wondering if this might also fix any issues that we already have regarding startup?

Remove duplicate metadata command registration

---

main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java

Close #2398 
Now the reconciliation service used by WikitextImporter is successfully mocked.

Mock reconciliation service

---

extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js

Addressed issue #1778. Now auto-fill works in both Chrome and Firefox.
**Test With Chrome:**
Before submitting:
After submitting with text **t1**:
**Test With Firefox**
Before submitting:
After submitting with text **t 3**:

Fix: Enable auto complete in chrome

---

main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.js

Any value (even an empty string) of the checked attribute will be treated as checked. Fixed by passing null to jQuerys attr function which removes the attribute.
https://stackoverflow.com/questions/4228658/what-values-for-checked-and-selected-are-false

CustomTabularExporterDialog: fix checkbox options being ignored

---

main/webapp/modules/core/styles/util/menu.less

Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>
When we switch to a different language and try to apply some features on our column. The text overflows the menu container.
Changed the styling such that the text fits in the menu container and split into multiple lines.

Fix #2454 - Menu too small for text

---

main/src/com/google/refine/importers/ImporterUtilities.java
main/src/com/google/refine/importers/TabularImportingParserBase.java
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
main/tests/server/src/com/google/refine/importers/ImporterUtilitiesTests.java

Issue as noted as issue #1792 . 
Generally speaking, this error can occur when importing multiple sheets from one source file with some later sheets have more columns than the a previous one and the columnns share the same name.
**Cause of Issue**
In the test file, _sheet2_ has more columns than _sheet1_ and each column has the same name in both sheets.
When loading the second sheet, in lin 113 of `TabularImportingParserBase`, the columnNames is initialized to `[]` while the names of _column1_ to _column15_ are stored already in the _project_ variable.  
Without reusing the previous column names, _column 16_ is then treated as the 1st column when reading data from _sheet 2_ (since columnNames is initialized to `[]` instead of being `[column1 ... column15]`)
**Testing**
- Pass `./refine …

Fix: Data losses when importing multiple sheets from same Excell file

---

refine.bat

- removes extra notice of free memory
- replaces wmic (deprecated) with systeminfo 
- displays in console and support.log as:
```
----------------------- 
PROCESSOR_ARCHITECTURE = AMD64
JAVA_HOME = E:\Java\openjdk-13.0.1_windows-x64_bin\jdk-13.0.1
java -version = openjdk version "13.0.1" 2019-10-15
freeRam =  8,225 MB
REFINE_MEMORY = 1400M
----------------------- 
```

remove deprecated wmic command and use systeminfo

---

main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java

**Realted Issue**
As mentioned in issue #2031 , the InputStreamReader does not support GZIP compressed contents. 
Tried to use a GZIPInputStream to address response with `content-encoding:gzip`.

Enable gzip compression

---

main/src/com/google/refine/expr/functions/Cross.java
main/tests/server/src/com/google/refine/expr/functions/CrossTests.java

Fix #2461 
Now the cross function can take a number as the first argument.

Support lookup by numbers for GREL cross function

---

refine

Systems like NixOS don't use the path `/bin` for executables.
By default, `bash` must be available in `env`.

[bash] set cross *Nix bang line

---

main/webapp/modules/core/MOD-INF/controller.js

**Refers**: _Importing an XML file from a URL does not auto detect the correct importer_ #2420
I tested with a number of URLs, all of which worked.
The **content type** response header was: **application / xml** or **text / xml**.

Fixed that does not auto detect XML files from URL #2420

---

main/webapp/modules/core/scripts/util/ajax.js

By setting a client side timeout one can avoid net::ERR_NETWORK_IO_SUSPENDED errors caused by the OS network layer being suspended [1]. This allows the client to handle higher level errors.
The jQuery.getJSON() function does not have a parameter for timeout management.
[1]: https://cs.chromium.org/chromium/src/net/http/http_network_layer.cc?q=ERR_NETWORK_IO_SUSPENDED&sq=package:chromium&dr=C&l=42

Set client timeout limit in chainGetJSON()

---

.gitignore
refine
refine.bat
refine.ini

Close #2480 
Developers can now add custom configurations to `refine-dev.ini`, this file won't be tracked by Git. 
OpenRefine will still use `refine.ini` for configuration if `refine-dev.ini` doesn't exist.

Support refine-dev.ini for development

---

extensions/wikidata/pom.xml

Closes #2526.
The build will initially fail because it will take some time for the artifacts to be published on Maven Central, we can just re-run the build before merging.

Update WDTK to 0.11.1

---

main/webapp/modules/core/scripts/views/data-table/data-table-view.js

1) ./refine build to build
2) ./refine to run an instance
3) add column by using existing column
4) verify column header and content are added correctly
Root cause is there are default properties in a empty dict of javascript
we have to enhance the element existence by checking the value type

Fix that columns named « toString » are displayed as collapsed (#2451)

---

main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html

Clicking on `regular expression` label does not check that checkbox. This PR fixes the wrong id for that checkbox.

Fix: the wrong label for regex checkbox in split multi cell dialog

---

.gitignore

I noticed on PR #2555 that we should have ignored the Eclipse plugins ,metadata folder

Add .metadata to ignore Eclipse plugins meta

---

main/src/com/google/refine/LookupCacheManager.java
main/src/com/google/refine/expr/functions/Cross.java
main/tests/server/src/com/google/refine/expr/functions/CrossTests.java

Close #2461 
As a conclusion to the discussion under #2461, when doing a match with the GREL cross() function, two values will be taken as identical if and only if they have the same string representation.
That's to say, the Integer 1 and Long 1 will match, while 1 and 1.0 won't, because they don't have the same representation.
Also changed the help text for the cross() function to make it more clear.

Use string representation for matching for GREL cross() function

---

extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js

Adding PerformEditsDialog.doFormSubmit() to share with keypress() [RETURN] from editField and « Edit Uploads ».
Questions:
* Should I move PerformEditsDialog.doFormSubmit() inside PerformEditsDialog.launch()?
* Should I also trap [RETURN] when the focus is not in `this._elmts.editSummary`?
Regards, Antoine

Update perform-edits-dialog.js to trap [RETURN] in editSummary and proceed to action

---

docs/src/index.md

Let's see if this PR gets automatically labeled as being about documentation.

Change "reference manual" to "product reference"

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js

Fixes #2424 .
The application does not remember the data type of a cell as a cell only stores information related to the cell value. Hence, to show the correct data type on the front end, we can just use `typeof` to get the data type of the cell before rendering the HTML. This way of using `typeof` is also consistent with the rest of the application (e.g. the rest of the code in `cell-ui.js` etc).
This works with different languages as well since the `select` values are in English regardless how OpenRefine is localised.

Show correct data type in data table cell editor

---

docs/core/Footer.js

Somehow the Netlify integration is currently tied to my account, to get a team account we can apply for an open source plan which requires linking back to Netlify from our site. This does it in a discreet way.

Add Netlify link required for a team open source account

---

main/pom.xml
main/src/com/google/refine/exporters/XlsExporter.java

* to improve memory usage when exporting xlsx files
* indirectly related to https://github.com/OpenRefine/OpenRefine/issues/2593

Use SXSSFWorkbook in XlsExporter

---

main/src/com/google/refine/importers/ExcelImporter.java

Doesn't solve https://github.com/OpenRefine/OpenRefine/issues/2593 but it will speed up existing code a bit. When you pass an InputStream to POI, it moves the data to a temp file - accessing with the file in the first place avoids this step.

POI works better reading files directly

---

main/src/com/google/refine/util/SerializationFilters.java

If a new {@code Double} instance is not required, this method
should generally be used in preference to the constructor
{@link #Double(double)}, as this method is likely to yield
significantly better space and time performance by caching
frequently requested values.
This helps performance slightly depending on JVM used and processor as I discuss in a comment here:
https://stackoverflow.com/questions/10577610/what-is-the-difference-between-double-parsedoublestring-and-double-valueofstr?lq=1#comment108527648_10577630

improve native caching during JSON serialization

---

main/src/com/google/refine/importers/TabularImportingParserBase.java
main/tests/server/src/com/google/refine/importers/TsvCsvImporterTests.java

Closes #2584, which occurs when both trimming and type detection are enabled in a tabular parser (such as the CSV/TSV parser).
Cell value trimming was introduced after cell datatype detection, whereas it should be the other way around.

Fix bug when both trim and autodetect are enabled in tabular parser.

---

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/CommonDescriptionScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DescriptionScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EnglishDescriptionScrutinizer.java

There were some if-blocks without braces that were having one line of code. Syntactically, it was correct but it makes the maintainability of the code harder and increases the chances of error.

Added if brackets to single statement if-blocks

---

extensions/wikidata/src/org/openrefine/wikidata/qa/QAWarning.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/CalendarScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstraintScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/WhitespaceScrutinizer.java

In case when we know, the kind of class we want to check before runtime, we should prefer using instanceOf operator in place of isInstance method.

Replaced isInstance method by instanceOf operator

---

main/src/com/google/refine/LookupCacheManager.java
main/src/com/google/refine/expr/functions/Cross.java
main/tests/server/src/com/google/refine/expr/functions/CrossTests.java

(Closes #2504) 
Can #200 be closed by this PR?
Currently, cross() can take 3 arguments: 
```
cross(cell or value, string projectName, string columnName)
```
In this PR, I added the following enhancements as mentioned in #2504 :
1. projectName will be optional and will be interpreted as the current project name if omitted or set to "".
2. columnName will also be optional and will be interpreted as the index column if omitted or set to "". Note that I don't mean a column with the name "index" by saying "the index column", it's actually a column with name "_OpenRefine_Index_Column_Name_", which is the inner name of the index column. See [Cross.java](https://github.com/OpenRefine/OpenRefine/pull/2518/commits/5d063f7ca965d1a8b8346fa528ed5a4bff0e687a#diff-d4f3fbf156f6686e6d9b4358766804edR50) …

Support default project name and column name for GREL cross() function

---

main/src/com/google/refine/io/FileProjectManager.java
main/src/com/google/refine/io/ProjectMetadataUtilities.java
main/src/com/google/refine/preference/PreferenceStore.java
main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
pom.xml

Fixes #2543 Fixes #2544 Fixes #2627.
Always use UTF-8 to write JSON because platform default encoding
might not be legal JSON (e.g. ISO 8859-1).
Also be more conservative about keeping backups if we fail to write.
Two open questions:
- Are we using the correct filter on write? Looks like it could be wrong.
- Do we want to make sure that we can deserialize the written file before declaring success? That would have saved us from the user data loss due to the write/read mismatch here.

Save preferences JSON using UTF-8 encoding. Bulletproof prefs load.

---

main/webapp/modules/core/styles/project.less

Fix a bug introduced by I #1038, where the first tab, in the Wikidata mode, would have a bad background. PR #2616

(I #1038) Fix a bug introduced by PR #2616

---

main/pom.xml
main/src/com/google/refine/ProjectManager.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/src/com/google/refine/io/FileProjectManager.java
main/tests/server/src/com/google/refine/ProjectManagerStub.java

NOTE: Changes this changes the Project Manager public API where some of the old types were embedded which means that any extensions that extend these interfaces will have to be updated.
Fixes #2690. Replaces #2645

Replace Apache Ant with Commons Compress

---

main/src/com/google/refine/importers/JsonImporter.java
main/tests/server/src/com/google/refine/importers/JsonImporterTests.java

Attempt to fix issue #1164 .
**Source of error:**
The JacksonParser does not accept unquoted control chars (ASCII characters with value less than 32) unless udpate it's features. 
Parsing unquoted chontrol chars will cause an  `Illegal Unquoted character` exception. 
**Tests**:
1.  Implement new test cases to ensure parser works as expected.
2.  Using the attached test json file, illegal character (the tab) is converted into legal ones as shown in the preview.
testJson file: 
[testJson.txt](https://github.com/OpenRefine/OpenRefine/files/4345718/testJson.txt)

Convert illegal characters into legal ones.

---

main/src/com/google/refine/browsing/util/ExpressionNominalValueGrouper.java
main/tests/server/src/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java

Fixes #2588 
The bug results because the `ExpressionNominalValueGrouper` used in `ListFacet` treats row data in the same way in both row and record modes.
To fix this, we have to make sure we do not double count instances of unique non blank data in record mode. I added some additional scratch pad variables instead of creating additional methods (e.g. `visitRecordRow`) because it feels cleaner this way.
I also added a test for the `ExpressionNominalValueGrouper`. Although I tried to reuse the project set up in `@BeforeMethod`, I was facing a lot of trouble changing the project to run in record mode. Hence, I am currently using `parseCSVProject` for a small CSV example that I came up with for this issue.

Fix imprecise facet statistics in records mode

---

main/pom.xml
main/src/com/google/refine/importing/ImportingUtilities.java
main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java

* Fixes #1410 by virtue of HTTP Commons having built-in support for redirects. It also supports retries, gzip decompression, and a bunch of other stuff out of the box.
* Replaced external network tests with mockwebserver based tests which should be faster and 100% reliable. Refactored to remove redundancy and make quicker. Fixes #2680. Fixes #1904.
* Replaces use of deprecated methods in ImportingUtilities which had already been converted to use Apache HTTP Commons for project creation.

Use Apache HTTP Commons for Fetch URL

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js
main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/styles/common.less
main/webapp/modules/core/styles/index/default-importing-parsing-panel.less
main/webapp/modules/core/styles/views/data-table-view.less

Continuation for #2422 
- Fixed the orange bars
- Added a sticky header
> Only for `column-header` row (one with column names). The entire header group for XML/JSON (with the node structure) is not sticky yet.
- Fixed border of header elements in Firefox

Refactoring the data table into a single container

---

main/src/com/google/refine/commands/project/ExportRowsCommand.java
main/src/com/google/refine/exporters/TemplatingExporter.java
main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.js
main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.js
main/webapp/modules/core/scripts/project/exporters.js

Fixes #1197. Previously we were using a funky ContentType (`application/x-unknown`) to attempt to force a file download rather than display in browser, but this conflicted with attempts to save UTF-8 which was outside the Basic Multilingual Plane (BMP).
By switching to `ContentDisposition: attachment`, which has been the preferred method for a number of years, we can avoid this conflict.

Use ContentDisposition instead of ContentType to control download

---

main/pom.xml
main/src/com/google/refine/importers/RdfTripleImporter.java

This replaces #2705 and #2706. All the Jena dependencies need to be updated at the same time.
This introduces a new explicit dependency on Apache commons-io, which really should be a transitive dependency of Jena=>jsonldjava=>commons-io, but for Jena 3.8+, the transitive dependency no longer works.
Ideally we would switch to using a single Jena dependency, like the recommended `apache-jena-libs` but that doesn't work for us (it can't find the JSON-LD parser), so I'll leave that for a later time.

Bump Jena from 3.6.0 to 3.15.0

---

.github/workflows/maven.yml

For #2462.
Since the workflow is not active on pull requests, CI will not actually test the PR before it is merged.

Delete older snapshot releases

---

main/tests/server/src/com/google/refine/process/ProcessManagerTests.java
main/tests/server/src/com/google/refine/util/TestUtils.java

No issue. One of the Process Manager tests can fail intermittently (It failed on an edit of the README)  due to a race where the process under test finishes between the two test points so that the status changes from `running` to `done` causing the serialized JSON comparison to fail.
This PR fixes the race and also cleans up the test utility methods which were printing two copies of the diff.

Fix race in Process Manager

---

lgtm.yml

In #2756 I think we have a spurious alert, because OpenRefine can be used over HTTP locally and therefore cookies should not need to be sent over HTTPS by default. This attempts to disable this check in LGTM.

Ignore insecure cookie alert in LGTM

---

.github/workflows/maven.yml

Graciously, Reddy has added a new option for us to `delete_tags`
https://github.com/dev-drprasad/delete-older-releases#delete_tags
Also, Reddy mentioned in his PR we can just do manual cleanup (via Git cli) for the old tags that are not associated to a release.

Add new option for deleting tags associated to releases

---

main/pom.xml

Fixes #2777.
This removes the following jars from `main/webapp/WEB-INF/lib`:
```
powermock-reflect-2.0.7.jar
annotations-13.0.jar
mockito-core-3.3.3.jar
mockwebserver-4.7.2.jar
powermock-api-support-2.0.7.jar
javax.inject-1.jar
powermock-core-2.0.7.jar
javassist-3.27.0-GA.jar
aopalliance-1.0.jar
kotlin-stdlib-1.3.71.jar
jcommander-1.72.jar
byte-buddy-1.10.5.jar
kotlin-stdlib-common-1.3.70.jar
hamcrest-core-1.3.jar
snakeyaml-1.21.jar
junit-4.13.jar
testng-7.1.0.jar
okio-2.6.0.jar
byte-buddy-agent-1.10.5.jar
okhttp-4.7.2.jar
powermock-module-testng-common-2.0.7.jar
powermock-api-mockito2-2.0.7.jar
objenesis-2.6.jar
guice-4.1.0-no_aop.jar
powermock-module-testng-2.0.7.jar
servlet-api-2.5.jar
```
The last one being removed because it is already provided by the `server` module.

Restrict copied jars to runtime dependencies

---

pom.xml

Fixes #2780 
I didn't look into this too deeply, so it might be that defining an empty `surefireArgs` param is a better way to go, but either way it needs to be made consistent. I suspect that Eclipse is being pickier than Maven about missing parameters.

Fix reference to undefined surfireArgs param

---

main/src/com/google/refine/model/recon/StandardReconConfig.java
main/src/com/google/refine/operations/recon/ReconOperation.java
main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java

Fixes #2590 et al. Addresses some of #2229.
- Handle non-JSON returns (fixes #1128)
- Handle missing `name` parameter for reconciliation candidates
- Widen catchall exception handler to deal with all exceptions
- call job cleanup code in case of failure so that control returns to user
- add default constructor to stop Jackson from complaining. I'm not sure why this is needed and/or worked before. Perhaps it's reconciliation service specific? Was testing against Magnus' (broken) Wikidata recon service
This could use some tests, but we don't currently have any tests of the reconciliation process itself, so it would require mocking a (badly behaved) reconciliation end point.

Better error handling for reconciliation process - fixes #2590

---

extensions/gdata/pom.xml
extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java

This replaces dependabot's PR #2735 by dropping the unnecessary dependencies. It also updates the Google Drive and Google Sheets dependencies so that everything is up-to-date, replacing #2656 #2674.
Works with both the current and the repaired Google Sheets code.

Update Google API dependencies for GData extension

---

refine

No issue #.
This key was used for the Freebase APIs and is no longer referenced anywhere.

Remove obsolete Google API key reference

---

extensions/gdata/src/com/google/refine/extension/gdata/SpreadsheetSerializer.java
extensions/gdata/src/com/google/refine/extension/gdata/UploadCommand.java
extensions/gdata/tests/src/com/google/refine/extension/gdata/SpreadsheetSerializerTests.java

Fixes #2760 along with a variety of problems that I found when testing fixes for it and fixes #2306..
- upload in chunks instead of serializing the entire document at once
- Free up resources as we go
- stop if an error occurs
- reduce batch size to try and stay in 10MB request size limit
(but need a more dynamic way to do this probably for very wide
sheets or sheets with large values)
- preserves cell data type on upload - fixes #2785.
I'll open issues for some of the other things. The whole thing is kind of a mess.

Improve Google Sheets upload

---

main/src/com/google/refine/importing/ImportingManager.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/importing/ImportingManagerTests.java
main/webapp/modules/core/MOD-INF/controller.js

Fixes #2805. Fixes #2800. This includes three fixes / improvements:
- Fix Content-Type handling to correctly extract the `charset` (which we call "encoding") - no issue
- Implement support for Structured Syntax Name Suffixes on media types so that we'll fall back to `text/json` or `text/xml` for mediatypes which have `+json` or `+xml` suffixes if we don't have an entry for the full type - issue #2800 / #2805
- Switch the default fallback type from `text/line-based` to `text` so that we try the most general guessing strategy. The other will only try to guess TSV, CSV, or Fixed formats, so will never find JSON or XML files with the character frequency guesser. - no issue

Create Project import improvements

---

main/pom.xml

Replaces #2743 where dependabot wants to update an unused dependency.

Remove commons-digester dependency

---

main/webapp/modules/core/scripts/views/data-table/data-table-view.js

(Related to I #2624)
Change the preference key name `ui.gridPaginationSize` to `ui.browsing.pageSize`.
@wetneb: per @tfmorris suggestion in I #2520, I would change the preference key.
Since it's the choices, is could also be: `ui.browsing.pageSizeChoices`. But that is probably too long.
Regards,
Antoine

Change pref name for ui.browsing.pageSize

---

main/pom.xml
main/tests/server/src/com/google/refine/importers/RdfTripleImporterTests.java

Fixes #2824
Versions up through 3.14.0 appear to work, but since odfdom bundles
Jena 3.9.0, we're going to be conservative and match that.
As an added bonus, includes a blank node test which will trigger
the failure.

Fall back to Apache Jena 3.9.0 (from 3.15.0)

---

extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java

No issue. Restore missing piece of commit 42354c0 so that Builder has the method parameter that it needs.
Not sure what happened here, but the code that I committed isn't the same as I tested with and it doesn't work. This fixes it.

Fix update to deprecated Google Drive credential code

---

extensions/database/module/scripts/project/database-exporters.js

Fixes #2805. 
Fix database extensions exporter which is corrupting the dictionary name with the value of the language.

Fix i18n. Fixes #2805

---

main/src/com/google/refine/util/ParsingUtilities.java

Probably should remove the funky Gzip support with the overloaded use of the encoding parameter, since it doesn't seem to be used anywhere, but this is a start.

Minor refactor - Use Apache IO Commons IOUtils instead of homerolled

---

extensions/gdata/src/com/google/refine/extension/gdata/UploadCommand.java

Fixes #2797. Changes mimetype from zip to gzip and adds .tar.gz extension to the name.
Testing this depends on #2828 for a functional Google Drive export.

Correct mimetype for Google Drive project exports

---

main/src/com/google/refine/importers/tree/TreeImportUtilities.java
main/tests/server/src/com/google/refine/importers/XmlImporterTests.java

Fixes #2863
The tree importer sorts columns/column groups by how populated
they are, which is of arguable utility, but the tie-breaker
of ordering by shortest column name is completely silly.
This change removes that and, in conjunction with a stable sort
algorithm, will preserve the original order of the columns.

Remove shortest-column-name ordering - fixes #2863

---

.travis.yml

Fixes #2861
- Only builds one each of JDK 8,11-14
- Fixes all validator warnings
- Switches default build environment to bionic
- Uses trusty for an Oracle JDK 8 build
- Adds OS X build
- Adds JDK 13 & 14 builds
- Adds placeholder for JDK 16 builds (but Jacoco doesn't currently support it, so commented out)
- Reorders build jobs so that most informative ones run first
- Split before_install into before_install and before_script sections

Adjust Travis build environments - fixes #2861

---

.travis.yml
main/src/com/google/refine/clustering/binning/FingerprintKeyer.java
main/tests/server/src/com/google/refine/clustering/binning/KeyerTests.java

Fixes #2898. Fixes #409. Refs #650
Replaces homegrown ISO Latin-1 only character subsitition with standard Java Normalize to NFD, followed by diacritic removal and a few custom character expansions/replacements.

Use standard text normalization - fixes #2898

---

.travis.yml

- On Mac, sleep for a bit after database server startup before trying to connect
- Use default JDKs on each build platform to avoid having to do Java installs (Xenial Oracle JDK 8, Bionic OpenJDK 11, OS X Oracle JDK 14)
- Make jobs which require installations optional so they don't fail the build (OpenJDK 12 & 13)

Tweak CI build settings - refs #2861

---

main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/importers/ExcelImporter.java
main/src/com/google/refine/importers/OdsImporter.java
main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java

Uses the OpenRefine 3.0+ date type of OffsetDateTime instead of the original java.util.Date.
Also added date tests which I was too lazy to figure out 8 1/2 years ago when I wrote the tests and added some utility methods to centralize date checking and conversion.

Fix Excel date import - Fixes #1908

---

main/src/com/google/refine/exporters/sql/SqlCreateBuilder.java
main/tests/server/src/com/google/refine/exporters/sql/SqlExporterTests.java
main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
main/tests/server/src/com/google/refine/importers/XmlImporterTests.java

No issue. This removes a bunch of logging messages left over from development by either changing them from `info` to `debug` level or removing them altogether.
I'd like to get rid of the stack traces from the expected exceptions too, but they're logged from the production code, not the test code in most cases.
The end goal is to have the tests be quiet when they're passing so that the offending problem is easily spotted when they're failing.

Remove informational logging from tests that are passing

---

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/WikidataConstraintFetcherTests.java

After adding the code for fetching parameters for different scrutinizers in their corresponding classes, we should remove the redundant code from the ConstraintFetcher interface and WikidataConstraintFetcherClass.

Remove unused scrutinizer specific methods

---

main/tests/server/src/com/google/refine/commands/lang/LoadLanguageCommandTests.java

Fixes #2895. The test fails consistently if run on its own, but can succeed if another test that correctly initializes the ProjectManager runs first. This patch adds the local initialization of a FileProjectManager.
The second commit is whitespace changes only to fix the indentation in the module (remove tabs).

Fix order dependent NPE in LoadLanguage test

---

extensions/wikidata/tests/src/org/openrefine/wikidata/qa/ConstraintTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstaintScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizerTest.java

After the cleanup of MockconstraintFetcher, WikidataConstraintFetcher & ConstraintFetcher, replacing the hardcoded constraint IDs & property IDs with the values already defined in the corresponding scrutinizers to reuse in the test classes.

Reuse Constraint IDs and Property IDs

---

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinRangeScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EditScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstraintScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizer.java
extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizer.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstaintScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizerTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizerTest.java

As findValues method is not concerned with fetching, therefore moving it to EditScrtuinizer as suggested by @afkbrb in his [comment](https://github.com/OpenRefine/OpenRefine/pull/2925#issuecomment-658496080)

Move findValues method to EditScrtuinzer

---

.github/ISSUE_TEMPLATE/bug_report.md

- Motivating change is removal of boilerplate text before description so we can see more of the description in hover previews.
- Also changes section headings from bolded to headings 
- And combines OpenRefine version in same section as other versions

More bug template tweaks

---

main/pom.xml
server/pom.xml

Fixes #2917
Update to Butterfly 1.0.4 which catches NoClassDefFound errors for Butterfly modules (ie OpenRefine extensions) which are missing Java dependencies (e.g. those built against earlier versions of OpenRefine)
[Obviously, this has a dependency on Butterfly 1.0.4 being published first]

Update to Butterfly 1.0.4 - fixes #2917

---

main/pom.xml

Bump to vicino 1.2 with bug fix and real POM.
Drop dependencies on secondstring and arithcode which are just transitive dependencies from simile-vicino, now that it has a
proper POM. Fixes #2959.

Update to vicino 1.2 and drop transitive dependencies - fixes #2959

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js
main/webapp/modules/core/scripts/views/data-table/data-table-view.js

The rendering functions for rows and cells use jQuery which causes a greater overhead. Replacing it (in cases where it isn't necessary) by javascript speeds up the functions tremendously. 
The comparison below is across 10 rows and 15 columns. The difference increases with greater number of rows and columns.

Faster rendering of rows and cells

---

.gitignore

.factorypath file gets added as a changed file in source control depending on the IDE you are using (I use VS Code).
Added a few other exclusions that my previous team used to add to our Java projects.

Add .factorypath and others to .gitignore

---

main/pom.xml

Fixes #3039 
Limits only asking Git for 2 properties, branch and commit id abbrev

Speed up git commit extraction

---

main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/expr/functions/strings/ToFromConversionTests.java
main/tests/server/src/com/google/refine/io/ProjectMetadataTests.java
main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java

Fixes #3026. 
- Use `Instant.truncate(DAYS)` instead of homebrew offset calculation.
- Fix handling of unknown language code as first format string. It was creating 160 copies of it and trying to convert (unsuccessfully) with them all.
The unknown language code used to return an `EvalError` but that behavior was changed and the test that covered it was disabled. Presumably this was intentional, but I'm not sure why. 
@ostephens do you know why?

Fix ToDate test failure & inefficiency - fixes #3026

---

main/src/com/google/refine/importing/ImportingUtilities.java

Also split filename suffix at last dot in case of filenames with multiple dots.
Fixes #3043

Add separator to zip slip check - fixes #3043

---

main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java

Neither of these tests are testing OpenRefine code
(and a negative `assertNotEquals` test is useless anyway)
I started to update the use of the deprecated Apache class, but then realized that that entire test is testing Apache code, not any of our code.
I was also going to convert the `assertNotEquals` test to an `assertEquals` test with the correct value, but realized that a) it will vary by timezone and b) we never use LocalDateTime.toString() anywhere, so it's a useless test.

Remove tests of third party code

---

CODE_OF_CONDUCT.md

We asked the steering committee to help with forming a code of conduct committee for the project.
The idea is that this committee should be formed of project members who are unlikely to be involved in any dispute directly, because they are not involved in the day-to-day development. By listing their names explicitly in the CoC document we are making it more likely that people actually reach out to them if there is any issue (otherwise they could hold back, thinking that the person they have a problem with could be in the committee too).

Update code of conduct committee members

---

main/src/com/google/refine/importers/TextFormatGuesser.java
main/tests/server/src/com/google/refine/importers/TextFormatGuesserTests.java

Fixes #3061. 
Corrects #2924 which was intended to fix #2853 
The count of C0 controls now excludes any whitespace characters (HT, VT, FF, LF). It's still a fixed threshold, not a percentage of total characters.

Don't count TABs as control characters - fixes #3061

---

main/webapp/modules/core/about.html

Fixes #3088. Extracted from #3087 
-  Updates jQuery version and scripts which have OpenRefine version. 
- Adds i18n scripts to prep for i18n of page (#3089) 
- Removes obsolete text references old Freebase logo (unrelated, but minor cleanup)

Fix About page script references - fixes #3088

---

.github/ISSUE_TEMPLATE/feature_request.md

This applies the parallel changes which were made in #2946 for the bug report template.

Update enhancement request template to match the bug report template

---

main/src/com/google/refine/grel/controls/ForEach.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/expr/functions/GetTests.java
main/tests/server/src/com/google/refine/grel/GrelTests.java
main/tests/server/src/com/google/refine/grel/controls/ForEachTests.java

Fixes #3149. 
* Implements support for JSON Object as first argument to `forEach()`
* Adds tests for existing `forEach()` forms in addition to the new one
* Refactors tests to move helper method to `RefineTest` super class & move get() tests to the appropriate module

Extend forEach() to support JSON objects

---

main/src/com/google/refine/expr/functions/arrays/Sort.java
main/src/com/google/refine/expr/util/JsonValueConverter.java
main/src/com/google/refine/util/JSONUtilities.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/expr/functions/arrays/SortTests.java

Extend `sort()` to handle arrays with nulls. Fixes #3152
- Instead of NullPointerException on nulls, sort them last
- add JSON helpers to return Comparable[] in addition to Object[]
- Non-homogenous arrays or arrays with non-primitive  objects (array or object) are not sortable
- Add tests for both new and old sort functionality
NOTE: we could also sort `null`s first, but I arbitrarily picked last.

sort() handles nulls instead of throwing NPE - fixes #3152

---

main/src/com/google/refine/commands/Command.java

Partial fix for #3145 
- Include the exception name with the message returned to the user.
Still to do in a separate PR - redo error dialog so that stack trace is available (but hidden by default)

Improve exception reporting - refs #3145

---

main/src/com/google/refine/importers/FixedWidthImporter.java
main/src/com/google/refine/importers/LineBasedImporter.java
main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/src/com/google/refine/importers/TabularImportingParserBase.java
main/src/com/google/refine/importers/WikitextImporter.java
main/src/com/google/refine/importers/tree/ImportParameters.java
main/src/com/google/refine/importers/tree/TreeImportingParserBase.java
main/src/com/google/refine/importers/tree/XmlImportUtilities.java
main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesStub.java
main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java

Refs #2963. Followup to #2978. This tidies up a few loose ends from the importer refactoring:
- reverts the archive file name changes to ImportParameters and marks the entire class as deprecated since it was just introduced at the beginning of all this silliness
- removes unused parameters from `TabularImportingParserBase.readTable()` to make it easier to figure out what's used where and marks the old method signature as deprecated
- ditto for `XmlImportUtilities.importTreeData()` and some related methods in that class. Switch them back from using `ImportParameters` and having to guess which of its members they depended on to using specific parameters.
- removes duplicate fileSource and archiveFileName setting code from `XmlImportUtilities`. Likely not a functional problem, but a …

Importer refactoring cleanup

---

main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java

Disable flaky wikitable importer test so that we have a reliable CI infrastructure until #3128 can be worked on.

disable flaky readTableWithLinks test - refs #3128

---

refine.ini

Fixes #3204 
Clarifies comments for:
- Google Data OAuth config
- JVM heap
NOTE: Our current JVM max heap settings are *lowering* the size computed for the default on my machine (4096 MB => 1400 MB), so we may just want to accept the defaults unless the user specifically wants to override them.

Clarify refine.ini comments - fixes #3204

---

main/src/com/google/refine/expr/functions/arrays/Uniques.java
main/tests/server/src/com/google/refine/expr/functions/arrays/JoinTests.java
main/tests/server/src/com/google/refine/expr/functions/arrays/ReverseTests.java
main/tests/server/src/com/google/refine/expr/functions/arrays/SortTests.java
main/tests/server/src/com/google/refine/expr/functions/arrays/UniquesTests.java

Fixes #3235. Also adds tests.
Unrelated bonus test additions include:
- enables an array `sort` test that wasn't annotated correctly.
- adds tests for `reverse` and `join`

Maintain ordering for GREL uniques() function

---

main/src/com/google/refine/commands/GetVersionCommand.java
main/webapp/modules/core/about.html
main/webapp/modules/core/scripts/index.js
main/webapp/modules/core/styles/index.less

Fixes #3240. 
- Adds Java runtime name and version to the GetVersionCommand
- Displays the returned information on the About page. 
- Removes non-functional (and confusing!) embedded in the HTML on the About page.
Also minor cosmetic fixup to lower left corner of home page to visually center elements.

Add Java runtime name & version to About page - fixes #3240

---

.travis.yml

Refs #3208
- Enable Java 16 (early access) builds now that we have Jacoco 0.8.6 with support for it
- Allow flaky Travis CI Mac build to fail 
- Add Java 14 Linux build to replace Mac
- Only do full build matrix on pushes to master (mostly PR merges) or release (e.g. v3.5) branches.
- Pull requests against master and pushes to feature branches only get a single Java 8 build

Travis CI build config changes

---

docs/docs/index.md
docs/docs/manual/installing.md
docs/docs/technical-reference/build-test-run.md
docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Also update docusaurus config to match new version and fixed some broken links in the documentation, but not sure
if the latter were related to the version change.
Not really much of a risk since it's in only in our documentation build system, but this will let us getting rid of the annoying nag.
Fixes #3031

Update to docusaurus-2.0.0-alpha.64 to fix security vuln in dependency

---

main/src/com/google/refine/clustering/binning/FingerprintKeyer.java
main/src/com/google/refine/clustering/binning/NGramFingerprintKeyer.java
main/tests/server/src/com/google/refine/clustering/binning/KeyerTests.java

Fixes #3282 
- include all Unicode whitespace characters in splitting delimiter and don't strip controls which are whitespace (HT, LF, VT, FF, CR, NEL)
- add C1 controls to control characters that are stripped
- refactor string normalization to reduce redundancy between two keyers
- minor cleanups, simplifications, and performance optimizations

Improve fingerprint keyers - fixes #3282

---

.github/FUNDING.yml

As per GitHub Support, the only other thing left to do is also publish the FUNDING.yml file that links to the Organization itself to our OpenRefine repo so that folks visiting the repository directly will also see the Sponsor button.
>Jack (GitHub Support)
>Sep 1, 2020, 5:51 PM UTC
>
> Hi Thad,
> 
> I ran this by our Sponsors product team, and they said that the link I shared https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository should have the correct information to add the Sponsors button to a repo. If you have any specific suggestions on how to improve it, we're definitely open to hearing how it can be improved or less confusing.
> 
> They said:
> 
> If they want the Sponsor button to show up in the OpenRefine/OpenRefine repo, then …

Create FUNDING.yml to have Sponsor button for repo

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js

Fixes #3173. Don't assume that the query always succeeds.
Error reporting is rudimentary (alert), but better than nothing, which is what we had before.
In addition to the originally reported error, this will also catch 403 Forbidden codes which will become more common as reconciliation services implement authentication

Check for errors on Guess Types query - fixes #3173

---

.github/workflows/maven.yml

This is an attempt to temporarily re-enable the `set-env` command, to make sure our CI stays green, before we figure out how to use the new system.
For #3341

Temporary workaround set-env deprecation

---

main/src/com/google/refine/expr/functions/strings/Phonetic.java
main/tests/server/src/com/google/refine/expr/functions/strings/PhoneticTests.java

Fix:
There is one test case missing in the file in the phonetic.java due to which it fails to validate the second argument when it is not string or number and hence falls back to default behaviour of considering "metaphone3" as its second argument.
Adding a if-else case for checking second argument solves the issue.

Fix for issue #3330 grel phonetic-function

---

main/pom.xml
main/src/com/google/refine/commands/recon/GuessTypesOfColumnCommand.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/src/com/google/refine/model/recon/ReconciledDataExtensionJob.java
main/src/com/google/refine/model/recon/StandardReconConfig.java
main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/src/com/google/refine/util/HttpClient.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java

Fixes #3129. 
Makes the following improvements to the Fetch URL code:
- switches to Apache [HTTP Client 5.0.2](https://www.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-5.0.x.txt) including support for HTTP/2 as well as automatic retries and other general improvements
- reuses HTTP client across requests for the entire operation rather than rebuilding it for every request to improve connection reuse and not pay connection setup cost every time (especially bad for HTTPS)
- honors Retry-After header (built-in support), but if none specified uses binary exponential backup (default is single retry at 1 sec.)
- computes interrequest delay using a request interceptor
~~Because the namespace was changed, the new client can coexist with the old client, but we should probably abstract …

Refactor HTTP code into common module & Improve Fetch URL  - fixes #3129

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.js

Fixes #501 
Used the built in dialog system to create the small popup asking for confirmation.
Chose the 'Remove Expression?' and the 'OK' and 'Cancel' for the text as they were already in the translation files.

Added confirm dialog for starred expression remove links #501

---

server/pom.xml

On the `new-architecture` branch, I couldn't find the old codeberry groupId but see on Maven Central that we have it contained in the `org.openrefine.dependencies` for now, so let's update that pom to make the clean/build seamless for folks like me wanting to help test later.

fix broken jdatapath dependency not found

---

.github/dependabot.yml
main/tests/cypress/yarn.lock

fixes #3444 
- Fixes the wrong dependabot config for website_deps
- Introduces dependabot for cypress
- Bumps cypress to 6.0.2

feat: introduce dependabot for cypress suite

---

.github/workflows/pull_request.yml

- Looks like pull_request_target doesn't build fresh changes in PR, hence replaced it with `on: pull_request`, please ignore the failed check for `pull_request_target` as the same test is getting passed on `pull_request`.
- As well as I have disabled CI on changes only involving docs subdirectory as they are not needed when we do changes in the docs-website.
- I have fixed the cache path to cache the cypress binaries properly.

fix: cache all UI paths for cypress

---

main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html

added link to <a> element for help on available date formats.
Fixes #3362

Fix help link for date formats

---

docs/src/css/custom.css

As suggested by @ostephens orally, this attemps to shrink the blue boxes around menu items:
**Before:**
**After:**

Adjust the menuItem class to avoid colliding borders

---

docs/docs/index.md

This documentation PR fixes links which currently 404 on the Introduction page by adding `manual/` to the path of the relevant links.

Fix links on Manual Introduction page.

---

main/tests/cypress/yarn.lock

fix: properly migrate to cypress 6.2.1

---

.github/workflows/snapshot_release.yml

I "think" this small change is the right way to prevent unnecessary snapshot release workflow run such as this one:
https://github.com/OpenRefine/OpenRefine/actions/runs/515619980
when the only files changed were in the /docs folders in a PR that was merged into master branch.
Example from: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1

Prevent snapshot release when only docs push

---

GOVERNANCE.md

Update Governance and Contributing doc

---

docs/docs/manual/installing.md

Re-instates the Tabs and TabItem imports. Without these the installing page in the documentation doesn't display correctly with the relevant information for Windows/Mac/Linux

Re-instating Tabs import

---

extensions/gdata/module/scripts/gdata-extension.js
extensions/gdata/module/scripts/index/gdata-source-ui.js

Fixes #3054.
- adjust for new undefined return value of cookies package which was introduced with the JQuery UI 1.12 update
- add some error handling in case we think we're logged in, but really aren't

Fix Google Data isAuthorized check - fixes #3054

---

extensions/gdata/module/scripts/index/gdata-source-ui.js
extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java
refine
refine.bat
refine.ini

Fixes #3604.
Enables access to public data in Google Sheets/Drive. API key must be sent if OAuth token isn't.

Add Google API key - fixes #3604

---

CONTRIBUTING.md

These should be better integrated, but as a stopgap, just include the link

Link to wiki page on first pull request

---

main/tests/cypress/cypress/integration/project/grid/column/transpose/cell_accross_columns.spec.js
main/tests/cypress/cypress/integration/project/grid/column/transpose/cells_in_rows.spec.js
main/tests/cypress/cypress/integration/project/grid/column/transpose/columnize.spec.js
main/tests/cypress/cypress/support/commands.js

Added tests for the transpose functionalities of OR
Basically, it follows [tutorials found on the doc](https://docs.openrefine.org/manual/transposing/)
Does this needs to be improved ?
Any missing or critical points that are not covered by the present tests ?
@kushthedude please have a look at the new command available, `cy.assertGridEquals`, it let us test the whole grid in one single assertion

test: Added tests for transpose functionalities, #3426

---

GOVERNANCE.md

Most of these changes are small improvements to sentences that did not feel super natural to me.
But one important difference is the change from
> Committers have earned enough trust from the community to have direct access to the project code base without having to submit pull request. Committer seek approval after the contribution is made, rather than before.
to
> Committers have earned enough trust from the community to review and merge pull requests.
As discussed in #3198 it is important that pull requests are used systematically, even by those who have the rights to merge them.
The sentence "Committers seek approval after the contribution is made, rather than before" felt like committers could just push to master and discuss afterwards, which isn't how we have been doing things for …

Follow-up improvements to GOVERNANCE.md after #3198

---

README.md

In December 2020, mobile clients can no longer connect to OpenRefine room for Gitter since the mobile clients are now deprecated.  Also since [Gitlab has sold Gitter and now officially has now moved to the Matrix.org Foundation (London)](https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix) and they now have an updated bridge for our room.
I spoke with Gitter support (Matrix) and they provided the new URL.  Which even shows up when using iOS app or Web via Element.io  We just need to provide this for easy onboarding for users.
https://matrix.to/#/#OpenRefine_OpenRefine:gitter.im
So I think we need to update this in our README.md

Add updated chat URL for Web and Mobile clients support

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js

Fixes #3028
- Create the pop-up before positioning it so that size can be considered in order to not overflow the window.

Make sure size of recon preview pop-up is set before positioning

---

main/tests/cypress/cypress/support/commands.js

Fixes https://github.com/OpenRefine/OpenRefine/pull/3676#issuecomment-796982412
There have been more frequent failures for ui_tests due to less timeout in the update preview-table.

fix: increase wait time for preview-table to update

---

main/webapp/modules/core/scripts/facets/facet.js
main/webapp/modules/core/scripts/project.js

Fixes #2891
Added the Refine.showLeftPanel() function.
When a facet is created, make sure the left panel is being shown.

Show left panel when a facet is created

---

main/webapp/modules/core/scripts/project.js

Fixes #2891
- If loaded thru a permalink, the new facets will not try to resize the display that is not yet loaded (and though crashes).
This fix a bug introduced in code merged to master yesterday.
Regards,
Antoine

Follow-up fix for facet panel resizing when using permalinks to restore facets

---

main/src/com/google/refine/commands/project/ExportRowsCommand.java

Fixes #3724 
- Support non-ASCII characters in export filenames
Tested on a Mac.  Follows [RFC6266](https://tools.ietf.org/html/rfc6266).

Support export filenames with non-ASCII chars.  (fixes #3724)

---

extensions/wikidata/src/org/openrefine/wikidata/commands/LoginCommand.java
extensions/wikidata/tests/src/org/openrefine/wikidata/commands/LoginCommandTest.java

Fixes #3745.
- Replace some special characters in cookie keys so that they are valid even by strict standards

Sanitize cookie keys in Wikibase extension

---

main/tests/cypress/cypress/integration/project/grid/column/edit-column/add_columns_based_on_this_column.spec.js
main/tests/cypress/cypress/integration/project/undo_redo/apply.spec.js
main/tests/cypress/cypress/support/commands.js

This PR is an attempt to fix some tests that are flaky.
- apply.spec.js
- add_columns_based_on_this_colum.spec.js
Also added some assertions to ensure OpenRefine is properly loaded in method `loadAndVisitProject`, I believe that should also help to lower the flakyness rate

Attempt to fix flaky integration tests

---

lgtm.yml

Currently LGTM is reporting alerts on problems found/fixed in external Javascript libraries which are included in our source tree. We don't control these, so this is just noise.
This PR changes the LGTM config to ignore external libraries. It has been successfully tested as part of #3087.

Have LGTM ignore external libraries for quality checks

---

.github/workflows/snapshot_release.yml

- CI was failing because java 1.8 is unknown for new java setup action

fix: unknown java 1.8 in build job action

---

main/webapp/modules/core/scripts/dialogs/extend-data-preview-dialog.js

Fixes #3809. Enables cross-origin property type-ahead.

Fixes #3809. Enables cross-origin property type-ahead.

---

main/tests/cypress/cypress/integration/project/grid/all-column/edit-columns.spec.js

Fixes and improve a test that was failing
@kushthedude the reason was that fill down, called from the "all" column is not editing columns all together, but one by one.
Hence, the grid re-render each time.
I noticed you're using food.small, and then apply some transforms to prepare the grid for initial testing conditions, it's actually best if you load a project from a json with the initial data you need to perform the test, so you don't need to prepare the grid for testing.

Fixed failing test edit all column / fill down

---

docs/docs/technical-reference/reconciliation-api.md
docs/docs/technical-reference/writing-extensions.md
docs/docusaurus.config.js
docs/static/js/fix-location.js

Closes #3819 by adding some JS code to remove trailing slashes at the end of documentation URLs.

Remove trailing slashes in doc pages URLs to fix links.

---

extensions/wikidata/module/scripts/schema-alignment.js
extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java

Fixes #{3816}
- one test for BCE year added in WbDateConstantTest.java
- make change in method parse() of WbDateConstant.java to support BCE year(for example, regard a BCE year -1100
- as 1100 when call other read-only methods and finally change the year from positive 1100 to -1100 when return the TimeValue for parse())
-

Support BCE dates in Wikibase upload

---

extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java
extensions/wikidata/tests/src/org/openrefine/wikidata/exporters/QuickStatementsExporterTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateVariableTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/testing/TestingData.java

Fixes #3694
- Adjust "extensions/wikidata/src/org/openrefine/wikidata/schema/WbDateConstant.java" and add a variable "segment" to judge whether the date has a precision smaller than year, month or day
- Adjust "extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbDateConstantTest.java" accordingly to test correctness.
- Note that the basic classes such as "Date" and "Calendar" are not modified since the authority is not assigned and I also think there isn't necessity to modify them because time like "1883-00-00T00:00:00Z" is actually not a real valid date.

Fix wikibase date export format

---

main/src/log4j.properties
server/src/log4j.properties

Fixes #3782.
For some reason the logging levels are now taken from the `log4j.properties` file in the `main` module, not the `server` one. Not sure why. Anyway, this restores the previous log levels, which makes the output less verbose.

Restore log levels after Jetty update

---

main/src/com/google/refine/util/HttpClient.java

Closes #3664.
By default, the Apache HTTP client does not retry POST requests in when basic network errors happen (such as a closed connection) because those requests are not deemed idempotent (so retrying them might generate a side effect on the server twice). But for reconciliation they are idempotent, so they should be retried.
It would be good to make this parameter configurable: if we add support for POST requests in the URL fetching operation, for instance, we could want to have a different behaviour there (not retrying by default). But I am a bit worried by the parameters we are gathering in the constructor of HttpClient, we should probably already introduce a builder class here.
The underlying issue is that the Apache HTTP client tries to reuse connections (which is useful) …

Make sure POST requests are retried even when connections are closed.

---

docs/versioned_docs/version-3.4/manual/installing.md

As of Homebrew 2.6.0:
> All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary. 
See https://brew.sh/2020/12/01/homebrew-2.6.0/.
Also, removed mention of openrefine-dev cask as this facility does not appear to be in use.

Update Homebrew documentation

---

.github/workflows/pull_request.yml
main/tests/cypress/cypress/integration/create-project/create_project.spec.js
main/tests/cypress/cypress/integration/create-project/preview_project.spec.js
main/tests/cypress/cypress/integration/project/grid/column/facet/scatterplot-facet.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/facets/by_judgment.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/reconcile.spec.js
main/tests/cypress/cypress/integration/tutorial/importing-data-into-openrefine.spec.js
main/tests/cypress/cypress/support/commands.js
main/webapp/modules/core/scripts/index/default-importing-controller/controller.js

Fixed several issues and problems we had with tests stability
- latest version of Cypress now properly handles some redirections used by OpenRefine, hacky code has been removed
- tests improvements to resolve flaky tests
- removed scatterplot visual testing (images diffs), that is not stable on edge
- Temporarily disabled `Test the create project from Web URL based on CSV`, those tests doesn't work with the last version of cypress, to be investigated separately in #4015
- fixed OpenRefine core javascript code to properly address #3678

Tests stability

---

docs/README.md

@wetneb Does this look OK?  I just tested and seems that this is how we can actually work and see the "next version" of docs and we didn't really document this anywhere as far as I can tell.  So this README section is a good place?
- Update Docs README about Next version
- 
-

Update info on Docs README about Next version

---

docs/docs/technical-reference/functional-tests.md
main/tests/cypress/cypress.json
main/tests/cypress/cypress/support/index.js
refine

Added an environment variable to disable projects cleanup on CI/CD.
This way we save an extra API call after each test run.
It will also fix [a flaky scenario](https://dashboard.cypress.io/projects/s5du3k/runs/1369/test-results/7f66c317-4292-4347-a6de-eed8e0397d4a) where the delete token wasn't found

Speed-up testing time for Cypress in CI/CD

---

docs/docs/manual/grelfunctions.md

Old link would not lead to any section in live documentation.
- fix internal link
- remove superfluous space
- "in to" -> "into"

fix internal link

---

main/tests/cypress/cypress/support/index.js

Updated the handler that catches edge windows exception.
The message thrown by edge changed

Cypress Testing, updated handled error message for Edge

---

docs/versioned_docs/version-3.4/manual/installing.md

... and doesn't work with Java 16 or later versions (see issue #4106).
This PR is a duplicate of #4134: I wasn't sure whether I should edit `docs` or `versioned_docs`, so edited both.

mention it requires java 14

---

.github/workflows/label_transfer.yml
.github/workflows/label_transfer/requirements.txt
.github/workflows/label_transfer/script.py

Fixes #4176.
- adds a Python script to transfer labels from issues to PRs.
We'll need to merge this PR before we can test its results.
This only runs for new PRs (or edited ones).

Add GitHub Action to copy labels from issues to PRs.

---

docs/docs/technical-reference/build-test-run.md

- Explicit mention of `git clone`
- Added currently supported jdk versions in Linux environments

Document clone command, and Java requirements

---

refine
refine.bat

Fixes #4265.
- Revert the faulty fix for #388.
- Let -m (on UNIX) and /m (on Windows) control both the initial heap size and the maximum one, so that we cannot run into the situation where the initial heap size is larger than the maximum one.

Fix CLI setting for memory size (-m and /m)

---

main/src/com/google/refine/util/ParsingUtilities.java

This pull request comes without tests because there is no clean way
to set the system timezone in a Java unit test:
https://stackoverflow.com/questions/23466218/setting-timezone-for-maven-unit-tests-on-java-8
The problem came from the fact that we were interpreting all dates with the current
zone *offset*, which varies during the year depending on DST, meaning that during the winter
we would interpret summer dates in a winter timezone, which does not make sense.
This changes the date conversion mechanism to only rely on the current zone, making sure
the correct offset is used depending on the value of the converted date.
Fixes #4294.

Fix date parsing to avoid offsets due to DST.

---

main/pom.xml

Closes #4296.
- temporary workaround by manually excluding a dependency. Fix has been proposed upstream: https://github.com/tdf/odftoolkit/pull/132

Exclude duplicate dependency from odftoolkit.

---

main/pom.xml
server/pom.xml

Fixes #4314
- Removes dependency to rhino-runtime
I might add further commits removing other libraries and let the CI decide if they are actually needed.
Other dependencies should get a comment in the POM to explain that `mvn dependency:analyze` reporting them as unused is a false positive.

Cleanup some unused dependencies

---

main/pom.xml

(No issue number)
Updates to this new version which does not depend on a vulnerable version of Apache Jena anymore.

Update odftoolkit to 0.9.0

---

extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js

Fixes #4268 
- Display validation error message when adding invalid manifests

Fix displayed msg when adding invalid manifests

---

extensions/database/pom.xml
extensions/gdata/pom.xml
extensions/jython/pom.xml
extensions/pc-axis/pom.xml
extensions/phonetic/pom.xml
extensions/pom.xml
extensions/sample/pom.xml
extensions/wikidata/pom.xml
main/pom.xml
pom.xml
server/pom.xml

Closes #4335.
Some dependencies which were clearly useful in a single extension
were left as such.

Centralize dependency versions and plugin versions in root POM.

---

docs/docs/manual/wikibase/configuration.md
docs/versioned_docs/version-3.5/manual/wikibase/configuration.md

ULS provides the [`languagesearch` API](https://www.mediawiki.org/wiki/Special:MyLanguage/API:Languagesearch) used to select term languages.
- Add ULS to the 3.5 docs
- (no other docs because IIUC arbitrary Wikibase support is new in 3.5)

Mention UniversalLanguageSelector requirement

---

.github/workflows/release_manager.sh
.github/workflows/snapshot_release.yml
README.md
appveyor.yml
benchmark/pom.xml
extensions/pom.xml
packaging/pom.xml
pom.xml

Closes #4346.
- integrate snapshot uploading into the Maven build process (for the standard `deploy` goal)
- remove scripts to upload to GitHub releases
This might need merging before it can be tested.

Use OSSRH snapshot repository to host snapshot releases.

---

refine

Closes #4375
- remove printout of Java command in the logs
- update link to documentation about memory allocation
- add delimiters to the memory allocation message
Current result:
```
Using refine-dev.ini for configuration
-------------------------------------------------------------------------------------------------
You have 7630M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://docs.openrefine.org/manual/installing#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
18:48:04.668 [            refine_server] Starting Server bound to …
```

Cleanup startup log on Linux

---

extensions/sample/pom.xml

hey,
the sample extension does not compile because of the main maven dependency
```
cd extensions/sample
mvn compile
..
Could not resolve dependencies for project org.openrefine:sample:jar:3.0-SNAPSHOT: org.openrefine:main:jar:3.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of snapshots has elapsed or updates are forced
```
This PR should address it

Fixed sample extension pom.xml

---

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
extensions/wikidata/tests/src/org/openrefine/wikidata/editing/EditBatchProcessorTest.java

Fixes #4268
- Factor out deprecated editor api in `EditBatchProcessor` for existing Item updates
- Update `EditBatchProcessorTest` class

Refactor editor api for existing Items

---

main/webapp/modules/core/styles/project.less

- Adds curvature to top-right corner of left-panel, and top-left corner of right-panel which highlights separation more to show the collapsible nature with new hide panel button. 
- removes unnecessary padding to better align left and right panel top edges visually.

Add border radius to left/right panel

---

pom.xml

Fix license download warning during packaging
- Updates `<name>` tag to a SPDX identifier https://spdx.org/licenses/ as recommended by https://maven.apache.org/pom.html#licenses
- Updates `<url>` tag to use raw content for easier preview with tools

Fix warning about license during packaging

---

extensions/wikidata/pom.xml
extensions/wikidata/src/org/openrefine/wikidata/commands/ConnectionManager.java
extensions/wikidata/src/org/openrefine/wikidata/commands/LoginCommand.java
extensions/wikidata/src/org/openrefine/wikidata/utils/EntityCache.java
extensions/wikidata/tests/src/org/openrefine/wikidata/commands/ConnectionManagerTests.java
extensions/wikidata/tests/src/org/openrefine/wikidata/commands/LoginCommandTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/commands/PreviewWikibaseSchemaCommandTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/testing/WikidataRefineTest.java

Fixes #4456
- rewrite tests in Wikidata extension not to use PowerMock

Migrate out of PowerMock for the Wikidata extension

---

docs/README.md

This updates our docs README.md to mention using LTS version of Node.js since there are numerous problems that exist if the Current version of Node.js is utilized to build our docs.  To mention just one that I had to deal with on Windows and Linux if LTS version was not utilized:
- Error: error:0308010C:digital envelope routines::unsupported
at String.replace (<anonymous>)
- export NODE_OPTIONS=--openssl-legacy-provider

mention Node.js LTS version for building our docs

---

.github/workflows/pull_request.yml
docs/docs/technical-reference/build-test-run.md
docs/docs/technical-reference/contributing.md
docs/versioned_docs/version-3.5/technical-reference/build-test-run.md
docs/versioned_docs/version-3.5/technical-reference/contributing.md

Fixes #2338
This adds support for Java linting in CI. The build will fail if the code is not correctly linted, which can be fixed by running `mvn formatter:format`.

Add linting check in CI

---

docs/docs/manual/installing.md
docs/versioned_docs/version-3.5/manual/installing.md

"All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary" from brew.sh/2020/12/01/homebrew-2.6.0
Related to issue #2191 in case users prefer the Brew option to the `.dmg` download. 
- Update commands from `brew cask install` to `brew install --cask` as suggested by brew.sh/2020/12/01/homebrew-2.6.0

Update brew installation

---

main/tests/cypress/cypress/integration/project/undo_redo/extract.spec.js
main/webapp/modules/core/scripts/project/history-extract-dialog.html
main/webapp/modules/core/scripts/project/history-panel.js

Closes #4498 
- Enabled the extraction of the Operation History list of actions, which is a JSON object, by downloading as a JSON file, called "history.json"
- On the Extract operation history dialog, added a button that can be used to initiate the above task, and placed it on the same level as the "Select all", "Unselect all" buttons, with a right float (to be placed close to the JSON textarea).
For the purpose of creating the downloadable file and actually downloading it on the user's computer, I used a small utility function from the following StackOverflow answer: https://stackoverflow.com/a/18197341/5564816
This approach works with HTML5, however, it could be prone to potential compatibility issues with old browsers.
If you have a better …

Extraction of the Operation History list as a downloadable JSON file

---

.github/workflows/pull_request.yml
.github/workflows/snapshot_release.yml
packaging/pom.xml
pom.xml

Closes #4521.
- cleanup packaging/pom.xml so that goals are bound to sensible phases

Fix packaging/pom.xml so that JRE is only downloaded when packaging

---

main/tests/cypress/cypress/integration/create-project/preview_project.spec.js
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html

Fixes #4299 
- Changed "parse next x lines as column header" checkbox to radio button and placing it with custom column names .
- minor replacement of the sections .
- reformated html file .

Turn column name parsing options of CSV/TSV importer into radio buttons

---

docs/docs/technical-reference/build-test-run.md

- Also adds more context that Maven is not entirely optional since our build, test, packaging now readily relies on it.
- Fixes typo for `MAVEN_HOME` env variable.
- Adds recommendation to use latest Maven otherwise spurious errors occur for some in their IDE's with Maven integration (VSCode).

Fix typo and add Maven installation link to tech docs (current)

---

docs/versioned_docs/version-3.5/technical-reference/build-test-run.md

- Also adds more context that Maven is not entirely optional since our build, test, packaging now readily relies on it.
- Fixes typo for `MAVEN_HOME` env variable.
- Adds recommendation to use latest Maven otherwise spurious errors occur for some in their IDE's with Maven integration (VSCode).

Fix typo and add Maven installation link to tech docs

---

docs/docs/manual/running.md
docs/versioned_docs/version-3.4/manual/running.md
docs/versioned_docs/version-3.5/manual/running.md

Fixes #3818
- Added -x examples in documentation files
Rich diff:

Documentation command line -x examples

---

main/src/com/google/refine/importers/tree/TreeImportingParserBase.java
main/tests/server/src/com/google/refine/importers/XmlImporterTests.java

Fixes #4566
Duplicates the base ImportingParserBase metadata append into the TreeImportingParserBase, which completely overrides the original method.

Fix missing import options metadata for XML

---

main/webapp/modules/core/styles/util/dialog.less

Fixes #4622
- Added spacing between ok/cancel buttons:

Spacing between ok/cancel buttons for custom text/numeric facet dialogs

---

main/src/com/google/refine/io/FileProjectManager.java

Fixes #4600 by setting `workspace.json` to be only readable by the user who wrote it.

Set more restrictive file permissions on workspace.json

---

extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java

Fixes #4631
- Added redirect to [wiki](https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension#missing-credentials) for when the Google export to Drive/Sheets options are clicked while the Google API credentials are undefined.

Redirect to wiki for Google Export options

---

docs/docs/manual/reconciling.md
docs/versioned_docs/version-3.5/manual/reconciling.md

(No issue filed — should I? I've just used the "Edit this page" link on https://docs.openrefine.org/manual/reconciling)
- fix typo in "reconcil**i**ation"

fix typo in "reconciliation"

---

extensions/wikidata/module/scripts/dialogs/logged-in-dialog.html
extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js
extensions/wikidata/module/scripts/dialogs/owner-only-consumer-login-dialog.html
extensions/wikidata/module/scripts/dialogs/password-login-dialog.html
extensions/wikidata/module/styles/dialogs/manage-account-dialog.less

Fixes #4628
- Move login note to be under the "Remember me" checkbox.
- Move dialog buttons to the dialog footer of Wikibase login and logged-in dialogs:

Wikibase dialog buttons

---

refine

Fixes #4644
- Modify MVN_VERSION="3.8.4" variable to MVN_VERSION="3.8.5" in refine script.
- 
-

fixes OpenRefine#4644 update Maven version to 3.8.5

---

main/src/com/google/refine/exporters/sql/SqlCreateBuilder.java
main/src/com/google/refine/exporters/sql/SqlInsertBuilder.java
main/tests/server/src/com/google/refine/exporters/sql/SqlExporterTests.java

Fixes #1940
- Substituting invalid characters in column names with an underscore for SQL Exporter
- The invalid characters are detected through the following regex: `[^a-zA-Z0-9_]`

[SQL Exporter] Substitute invalid characters in column names with underscore (#1940)

---

.gitignore

(no issue)
Since our Javascript dependencies are now managed by NPM, we should not add them back to the repository, hence the corresponding directory should be added to our `.gitignore`.
@elebitzero we are not currently tracking `main/webapp/package-lock.json`, but perhaps we should? Otherwise I would also add it to `.gitignore`.

Add 3rdparty js libraries to .gitignore

---

docs/docs/manual/installing.md

Fixes #4656
- Correct the inline link of "locate your workspace directory" in _**_Installing or upgrading --Back up your data_**_ section.
- Reconfigure the guidance to find workspace in section **Set where data is stored**
- Simplify steps to install extensions in section **Find the right place to install**
- Modify the path to be reachable

fix OpenRefine#4656 - clarify location of workspace

---

main/src/com/google/refine/expr/functions/date/DatePart.java

Fixes #1122 
- Addition of a link to the GREL docs in the Help section of the Expression dialog

Addition of a link to the GREL docs in the Help section of the Expression dialog

---

main/src/com/google/refine/commands/Command.java

Fixes #4540
The following Commands were not properly setting the Content-Type and Character Encoding in the the HTTP Header returned by the server:
* Save Wikibase Schema
* Denormalize
* Join Multi Value Cells
* Key Value Columnize
* Split Multi Value Cells
* Transpose Columns Into Rows
* Transpose Rows Into Columns
* Move Column
* Remove Column
* Rename Column
* Annotate One Row

Added encoding fix

---

docs/docs/technical-reference/build-test-run.md

Fixes #4675
- Replaced the non-accessible link to get testng with that stated [here](https://github.com/cbeust/testng-eclipse#install-release).

update link to get testng

---

docs/versioned_docs/version-3.5/technical-reference/contributing.md

Update contributing to add the notion of Issue assignements.
- Talk about assigning yourself to issues
- Talk about Program and mentors doing the assignment of GFI & GSI.

Update contributing.md for assignments and Programs (Outreachy & GSoC)

---

main/src/com/google/refine/grel/ast/OperatorCallExpr.java
main/tests/server/src/com/google/refine/grel/GrelTests.java

Fixes #377
- fix the division operator call to return a Double.NaN when `n1 <- 0, n2 <- 0`

set division operator call to return NaN on 0/0

---

.github/workflows/snapshot_release.yml

Fixes #4727 
The snapshot workflow file doesn't run `npm install` because it just runs `mvn package`, so this fix adds just adds `npm install` to that file.
- Added `npm install` to snapshot workflow.
The fix is minor but I'm unable to test.

Fixed snapshot builds

---

main/src/com/google/refine/LookupCacheManager.java
main/src/com/google/refine/util/HttpClient.java
main/src/com/google/refine/util/LookupException.java
server/src/com/google/util/logging/IndentingLayout.java
server/src/com/google/util/threads/ThreadPoolExecutorAdapter.java

Fixes #4735
Proposed Changes. 
As fur as Licensing is concerned, all the classes are supposed to have linces and some classes didnot have linces so we needed to have all the classes lincesed.
- Added Linces Headers to the classes that had no linces Headers. cc @antoine2711  @WaltonG .Kindly review

Add Headers Lincense to the project code base

---

.github/workflows/snapshot_release.yml

Fixes #4727 
- Moved `npm install` command up, and added `npm install` for Mac build.
I ran the commands locally and they copied the files in 3rdparty successfully but they don't show up in the real snapshot build for the original fix.

Fixed snapshot builds (attempt 2)

---

main/webapp/package.json

Updating underscore dependency (low-risk upgrade since it's only used in two places).

build(webapp): bump underscore from 1.51 to 1.13.2

---

main/webapp/package.json

Low-risk upgrade for the tablesorter dependency, as it is only used in one place (the open project UI):

build(webapp): bump tablesorter from 2.29.0 to 2.31.3

---

main/webapp/package.json

Low-risk upgrade for the moment dependency, as it is only used in one place (the open project UI):

build(webapp): bump moment from 2.19.2 to 2.29.3

---

main/webapp/modules/core/externals/imgareaselect/jquery.imgareaselect.js

(In preparation for upgrading jQuery to 3.6.0)
Low-risk upgrade for the imgareaselect dependency, as it is only used in one place (Facet -> Scatterplot facet):

build(webapp): bump imgareaselect from 0.9.2 to 0.9.11-rc.1

---

main/webapp/modules/core/scripts/dialogs/scatterplot-dialog.js

Migrating code step-by-step to prepare for the upgrade to jQuery 3.6.0
Most of the migration required for the jQuery upgrade can be done while still on the current jquery 1.12.4, so the plan is to incrementally migrate the code while on the old version, and then do the final changes to upgrade to jquery 3.6.0.  This will make the process more manageable and less risky.
In This PR: Replaced jquery API load(function) call which is removed in the latest version.

Replaced usage of removed load method for jQuery

---

main/tests/cypress/cypress/support/commands.js
main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.html
main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/project/history-apply-dialog.html
main/webapp/modules/core/scripts/project/history-extract-dialog.html
main/webapp/modules/core/scripts/views/data-table/cell-editor.html

- Made textarea closing tags explicit for jQuery 3.6.0 support.
- Increased the wait from 500ms to 1500ms on a flaky test.

Updated textarea closing tags for jQuery 3.6.0 support

---

main/tests/cypress/cypress/integration/preferences/change_preference.spec.js
main/tests/cypress/cypress/support/openrefine_api.js

- Added  a clean up for the preferences set in the Cypress tests.
- Changed test preferences to not use Date.now() because they are being cleaned up now.
Example of how the preferences are cluttered from running tests before these changes:

Cleaned up preferences set in Cypress tests

---

main/tests/cypress/cypress/integration/create-project/create_project.spec.js
main/tests/cypress/cypress/integration/create-project/preview_project.spec.js
main/tests/cypress/cypress/integration/import-project/import_project.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/actions/clear_reconciliation_data.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/actions/create_new_item_for_each.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/actions/discard_reconciliation_judgments.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/actions/match_to_best_candidate.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/add_entity_identifiers.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/copy_reconciliation_data.spec.js
main/tests/cypress/cypress/integration/project/grid/column/reconcile/facets/by_judgment.spec.js
main/tests/cypress/cypress/integration/project/grid/viewpanel-header/rows_records.spec.js
main/tests/cypress/cypress/integration/project/project-header/export_project.spec.js
main/tests/cypress/cypress/integration/tutorial/importing-data-into-openrefine.spec.js
main/tests/cypress/cypress/support/commands.js
main/tests/cypress/cypress/support/openrefine_api.js

Cleaned up projects that are being created through Cypress UI commands.  There is already a cleanup for projects created programmatically through cy.loadAndVisitProject().  However, if you run the Cypress test suite, there were 17 projects not getting deleted. See screenshot below.
* added addProjectForDeletion()
* added waitForProjectTable()
There are 17 projects created on each test run:
doaj article sample csv
1651727097719
1638261281543 csv
1638261281543 csv
1638261281543 csv
1638261281543 csv
1638261281543 csv
1638261281543 csv
1638261281543 csv
heym
1651726631244
Clipboard
food mini csvthis is a test
food mini csv
Clipboard
food mini csv
shop mini tsv

Cleaned up projects that are being created through Cypress UI commands

---

docs/versioned_docs/version-3.5/manual/installing.md

Broken or bad link.
Changed https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases to https://github.com/OpenRefine/OpenRefine-snapshot-releases
- Change https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases to https://github.com/OpenRefine/OpenRefine-snapshot-releases

Update installing.md for bad link https://github.com/OpenRefine/OpenRefine-snapshot-releases/releases

---

main/tests/cypress/cypress/integration/project/grid/all-column/edit-columns.spec.js
main/tests/cypress/cypress/integration/project/grid/column/edit-column/join_columns.spec.js
main/tests/cypress/cypress/support/commands.js

Three cypress tests that use drag-n-drop to reorder columns are flaky when using jQuery 3.6.  The issue arises when one column is dragged upward and it is dropped on the center of the other column name. By dropping the column name at the 'top' of the target, the tests work.
This fix also works with the existing jQuery.
The following tests are fixed with this change:
-  edit-columns.spec.js
- Ensure columns are reordered as per order
-  cypress\integration\project\grid\column\edit-column\join_columns.spec.js
-  Ensures two columns are joined respecting the column ordering
-  Ensures two columns are joined with given seperator with columns reorder

 Fixed flaky drag-n-drop tests for jQuery migration

---

main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.js

Due to a change in behavior in jQuery $.post(), calls to /command/core/toggle-starred-expression would fail if "json" is expected, but an empty response is returned.  By omitting the expected content type (""), then the content-type is set by the server response, so then it works.
Ref: https://github.com/jquery/jquery/issues/3973
Ref: https://bugs.jquery.com/ticket/5156

jQuery 3.x Migration - Fixed Test the history, star Test

---

main/src/com/google/refine/exporters/OdsExporter.java
main/tests/server/src/com/google/refine/exporters/OdsExporterTests.java

Fixes #4738
- remove the default rows when create [newTable](https://odftoolkit.org/api/odfdom/org/odftoolkit/odfdom/doc/table/OdfTable.html#newTable(org.odftoolkit.odfdom.doc.OdfDocument))
- default row is 2 rows, to prevent avoid the api changes(change the default rows and etc.), use an parameter to store the default rows number
- Add testcase of OdsExporter
- Pass format check with `mvn formatter:format`

(I#4738) Making the exported file consistent with the original data

---

GOVERNANCE.md

- Add Jan Ainali as new member of the Advisory Committee
- Add a section on Project Director
- A few minor cosmetic / spelling updates
By the way, I have the impression other parts of this document are a bit outdated (e.g. the part on Committers). Could use another pair of eyes re: this aspect.
Would also be good to integrate this document somewhere in OpenRefine's website (if we decide to upgrade it).

Update GOVERNANCE.md: changes to Advisory Committee, Project Director

---

refine.bat

Fixes #4868
- add « @ echo off » command at the start of the file.
Goes from:
To:
Regards, Antoine

Add echo off to windows batch script

---

docs/README.md
docs/docusaurus.config.js

Replacing copyright (c) line in footer with sentence indicating docs fall under a CC-BY 4.0 license.
Fixes #4876
- Small update to docusaurus.config.js

CC license rather than (c) for OpenRefine's documentation

---

main/webapp/modules/core/scripts/views/data-table/sorting-criterion-dialog.html

- Fixed jitter found in column -> sort dialog, as shown here:
Before:
After:

Fixed jitter in column -> sort dialog

---

main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java

Fixes #4918.
- restrict the protocols that can be used at project creation to fetch the contents of a URL

Restrict protocols available at project creation

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js

We recently changed (in #3731) the way the identifiers of entities are inserted into the URLs to view them, in the context of the reconciliation service. This breaks compatibility with some important reconciliation services such as OpenCorporates'.
It was instead suggested in https://github.com/reconciliation-api/specs/issues/39 that we leave it up to the services whether (and how) the ids are escaped when inserted in the URL.
Temporarily fixes #4645, for the sake of getting a release (3.6) out of the door soon. I intend to go back to this.

Revert back to previous behaviour for insertion of ids in URL templates for reconciliation

---

main/tests/cypress/cypress.json
main/webapp/modules/core/scripts/util/dialog.js

I noticed, especially on a high resolution 4k monitor, that the positioning of the Rename Column dialog was different now from OR 3.5.2.
In OR 3.5.2, window.prompt() is used and on Brave/Chrome, the prompt dialog appears right at the top, even overlapping the browser URL bar.
In OR 3.6.0, I changed it to a jquery-ui dialog to match the UX of the rest of the webapp.  This looks better, but the positioning is changed. See the screenshots below:
I looked into the positioning code in dialog.js, and found that the code is centering the dialog's midline on the window's midline.
Current UX guidelines suggest modal dialogs should be positioned higher in the window.  The current behavior looks especially bad for small dialogs on high resolution 4k monitors. (See screenshot below).
I noticed …

Updated the dialog positioning to be higher up

---

main/webapp/package.json

- Upgrade jQuery and jQuery Migrate.
The jQuery migration from 1.12.4 to the latest (3.6.0) version required many fixes due to deprecated and removed methods, and also some behavior changes.
Luckily, all the work was able to be done incrementally since all of the fixes were compatible with the old version (1.12.4).
All of the Cypress tests are passing, and I have done some additional manual testing.
Summary of Changes:
* Replaced usages of jQuery functions removed in 3.6.0 or earlier. (Ref: https://api.jquery.com/category/removed/).
* Replaced usages of jQuery functions deprecated in 3.6.0 or earlier. (Ref:  https://api.jquery.com/category/deprecated/).
* Fix broken code due to jQuery no longer auto-inserting tbody tags.
* Correct <textarea/> to …

Upgrading jQuery to 3.6.0

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js

Fixes #4847 
- Improved error message for invalid manifest version
- Tested for the cases of no version, invalid version (such as letters), 1.x, 2.x, >= 3.0, < 1.0.
Before:
After:

Improved error message for invalid manifest version

---

docs/docs/index.md
docs/docs/manual/installing.md
docs/versioned_docs/version-3.5/index.md
docs/versioned_docs/version-3.5/manual/installing.md

Those mentions are getting out of date as we publish new versions.
I also removed the entire "What's new" section because the docs is not
an appropriate place for our changelogs, and the contents of the section
were redundant with the other download links listed before.

Remove references to specific versions of OpenRefine in the docs.

---

refine
refine.bat

Fixes #4930 
Changes for refine.bat:
-  Only use java found in %JAVA_HOME% to check the version and run.  
-  Exit if Java Release < 11 
-  Warn if Java Release > 17
Changes for refine:
- Exit if Java Release < 11
Running with Java 8:
```
>refine.bat run
Using refine.ini for configuration
Java 8 (1.8.0_332)
OpenRefine requires Java version 11 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version.
```
Running with Java 17:
```
>refine.bat run
Using refine.ini for configuration
Java 17 (17.0.2)
Getting Free Ram...
23:47:36.994 [            refine_server] Starting Server bound to '[127.0.0.1:3333](http://127.0.0.1:3333/)' (0ms)
```

Updated refine.bat to use %JAVA_HOME% and be consistent with the refine script

---

main/tests/cypress/build-test-matrix.js

The reconciliation tests were not included in the CI test run.
I added them to the test group that ran the quickest (3m).
- Added reconciliation tests to the CI test run.

Added grid/column/reconcile Cypress tests to the CI build matrix

---

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/collapse-consecutive-whitespace.spec.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js

fixes #4883
- replaced `value.replace(/\\s+/,' ')` for `value.replace(/[\\p{Zs}\\s]+/,' ')` 
- 
-

Added whitespaces to the "collapse consecutive whitespaces" command

---

main/tests/cypress/cypress/integration/project/grid/viewpanel-header/sort.spec.js
main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html
main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js

- Cleaned up the spacing between the Select and Deselect buttons in multiple file select panel.
Before:
After:

Cleaned up the spacing between the Select and Deselect buttons in multiple file select panel

---

docs/versioned_docs/version-3.5/manual/installing.md

Having found out [the hard way](https://github.com/AtesComp/rdf-transform/issues/6#issuecomment-1127394943) that Oracle's JRE is some 10 versions behind the JDK, I suggest a phrase in the installation introduction to point that out. In my case, RDF Transform needed the higher version.
- 
- 
-

Java versioning

---

main/webapp/modules/core/scripts/preferences.js

- Added spacing between buttons in preferences.
- Added Actions header.
Before:
After:

Added spacing between buttons in preferences and added Actions header

---

docs/docs/technical-reference/version-release-process.md

The release process is now simpler, as most of it is scripted within a GitHub action. This updates the documentation to reflect that.

Update release process in technical docs

---

main/src/com/google/refine/commands/importing/GetImportingConfigurationCommand.java
main/webapp/modules/core/scripts/index/create-project-ui.js

This makes the `get-importing-configuration` command accessible through GET requests rather than through `POST` requests as it does not change state.
Notes:
The `POST` option could maybe be safely removed considering that migration should be straightforward for potential API clients.

API: make the get-importing-configuration command available over GET

---

extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/module/scripts/dialogs/wikibase-dialog.html
extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js

Fixes #5007
- Added 'Discover Wikibase instances…' button to the 'Select Wikibase instance' dialog that opens https://github.com/OpenRefine/wikibase-manifests.
After:

Added 'Discover Wikibase instances…' button to the 'Select Wikibase instance' dialog.

---

main/webapp/modules/core/styles/index/open-project-ui.less
main/webapp/modules/core/styles/jquery-ui-overrides.less
main/webapp/modules/core/styles/project/facets.less
main/webapp/modules/core/styles/project/process.less
main/webapp/modules/core/styles/project/sidebar.less
main/webapp/modules/core/styles/pure.css
main/webapp/modules/core/styles/theme.less
main/webapp/modules/core/styles/views/data-table-view.less

Drop various legacy CSS features/prefixes.
These changes should only affect browsers older than:
- IE 10
- Safari 13
- Firefox 50
- Chrome 56

drop legacy CSS

---

.github/dependabot.yml

- Added ignore to Dependabot for the Cypress dependency since we do not want to upgrade until Cypress adds back 'Run all tests,' and based on the comments of the maintainer, 'Run all tests' will not be back for another 6 months to a year.

Added ignore to Dependabot for Cypress dependency

---

extensions/wikidata/module/scripts/dialogs/wikibase-dialog.html
extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
main/webapp/modules/core/scripts/reconciliation/recon-dialog.html

So that the security and accessibility features of the browser work as intended.

Semantics: change two buttons to links

---

extensions/wikidata/module/styles/schema-alignment.less

Closes #5089.
Fixes bug introduced by #5028.
- restore the size of the grid used to render mediainfo previews

Fix preview of MediaInfo entities

---

.github/dependabot.yml

- Updated Dependabot to ignore Jetty versions 10 and above.

Updated Dependabot to ignore Jetty versions 10 and above

---

main/webapp/modules/core/styles/common.less

- Made text color in tables consistent with the color used in the project table to improve readability of the table data (Going from gray to almost black).
After (Open Project) :
After (About/Project Metadata) :

Made text color in tables consistent with the color used in the project table

---

extensions/gdata/module/scripts/index/gdata-source-ui.js
main/webapp/modules/core/scripts/util/misc.js

Fixes #5107
- Added fix for gdata importer login to get the date properly so the documents show up on login (Last screenshot).
- Fixed i18n typo.
- Added a try catch block around the code that processes each document. If any document causes an exception, an error is displayed in the console, but the other documents are displayed:

Added fix so the gdata importer gets the date properly

---

pom.xml

- Update Jetty from 9.4.46.v20220331 to 9.4.48.v20220622.

build(deps): bump jetty.version from 9.4.46.v20220331 to 9.4.48.v20220622

---

docs/docs/technical-reference/contributing.md
docs/versioned_docs/version-3.6/technical-reference/contributing.md

- fixes #5120
- is the local doc web server at http://localhost:3000? Got that from https://docusaurus.io/docs/installation#running-the-development-server

[doc] docusaurus installation

---

extensions/wikidata/module/styles/dialogs/wikibase-dialog.less

In 8e4dce1ac7df5adf561ea8f912db86e299817ee1 (#5049), we introduced a CSS rule which affects all `span` elements in the entire application, whereas it was meant to only apply to the ones contained in the dialog to manage Wikibase instances.
Before this fix:
With this fix:

Fix CSS issue in Wikibase extension, affecting the entire application

---

extensions/database/module/scripts/index/database-import-controller.js
extensions/database/module/scripts/project/database-exporters.js
extensions/gdata/module/scripts/index/importing-controller.js
extensions/gdata/module/scripts/project/exporters.js
extensions/pc-axis/module/scripts/pc-axis-parser-ui.js
extensions/phonetic/module/scripts/load-language.js
extensions/wikidata/module/scripts/menu-bar-extension.js
main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/about.html
main/webapp/modules/core/scripts/index.js
main/webapp/modules/core/scripts/preferences.js
main/webapp/modules/core/scripts/project.js
main/webapp/modules/core/scripts/util/i18n.js

- Move duplicate code to initialize the i18n system to i18n.js so it can be used by the index.vt, preferences.vt, and project.vt templates.  
- Removed duplicate code in extensions.
- Updated controller.js to include i18n.js in the script bundles for each template.
- Added check to compare the browser's language to the one returned by the load-language command, and print a warning if they are different.  Requested in Issue #5118.

Cleaned up duplicate i18n code

---

main/webapp/modules/core/scripts/dialogs/clustering-dialog.html

- Changed 'Find out more...' link to point directly to the documentation rather than GitHub in the cluster and edit dialog.

 Changed link in the cluster and edit dialog to point directly to the documentation

---

main/webapp/modules/core/langs/translation-en.json

In #5138 the error message that is shown does not quite match the UI:
The message mentions the "Edit?" column but it is actually called "Merge?".
This fixes that (but not #5138).

Adjust wording of error message mentioned in #5138

---

docs/docs/technical-reference/openrefine-api.md

- a bit related to #5123 (set-project-metadata can be used to rename a project)
Questions:
- all params go in post data? That's what I see in Chrome dev console:
- is `set-project-tags.old` required? That's what I see in console, so I surmised the following description. The alternative would be that only `new` is used to set all tags
'old': tags to remove (comma-separated list)
'new': tags to add (comma-separated list)
- I hope that cross-doc links like ` [Project management](../manual/starting#project-management)` work

[doc] set-project-metadata, set-project-tags

---

docs/docs/manual/wikibase/configuration.md
extensions/wikidata/module/scripts/schema-alignment.js
extensions/wikidata/module/scripts/wikibase-manager.js
extensions/wikidata/module/scripts/wikibase-manifest-schema-v2.js
extensions/wikidata/pom.xml
extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
extensions/wikidata/src/org/openrefine/wikidata/manifests/Manifest.java
extensions/wikidata/src/org/openrefine/wikidata/manifests/ManifestV1.java
extensions/wikidata/src/org/openrefine/wikidata/manifests/ManifestV2.java
extensions/wikidata/src/org/openrefine/wikidata/updates/EntityEdit.java
extensions/wikidata/src/org/openrefine/wikidata/updates/FullMediaInfoUpdate.java
extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java
extensions/wikidata/tests/src/org/openrefine/wikidata/manifests/ManifestTest.java
extensions/wikidata/tests/src/org/openrefine/wikidata/updates/MediaInfoEditTest.java

Fixes #5039.
- Rework the backend to avoid trying to fetch MediaInfo entities when we are not uploading any structured data. This enables working with the existing Wikibase integration with "virtual" MediaInfo entities, even when the target Wikibase instance does not actually have Wikibase entities of that type, but only plain old MediaWiki files. This is shoehorning a new sort of file upload feature in the Wikibase extension (#5039), even if it does not have anything to do with Wikibase in the end.
- Add a field to the manifest to disable the structured data fields on media files (captions and statements). When this flag is set in the Wikibase manifest, we simply offer the file name, file path and wikitext fields in the schema editor, and nothing …

Support for file upload to Wikibase instances without structured data support

---

main/resources/com/google/refine/messages/OpenRefineMessage.properties
main/src/com/google/refine/importers/ImporterUtilities.java
main/src/com/google/refine/operations/recon/ReconOperation.java

Fixes #2443 
- transferred the default column name prefix used for headers of separator based files to properties for localisation.
- transferred the facet names (judge and score) to properties for localisation 
- removed the conflicting *_en.properties files for FunctionDescription

2443 back end localization final

---

main/webapp/modules/core/scripts/dialogs/clustering-dialog.html
main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
main/webapp/modules/core/styles/dialogs/clustering-dialog.less

Fixes #5210, #1141, #938
- Adjusted control part of the cluster and edit dialog.
- Adjusted the width and spacing of elements in the dialog body. 
After:

Cluster and edit display fix

---

extensions/wikidata/module/MOD-INF/controller.js
extensions/wikidata/module/langs/translation-en.json
extensions/wikidata/module/scripts/dialogs/save-new-template-dialog.html
extensions/wikidata/module/scripts/dialogs/save-new-template-dialog.js
extensions/wikidata/module/scripts/schema-alignment-tab.html
extensions/wikidata/module/scripts/schema-alignment.js
extensions/wikidata/module/scripts/template-manager.js
extensions/wikidata/module/scripts/wikibase-manager.js
extensions/wikidata/module/scripts/wikibase-manifest-schema-v2.js
extensions/wikidata/module/styles/schema-alignment.less

Closes #5043.
This adds the ability to start a schema from a previously saved schema template.
A schema template is a schema with some missing values.
It is also possible to pre-define some templates in the Wikibase manifest, so that those are added to OpenRefine when the manifest is first loaded.
I think it would be useful to add an interface to list existing schema templates, which would enable:
* deleting schema templates
* exporting a schema template to JSON (useful to add it to the manifest afterwards)

Initial support for schema templates.

---

main/src/com/google/refine/importing/ImportingJob.java

Fixes #5218
- Adjusted memory usage display to show the memory used instead of memory total.
- Adjusted display to use base 2 instead of base 10 for the conversion to show the correct amount of memory.
After:

Adjusted memory usage display to show the memory in use

---

pom.xml

This update requires migrating to log4j-slf4j18-impl, which has not been updated yet to satisfy the 2.0 SPI.
This closes #5225.
This reverts commit 0ebfccd4f87acc5c8118a5fc228d83034cfc5644.

Revert "build(deps): bump slf4j-api from 1.7.36 to 2.0.0 (#5206)"

---

docs/docs/manual/installing.md
docs/docs/manual/running.md
docs/versioned_docs/version-3.4/manual/installing.md
docs/versioned_docs/version-3.4/manual/running.md
docs/versioned_docs/version-3.5/manual/installing.md
docs/versioned_docs/version-3.5/manual/running.md
docs/versioned_docs/version-3.6/manual/installing.md
docs/versioned_docs/version-3.6/manual/running.md

- Hyperlink browser list to their homepages
- Add Safari as support WebKit browser
- Correct WebKit capitalisation ;-)
---
I hope it's correct to update all `*/versioned_docs/version-*/` files as well.

Make browser list more useful

---

docs/docs/manual/wikibase/overview.md
docs/versioned_docs/version-3.6/manual/wikibase/overview.md

In Wikibase schemata we do not let people edit sitelinks yet, this fixes the docs about that.

Improve documentation about absence of support for editing sitelinks

---

docs/docs/manual/wikibase/configuration.md

Some expansion of the documentation to help Wikibase administrators take advantage of the new support for file upload.
@lozanaross @paulduchesne @trnstlntk let me know if anything is unclear, and feel free to make direct edits to this PR as well.

Expand documentation for Wikibases with file upload

---

extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
main/tests/cypress/cypress/integration/extensions/wikidata/layout.spec.js
main/tests/cypress/cypress/integration/extensions/wikidata/select_wikibase_instance.spec.js
main/tests/cypress/cypress/integration/extensions/wikidata/wikibase_account.spec.js
main/tests/cypress/cypress/support/ext_wikidata.js
main/tests/cypress/cypress/support/index.js

Partial fix for #3430
This PR is adapted from @fgiroud PR #3624
- Added basic tests for the Wikibase extension that are possible without credentials:
- Check extension is loaded
- Check login dialog
- Select Wikibase instance
- Add/Delete Wikibase manifests by URL and JSON

Wikidata extension tests

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
main/webapp/modules/core/styles/reconciliation/recon-dialog.less

We plan to redesign this dialog completely - there are a lot of issues with it. This is just a fairly minimal fix to avoid its contents overflowing and hiding the "Reconcile" and "Cancel" buttons.
Closes #5285.
- make sure the lower part of the form can expand to the full width of the dialog by uncoupling it with the separation between the two upper parts
- remove the (fairly arbitrary) `height: 500px` set on the dialog so that it can expand further down to fit its contents
New version:

Fix reconciliation dialog overflow issue.

---

extensions/wikidata/module/scripts/wikibase-manifest-schema-v1.js
extensions/wikidata/module/scripts/wikibase-manifest-schema-v2.js

Fixes #5035.
This simply drops the `"format": "url"` parts of the schema because AJV refuses localhost URLs for those fields. All of those URL fields can legitimately point to localhost, in particular in development environments.
Furthermore some fields do not actually hold URLs but URL templates, so the `"format": "url"` was wrong for those in the first place.
It would be more satisfying to keep some sort of validation here, but supplying a regex would bloat the manifest. Fixing the issue in AJV could also be an option, but that requires more work and it should not stand in the way of this (since this is actively preventing people from working with this).

Remove 'url' format in Wikibase manifest JSON schema

---

main/webapp/modules/core/scripts/facets/range-facet.js
main/webapp/modules/core/scripts/facets/timerange-facet.js

Fixes #3319
Adjusted the numeric and timeline facet histogram bin colors to improve the contrast so that it is 3 to 1 between the three colors: background (white), bin color 1, and bin color 2.
Previously, timeline facet was using a separate color palette. This change makes numeric and timeline use the same colors. See the pictures below to see the difference.
Before and After:
Contrast:

Adjusted the colors in range and timerange facet to have more contrast

---

extensions/wikidata/module/scripts/wikibase-manager.js

Small improvement, to make sure that the schema templates are not lost if OpenRefine is closed immediately after adding a new Wikibase instance with templates in its manifest.

Save schema templates when adding a wikibase.

---

main/src/com/google/refine/commands/Command.java

When errors happen in the API it can be rather opaque to the end user as the error is only printed in the resulting JSON response. This change ensures that the stacktrace is also natively printed.

Make respondException print the exception stacktrace

---

extensions/wikidata/module/styles/dialogs/wikibase-dialog.less

Preserve aspect ratio of Wikibase logos

---

docs/package.json
docs/yarn.lock

- Upgraded Docusaurus to 2.1.0 by upgrading both @docusaurus/core and @docusaurus/preset-classics to 2.1.0 since that version requires the packages to be in sync.

Upgraded Docusaurus to 2.1.0

---

main/tests/server/src/com/google/refine/expr/functions/ToStringTests.java

Closes #5277
This changes an assert that was failing when the environment locale was set to French.
I considered forcing the locale to be en_US when tests are run but rejected this because in my opinion, tests that require a specific locale to pass are brittle and should ideally be avoided. The actual fix dynamically sets the expected value based on the locale the test is being run in, which is a more resilient solution.
While working on this issue, an inconsistency in the toString method was identified. Ideally, when the function is called on a number, it should always return a string that takes the locale into consideration. However, there is an edge case where this does not happen. The following assert is included in the `testToString` test and succeeds with a French locale when it …

Fix failing test assert when locale is set to French.

---

main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.html
main/webapp/modules/core/scripts/project/history-apply-dialog.html
main/webapp/modules/core/scripts/project/history-extract-dialog.html
main/webapp/modules/core/styles/project/sidebar.less
main/webapp/modules/core/styles/views/data-table-view.less

- Allowed the cell edit popup and the templating, export and apply history dialogs to be resizable when changing the size of the textbox inputs.
Edit cell before:
Edit cell after:

Allowed the cell edit popup and dialogs with textbox inputs to be resizable

---

extensions/database/pom.xml
extensions/gdata/pom.xml
extensions/jython/pom.xml
extensions/phonetic/pom.xml
extensions/wikidata/pom.xml
main/pom.xml

Fixes #5338
Adds necessary logging dependencies to the test scope so that logging works for unit tests.

Add logging dependencies for test scope. Fixes #5338

---

main/tests/cypress/cypress/integration/project/grid/column/facet/facets.spec.js
main/tests/cypress/cypress/integration/project/undo_redo/undo_redo.spec.js
main/tests/cypress/cypress/integration/tutorial/layout-of-openrefine.spec.js
main/tests/cypress/cypress/support/commands.js

This PR fixes two flaky tests which were due to this error:
`Timed out retrying after 4000ms: Expected to find element: body[ajax_in_progress="true"], but never found it.`
Following tests show this same error:
* Test include/exclude filters (facets.spec.js)
* Delete 3 columns, then successively undo and redo the modifications using the Undo/Redo panel (undo_redo.spec.js)
The tests are flaky because they are waiting for the loading indicator to appear, and then disappear. However, if the background task finishes quickly enough, the indicator appears and disappears, or just never appears, and the test is stuck waiting for the loading indicator to appear, resulting in a timeout and test failure.
```
cy.get('body[ajax_in_progress="true"]');  // <= may get stuck here …
```

Fixed flaky Cypress tests and cleaned up the logic on the include/exclude filters tests in facets.spec

---

extensions/wikidata/module/scripts/wikibase-suggest.js

Closes #5190.
This bug was happening because we were storing the results of Wikibase requests incorrectly in the cache. They needed to be translated to a common format supported by the library.

Fix caching of Wikibase suggest results

---

refine

Fixes #5240
This PR fixes a problem where the absence of the `which` command on users' computers was causing `refine.sh` to give a misleading error message.
After reading around the issue, various approaches were considered:
1. Just update the error message to make it clear that `which` might be one of the commands that's missing
2. Do an individual check against the `which` command with its own error message before the command is used. This would use `command -v`
3. Rework the script to not use `which` at all, replacing it with `command -v`. There seems to be quite a strong sentiment that it's not ideal to use, eg https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then, and replacing it should reduce instances where users are missing a command to run the script. …

Replace use of 'which' with 'command -v'

---

docs/versioned_docs/version-3.6/manual/running.md

fixes #5137
@trnstlntk Does the Netlify preview look OK and show a similar Caution banner text for the Windows tab under "Starting and exiting" as it does for the Linux tab?
I also expanded and mentioned we have a Windows Kit with embedded Java that folks can download and skip worrying about Java setup.

Add Caution about JAVA_HOME error to Windows tab

---

main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/util/misc.js
main/webapp/modules/core/scripts/views/data-table/cell-ui.js
main/webapp/modules/core/styles/views/data-table-view.less

Fixes #5349
Increased the initial height for the cell and text facet editor when the content has more rows. Minimum initial height is 3 rows; maximum initial height is 15 rows (5x more than before). Scrollbars are displayed if the content has more than 15 rows.
The user can still manually make the textarea even taller if they want.  See recording for examples.

Made the textarea for the edit cell/text facet editors larger

---

main/pom.xml

Fixes #5353
Exclude a large generated module from instrumentation so that we don't get an error on it.

Exclude generated code tables from JaCoCo - fixes #5353

---

main/src/com/google/refine/ProjectMetadata.java
main/src/com/google/refine/clustering/binning/FingerprintKeyer.java
main/src/com/google/refine/commands/project/SetProjectTagsCommand.java
main/src/com/google/refine/commands/recon/GuessTypesOfColumnCommand.java
main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/expr/functions/strings/Range.java
main/src/com/google/refine/importers/FixedWidthImporter.java
main/src/com/google/refine/importers/ImporterUtilities.java
main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/src/com/google/refine/importers/TabularImportingParserBase.java
main/src/com/google/refine/importers/TextFormatGuesser.java
main/src/com/google/refine/importers/WikitextImporter.java
main/src/com/google/refine/importers/tree/XmlImportUtilities.java
main/src/com/google/refine/model/Row.java

Fixes #5105 
- All uses of the std lib String trim have been migrated to Guava's implementation of trim
I have also tested the csv file from #5246 to verify that the NBSP's are catered for.

Migrate std lib trim to guava trim

---

main/tests/cypress/cypress/integration/project/project-header/export_project.spec.js

- Fixed flaky export project tests failing with error:
`Timed out retrying after 4000ms: cy.readFile("cypress/downloads/1659083769462.xlsx") failed because the file does not exist at the following path:
`
The old code would return as soon as file was created, but possibly before file contents were flushed to disk, so sometimes the file would be empty (filesize: 0).
Solution:
Use Cypress's file download recipe to check that the downloaded files have contents. (Ref: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/e2e/utils.js)

Fixed flaky export project tests to properly verify downloads

---

main/tests/cypress/cypress/integration/project/grid/column/facet/facets.numeric.spec.js

- Fixes the 'Test for checkboxes and reset button' Cypress test,  which was using cy.waitForOperation() which is a problem on faster machines.
When the test fails, the following error is visible:
```
Timed out retrying after 4000ms: Expected to find element: body[ajax_in_progress="true"], but never found it.
```
See the previous PR https://github.com/OpenRefine/OpenRefine/pull/5342 for further explanation.

Fixed flaky test in facets.numeric.spec.js

---

main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js
main/tests/cypress/cypress/support/commands.js

- Updated the `typeExpression` Cypress command to be able to work without `cy.wait(500)`.

Added a fix to remove the cy.wait(500) on the cy.typeExpression() command

---

main/tests/cypress/cypress.json

Running the entire test suite locally takes 451 seconds with the default 10ms keystroke delay, and 426 seconds with 0ms delay.
- Changed `keystrokeDelay` to 0ms to make Cypress tests with `.type` run faster.
Before (10 ms):
After (0ms):

Changed keystrokeDelay to 0ms to make Cypress tests with cy.type run faster

---

main/tests/cypress/cypress/integration/project/grid/column/facet/facets.spec.js
main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js

- Optimized the Cypress tests with the selectors that matched the highest amount of unnecessary elements to match fewer elements or just the needed one, so that viewing snapshots for those areas of the following tests requires less time and memory:
- facets.spec:
- Test the mass edit from a Facet (~190 elements)
- Test the Remove all button (~1.2k elements)
- Test include/exclude, invert (~199 x 3 elements)
- Test facet reset (~199 x 3 elements)
- expressions.spec:
- Test the reuse of expressions from the history (~500 elements)

Optimized Cypress tests that have selectors matching a large amount of elements

---

docs/docs/manual/wikibase/configuration.md
docs/versioned_docs/version-3.5/manual/wikibase/configuration.md
docs/versioned_docs/version-3.6/manual/wikibase/configuration.md

I have long stopped maintaining the Wikibase reconciliation service for items, which was previously developed at https://github.com/wetneb/openrefine-wikibase.
Luckily, an active fork is available at https://gitlab.com/nfdi4culture/ta1-data-enrichment/openrefine-wikibase
This updates the docs to point prospective users to that instead.

Update repository URL for Wikibase reconciliation service

---

extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/MediaFileUtilsTest.java

Closes #5420.
The error handling for this API action was basically non-existent - guess who was to blame? Oops, sorry about that…

Improve error handling for upload of media files.

---

.github/workflows/codeql.yml

CodeQL adds code scanning for critical security issues. The results will be shown for project owners on
https://github.com/OpenRefine/OpenRefine/security.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Create new GitHub action for CodeQL

---

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/collapse-consecutive-whitespace.spec.js

Having invisible characters in source code is evil. This PR replaces them with their equivalent escapes and also expands the range of characters tested to include both Java whitespace (e.g. HT, FF, VT) and Unicode whitespace.

Replace hidden characters with escape codes. Refs #4883

---

extensions/wikibase/module/langs/translation-en.json
extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
extensions/wikibase/src/org/openrefine/wikibase/schema/WbMediaInfoEditExpr.java
extensions/wikibase/tests/src/org/openrefine/wikibase/schema/WbMediaInfoEditExprTest.java

This should let the user identify cases such as additional `File:` prefixes too, which was the problem encountered in #5430. Closes #5433.

Add explicit Wikibase QA warning when file names are normalized.

---

main/src/com/google/refine/importers/ExcelImporter.java
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js

Fixes #4838
Adds an option (default=False) to import all cell values using a textual rendering, rather than the value that is stored in Excel. 
This can be useful for datatypes which aren't supported by OpenRefine such as times, dates, intervals or where the datatype information is only available in the format string (e.g. integers).

Add option to import Excel as text only. Closes #4838

---

main/tests/cypress/cypress/integration/project/grid/viewpanel-header/rows_records.spec.js

- Fixed flaky test in rows_records.spec.js that had an `ajax_in_progress="true"` check.

Fixed flaky test in rows_records.spec.js that had an ajax_in_progress="true" check

---

main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java

Fixes #5464
- Use our default locale DecimalFormatter instead of a hardcoded string for the expected value
- ~~Also left in the commented out "big hammer" version which just pins the default locale to US. I don't have a strong opinion as to which is better.~~
-

Make Excel import tests locale independent. Fixes #5464

---

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/join_columns.cy.js

-  Fixes a flaky Cypress test in join_columns.spec that used `ajax_in_progress="true"`

Cleaned up flaky test that used ajax_in_progress="true" in join_columns.cy

---

.github/workflows/pull_request.yml
.github/workflows/snapshot_release.yml
main/tests/cypress/package.json
main/tests/cypress/yarn.lock

- Upgrades fs-extra from 10.1.0 to 11.1.0.
- Upgrades Node from 12 to 14 in snapshot_release.yml and pull_request.yml to upgrade fs-extra.

Bump fs-extra from 10.1.0 to 11.1.0

---

main/src/com/google/refine/expr/functions/ToDate.java
main/src/com/google/refine/importers/ExcelImporter.java
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java

Fixes #5390. Fixes #5389
- Import numbers as integers where possible/required. This includes "General" format numbers with a zero fractional part as well numbers which are explicitly formatted as integers, perhaps masking a fractional part.
- Import unsupported date formats as strings, including dates (w/o times), times, intervals
- Import problematic non-date number formats as strings, including leading zeros, embedded punctuation or anything other than grouping separator, decimal separator, percentage sign, padding (leading/trailing space & trailing zero)
The regex used to identify the number formats that OpenRefine can import cleanly will probably need some tuning. There's also the issue that Apache POI's text rendering isn't feature complete or …

Import unsupported datatypes as strings

---

main/src/com/google/refine/exporters/OdsExporter.java
main/src/com/google/refine/importers/OdsImporter.java

Fixes #5485
- Remove suppression of deprecation warnings now that historical ODS API has been undeprecated
- Protect against some (theoretical) NPEs. Although very unlikely this silences some warnings.
- A couple of minor simplifications (all straightforward to validate by inspection)

Reenable ODF Toolkit deprecation warnings

---

main/src/com/google/refine/expr/functions/TimeSinceUnixEpochToDate.java
main/tests/server/src/com/google/refine/expr/functions/TimeSinceUnixEpochToDateTest.java

Fixes #5488 
- Preserve full precision for millisecond and microsecond. Enhance tests to cover these cases.

Fix milli/microsecond cases. Improve tests to cover. Fixes #5488

---

.github/workflows/snapshot_release.yml

Fixes #5492.
This is not tested in real conditions. I expect it is likely it does not work out of the box: if the workflow fails, it should be after upload to Maven Central, and so it should be possible to upload the artifacts manually to the GitHub release and attempt a fix of the workflow to be tested at the next release.

Upload packaged artifacts to GitHub for new releases

---

main/src/com/google/refine/expr/functions/xml/SelectXml.java

This change reflects the issue listed under #5394. getParams() has been changed such that the element and string positions are swapped.
Fixes #5394
- getParams() has been changed such that the element and string positions are swapped.

issue#5394 -- Updated SelectXML.Java

---

.github/workflows/snapshot_release.yml
packaging/dmg_settings.py
packaging/pom.xml

Fixes #5205
- Use [dmgbuild](https://github.com/dmgbuild/dmgbuild) to create macOS dmg file with a shortcut to `/Applications` and a simple arrow background (can be changed to something else if you design a better background image).

Add `/Applications` shortcut to macOS dmg file

---

main/src/com/google/refine/ProjectManager.java
main/src/com/google/refine/ProjectMetadata.java
main/src/com/google/refine/io/ProjectMetadataUtilities.java
main/src/com/google/refine/model/Cell.java
main/src/com/google/refine/model/Project.java
main/src/com/google/refine/util/ParsingUtilities.java
main/src/com/google/refine/util/SerializationFilters.java
main/tests/server/src/com/google/refine/ProjectManagerTests.java

Fixes #3047
- Switch from LocalDateTime with ad hoc UTC conversion hand coded on top to java.time.Instant which is natively UTC
- Fix test that was broken in 2017 when the previous set of changes were made
NOTE: This changes the datatypes of parameters/returns in an API which is declared as public, but really shouldn't be used externally (and no one apparently noticed/complained when they were changed from java.util.Date before). We could restore compatibility with the pre-2017 API, but I don't really see the point.
Untangling the user data type will be in a separate PR since it's not at all coupled with this.

Untangled project timestamp management. Fixes #3047

---

extensions/database/pom.xml

There are 1 security vulnerabilities found in org.postgresql:postgresql 42.5.0
- [CVE-2022-41946](https://www.oscs1024.com/hd/CVE-2022-41946)
Upgrade org.postgresql:postgresql from 42.5.0 to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.postgresql:postgresql to 

---

main/webapp/modules/core/styles/index.css
main/webapp/modules/core/styles/project/sidebar.css
main/webapp/modules/core/styles/theme.css

- Fixes a regression introduced by #5525, where the slogan text and the browsing panel help text (using facets/filters window) both look lighter.
- Added the CSS variable `text-quarternary` that replaces the LESS variable `@near_black` and its usages.
Slogan before:
Slogan after:
Browsing panel before:
Browsing panel after:

CSS Migration Fix

---

main/tests/cypress/cypress/integration/project/grid/column/reconcile/actions/clear_reconciliation_data.spec.js
main/webapp/modules/core/scripts/project.js
main/webapp/modules/core/scripts/project/browsing-engine.js
main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
main/webapp/modules/core/scripts/views/data-table/column-header.html
main/webapp/modules/core/scripts/views/data-table/data-table-view.js

Fixes #4350.
This renders recon stats in column headers, restoring the existing behaviour. The difference is that those recon statistics are not stored statically in column metadata anymore, but are computed dynamically like facet statistics. For efficiency reasons, this is done at the same time (in the same HTTP request) as facet statistics, so that the same pass on the dataset can be used to gather the statistics.
It would be relatively straightforward to extend this to display more than reconciliation statistics, such as datatypes, but I am leaving this as is for now because this requires a larger design effort.
I am anticipating that some Cypress tests might not work as expected, so marking this as draft.

Restore recon stats rendering in 4.0

---

main/src/main/java/org/openrefine/commands/history/ApplyOperationsCommand.java
main/src/test/java/org/openrefine/commands/history/ApplyOperationsCommandTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/project/history-panel.js
refine-model/src/main/java/org/openrefine/util/ParsingUtilities.java
refine-workflow/src/test/java/org/openrefine/importers/TsvCsvImporterTests.java

This is a first step towards #5539 and #5540 (but does not close either of them).
When an operation cannot be executed because its JSON representation is invalid or it does not apply to the given project, the corresponding error is reported to the user and the following operations are not executed.
Before this PR, errors were reported in the server logs and all operations were attempted even if a previous one failed (see #5540).
This is not meant to be a final UX, I plan to do many other improvements of this dialog. This first behaviour is just to make sure we can reuse the logic behind the dialog to apply operations everywhere else in the tool, for #5539.

Improve error handling in Apply operations dialog

---

main/webapp/modules/core/about.html
main/webapp/modules/core/about.js
main/webapp/modules/core/error.vt
main/webapp/modules/core/index.vt
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/preferences.vt
main/webapp/modules/core/project.vt
main/webapp/modules/core/scripts/preferences.js
main/webapp/modules/core/scripts/project.js
main/webapp/modules/core/styles/common.css
main/webapp/modules/core/styles/index.css
main/webapp/modules/core/styles/project.css

So that the background and foreground text can be styled.
side effects:
- minor style changes (acceptable in my opinion)
- accessibility improvements
- dropped some absolute positioning
- fixed a bug causing the slogan to shift from the left during page load
Part of #3017

header: move "OpenRefine" header text from image

---

.github/workflows/snapshot_release.yml

Fixes #5569
- removes extra maven cache setup
- adds maven cache to java-setup
- migrates to `temurin` Java distribution

Migrate to temurin and use cache with java-setup

---

main/webapp/modules/core/styles/index.css

- Changed the alignment of the slogan text to line up with the logo text as shown below:
Before:
After:

Fixed the alignment of the slogan text to line up with the logo text

---

main/src/main/java/org/openrefine/commands/column/RemoveColumnCommand.java
main/tests/cypress/cypress/integration/project/undo_redo/extract.spec.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
refine-workflow/src/main/java/org/openrefine/operations/column/ColumnRemovalOperation.java
refine-workflow/src/test/java/org/openrefine/operations/column/ColumnRemovalOperationTests.java

Closes #4055.
This generalizes the `row-removal` operation to support removing multiple columns at once, and uses this operation to remove the joined columns in the `Edit column -> Join columns` operation (when the user selected this option in the dialog).
This way, the JSON representation of the sequence of operation becomes:
```json
[
{
"op": "core/column-addition",
"engineConfig": {
"facets": [],
"mode": "row-based"
},
"baseColumnName": "NDB_No",
"expression": "join ([coalesce(cells['NDB_No'].value,''),coalesce(cells['Shrt_Desc'].value,'')],'')",
"onError": "keep-original",
"newColumnName": "joined",
"columnInsertIndex": 1,
"description": "Create column joined at index 1 based on column NDB_No using expression join ([coalesce(cells['NDB_No'].value,''),coalesce(cells['Shrt_Desc'].value,' …
```

Use column-removal operation after joining columns

---

main/tests/cypress/package.json
main/tests/cypress/yarn.lock

Bump Cypress from 12.3.0 to 12.4.0

---

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js

Closes #5581.
This stores the original clustered value as a DOM `data-` attribute, keeping it separate from the rendered value (where spaces are made non-breaking).
I intend to include this fix in 3.7-beta3.

Do not insert non-breaking space in clustered values

---

server/src/com/google/refine/Refine.java

Switch from string concatenation to string array for command line construction. I don't think this is really an issue, but hopefully it's an easy fix to quiet CodeQL

Fix CodeQL flagged vulnerability

---

main/webapp/modules/core/scripts/util/dialog.js

Makes dialogs focus-able, makes it possible
to use dialog headers as modal labels, and
automatically set focus when a dialog is displayed.

make dialogs focusable

---

main/webapp/modules/core/scripts/index.js
main/webapp/modules/core/scripts/index/open-project-ui.js

This change makes it possible to link to given panel by its identifier.
To for example go straight to the language settings one could navigate to:
`http://127.0.0.1:3333/#lang-settings`

Make it possible to link to a given home screen panel

---

main/webapp/modules/core/scripts/facets/list-facet.js

Fixes #5606
Fixes the Regression from: https://github.com/OpenRefine/OpenRefine/pull/5514
The initial height is set when a facet is added.  The facet height is not adjusted in the following cases:
- When other facet is added.
- When other facet is deleted.
- Include/Exclude Choice
- Edit Choice -> Apply
- Sort by: name count
- Refresh
- Cluster Choices -> Merge selected & Close
- Resize/Min/Max Browser Window
- Show/Hide Left Panel
- Min/Max a facet

Added a fix to keep the facet height after performing various operations

---

main/webapp/modules/core/scripts/project/browsing-engine.js
main/webapp/modules/core/styles/project/sidebar.css

Fixes #5610
- Added a fix to stop the facets panel from shifting on refresh as shown below:
After:

Added a fix to stop the facets panel from shifting on refresh

---

main/webapp/modules/core/scripts/index/open-project-ui.js

This change adds a `data` attribute to project tags with the name of that tag so that one can give individual tags custom styles:
```css
.project-tag[data-tag-name="client-y"] {
background: #0ab97e;
...
}
```
Previously you would need to do this with JavaScript to check the actual contents of the tag.

project tags: expose tag name in a data attribute

---

conf/openrefine.l4j.ini
main/src/com/google/refine/util/HttpClient.java
main/tests/server/src/com/google/refine/util/HttpClientTests.java

Fixes #5476
This pull request aims to properly handle the configuration of proxies for external services called by OpenRefine.
In particular, it allows the scenario where some services are outside (accessible through the proxy) and other are inside (not using the proxy).
3 configurations are possible:
1/ no proxy is needed: nothing has to be defined in openrefine.l4j.ini
2/ we want to use the usual properties for configuring nework in java as described in the [documentation](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html)
In this case, the property ``-Djava.net.useSystemProxies=true`` should be defined as well as ALL the others needed (the latter ones can be defined globally using the environment variable ``JAVA_TOOL_OPTIONS``). Note that, in particular, …

Handle proxy configuration, closes #5476

---

main/src/main/java/org/openrefine/commands/history/UndoRedoCommand.java
main/src/test/java/org/openrefine/commands/history/UndoRedoCommandTests.java
main/webapp/modules/core/scripts/project/history-panel.js
main/webapp/modules/core/scripts/project/process-panel.js
modules/refine-model/src/main/java/org/openrefine/history/GridPreservation.java
modules/refine-model/src/main/java/org/openrefine/history/History.java
modules/refine-model/src/test/java/org/openrefine/history/HistoryTests.java

Fixes #572.
When the sequence of operations undone or redone all preserve rows (or records, if in records mode), the pagination settings are preserved.

Preserve pagination settings when using undo/redo.

---

server/src/com/google/refine/Refine.java

Fixes #5620
- adds "bytes" to end of logger string for `JVM Max Heap:` label

Fixes #5620 adds "bytes" to end of logger string

---

.github/workflows/unassign_issues.yml

Add workflow to unassign contributors from good first issues after a delay

---

main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/create_new_item_for_each.cy.js

Fixes #5628
-  Adds a check to make sure that there is at least one reconciliation service to select.

Fix for failing Cypress CI test

---

main/tests/cypress/cypress/support/e2e.js

- Fixes flaky cancel button Cypress test that shows up in the dashboard:

Fix for the flaky cancel button Cypress test

---

GOVERNANCE.md

Update governance with 
* link to the new forum
* link to the new documentation repository
* updated status of the project director
Should we also update the Steering Committee section

Update Governance with broken links

---

main/src/com/google/refine/grel/controls/ForRange.java
main/tests/server/src/com/google/refine/grel/controls/ForRangeTests.java

Fixes #5520
- forRange can work with a negative increment.
- Fixes the bug to support both integer and floating point values.
- To reject invalid arguments and return an error message instead of an empty array.

Enhance forRange to accept negative increments (#5520)

---

refine

Fixes #5586
- Remove the following obsolete commands from the Linux refine script: 
- Linters/Formatters: `findbugs`, `pmd`, `cpd`, `jslint`, and `whitespace`.
- OpenRefine Broker: `broker`, `broker_appengine_upload`, and `broker_appengine_run`.
- `reconcile_server` lines in `ui_tests`.

Removed unneeded commands and lines in the Linux refine script

---

main/src/com/google/refine/expr/WrappedRow.java
main/src/com/google/refine/expr/functions/Cross.java
main/tests/server/src/com/google/refine/expr/functions/CrossTests.java

Fixes #5633
- Refactor to use static import for asserts so that we won't have a mix of styles in the module (separate commit)
- Fix NullPointerException when null parameters are passed and add a test for the condition (discovered while debugging)
- Fix `record` field access for lists of WrappedRows (only used by `cross()` so test added there)

Fix accessor for "record" field in lists of WrappedRows (output by cross function)

---

main/src/com/google/refine/expr/functions/strings/Split.java
main/tests/server/src/com/google/refine/expr/functions/strings/SplitTests.java

Fixes #5587
- Changes `split()` to filter trailing empty token when there's a trailing string separator and leading empty token when there's a leading pattern separator match.
- 
- 
Note in the diff that I actually noted the anomalous behavior when I wrote the original tests, but never investigated (and just wrote the test to match the current, rather than documented, behavior.

Filter empty tokens to match doc. Fixes #5587

---

pom.xml

There are 1 security vulnerabilities found in commons-fileupload:commons-fileupload 1.4
- [CVE-2023-24998](https://www.oscs1024.com/hd/CVE-2023-24998)
Upgrade commons-fileupload:commons-fileupload from 1.4 to 1.5 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade commons-fileupload:commons-fileupload to 1.5

---

.github/workflows/snapshot_release.yml

The CI test matrix still fails, seemingly for a new reason, so this is an attempt to fix it.

Attempt to fix the CI test matrix by pinning dependency versions

---

packaging/pom.xml

For #5583 (not sure it fixes it - I will ask folks to try the snapshot release once merged, and if that works I would backport this to 3.7)
Apparently dependabot did not propose this update although the version we are using is already quite a few months old. I am not sure why. Given #5667 it looks like this is not the only dependency that gets skipped.

Update launch4j-maven-plugin to 2.3.2, for #5583

---

refine.bat

Fixes #5359
- Moved functionality of `/d` to `/debug` and `/x` to `/jmx` for refine.bat.
- Implemented `/d`, `/v` and `/x` for refine.bat.
- Cleaned up some of the argument parsing to be more clear and concise.
- Changed the usage statement to reflect the changes.

Refine bat consistency cleanup

---

main/webapp/modules/core/styles/index/open-project-ui.css

improve readability of the no-projects message

---

main/webapp/modules/core/scripts/index/lang-settings-ui.js

given that the ActionArea's IDs are now used in  the URL let's not use an abbreviation.

change the language tab-url

---

refine.bat

- Reformat the usage statement for refine.bat:
- Remove unneeded quotes.
- Remove extraneous periods (...).
- Align option descriptions with action descriptions.
- Sort options and actions alphabetically.
- Shorten some of the descriptions.
Before:
After:

Reformatted and cleaned up refine.bat usage statement

---

refine

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18mF3dyLVYfYFn8DBhGJijLl0X3VYGNs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=9qMKnk7)
Fixes #5680 
- The check running script is only checking if OpenRefine is running on the given interface, not if "something" is running, the error message should therefore, not say that something is already running there but rather give a more generic error. "OpenRefine isn't running on $URL."
- 
-

updated the error code

---

benchmark/pom.xml
pom.xml

Resolves Dependabot alert 110
https://github.com/OpenRefine/OpenRefine/security/dependabot/110 which Dependabot was unable to generate a PR for.
It's a little bit worrying that Dependabot didn't alert on any of the other uses of TestNG where the version was specified via a variable, but only the one that was hardcoded. 
This switches the `benchmark` project to use the variable and updates it to a version that doesn't have the vulnerability.

Update TestNG to 7.7.1 - fixes CVE-2022-4065

---

main/src/com/google/refine/ProjectManager.java
main/src/com/google/refine/ProjectMetadata.java
main/src/com/google/refine/commands/project/SetProjectTagsCommand.java
main/src/com/google/refine/commands/row/GetRowsCommand.java
main/src/com/google/refine/history/History.java
main/src/com/google/refine/model/Project.java
main/tests/server/src/com/google/refine/ProjectManagerTests.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/history/HistoryTests.java
main/tests/server/src/com/google/refine/model/ProjectStub.java

Fixes #1380 Fixes #5387 Probably fixes #3475
- refactor row counter maintenance in ProjectMetadata so it's done when row list is updated rather than on every GetRows command. (#1380)
- Update row count when project is created/registered (#5387)
- Update row count for when opening legacy projects which were created before row count was stored in metadata (but do it in a way that doesn't change the Modified date for the project)

Refactor row count handling for ProjectMetadata. Remove from GetRows.

---

main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js

This fixes the tab order for the two reconciliation create buttons:
[Screencast from 2023-03-14 16-16-09.webm](https://user-images.githubusercontent.com/2631719/225048095-c2e2e8bd-41c5-4dae-ad54-a82f61bbe0e9.webm)
Previously the order would be reverse, as in the right button being focused before the left one.

fix the tab order for reconciliation create and match buttons

---

refine.bat

- Make refine.bat use `wmic` to get the available free memory instead of the inefficient `systeminfo ^| findstr /C:"Available Physical Memory"`.
WMIC (Windows Management Instrumentation Command-line) is a command-line interface for the Windows Management Instrumentation (WMI) technology. It has been available since Windows Server 2003 and Windows XP/Vista/7 and later.
On my desktop the time for 'Getting Free Ram' went from 2.5 seconds to instant.  For my laptop, it went from 3.5 seconds to almost instant.
Before:
After:

Use wmic for getting free ram in refine.bat

---

refine

- Remove unneeded quotes.
- Remove extraneous periods (...).
- Align option descriptions with action descriptions.
- Sort options and actions alphabetically.
- Shorten some of the descriptions.
Before:
After:

Reformatted the usage statement in the Linux refine script

---

main/webapp/modules/core/scripts/util/dialog.js

Fixes #5714
- Set containment property to prevent user from dragging jQuery UI dialogs above the top of the browser window.
I originally tried `containment: 'window'` but that didn't work as expected because the dialog-container is the full width of the browser window, so it prevented the user from moving the dialog left or right. So instead of that, I am setting a containment box with top = 0 to prevent the user from dragging the dialog above the top of the screen.  The bottom, right, and left boundaries are set sufficiently large that so user's can drag in those directions without limit on 4k displays.
After:

Made it so dialogs cannot be dragged past the top of the window

---

refine.bat

- Change doc URL from  http://bit.ly/1c2gkR to https://openrefine.org/docs/manual/installing#java.
- Don't print "Type 'refine /h' for usage." in this case.
- Also add a check to see if $JAVA is executable.

Corrected the error message and doc URL when JAVA_HOME is not set in refine.bat

---

.gitignore

Having a .gitignore file ignoring either extension folders or symlinks can be super useful during development. For example when testing extension compatibility with ones changes.

ignore .gitignore file in the extension directory

---

main/webapp/modules/core/styles/index/default-importing-sources.css

ensure the clipboard import input does not overflow in narrow windows

---

main/webapp/modules/core/scripts/util/i18n.js

This prevents failing i18n loads for extensions from changing the language of the rest of the interface, resulting in untranslated text (falling back to the message codes themselves).
Closes #5750. (See more detailed diagnosis of the problem in https://github.com/OpenRefine/OpenRefine/issues/5750#issuecomment-1489890024)
I would like to release this soon in 3.7.2.

Fix locale loading in the frontend

---

refine

The refine script prints out the free memory and run memory config for every action, even though the "run" memory config is only relevant when running OpenRefine. For other actions e.g. "build", "dist", etc. it is not applicable.
```
$ ./refine build
-------------------------------------------------------------------------------------------------
You have 5936M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://openrefine.org/docs/manual/installing#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
```
This PR changes it so this message is only printed for the run action.

Change the refine script to print free memory message only for the run action

---

main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/project/browsing-engine.js

Fixes #5749
- Made it so the initial facet height is properly set when facets are added when the facet panel is not visible.
- Add callback on jQuery event "tabsactivate". If the new active tab is a facet tab, then set the initial height for all facets (if not already set).

Fix initial facet height when facets are added while the facet panel is not visible

---

refine
refine.bat

Fixes #5776
Fixes #5773
- Allow JAVA_HOME to be set from the ini.
- Give command line options precedence over the ini.
- Clean up consistency in some wording between refine.bat and refine scripts.
Tested on Ubuntu Linux:
```
./refine
./refine -h
./refine run
./refine test
./refine clean
./refine build
./refine -c my.ini
./refine -c my.ini run
./refine -c missing.ini
./refine -m 8192m
./refine -c my.ini -m 8192m
./refine -m 8192m -c my.ini
./refine -c missing.ini -m 8192m
./refine -p 3344 -i 127.0.0.2 -m 8192m --debug --jmx
./refine -c my.ini -p 3344 -i 127.0.0.2 -m 8192m --debug --jmx
```

Added fix for command line options in refine

---

main/webapp/modules/core/scripts/index/edit-metadata-dialog.js

Fixes #5774
- Removed code from #4527 that caused a regression in the dialog for project metadata that caused it to jump to the top left of the screen when being dragged.
After:

Fixed project metadata dialog so it doesn't jump to the top left corner when it is dragged

---

main/src/com/google/refine/ProjectMetadata.java

Fix error handling issue highlighted in #5772. 
Doesn't fix the underlying bug, but will correctly report the error back to the client.

Don't swallow exception on error. Refs #5772

---

main/webapp/modules/core/scripts/project/browsing-engine.js

- Made it so numeric facets are properly refreshed when switching tabs from the undo/redo history tab.
Before:
After:

Made it so numeric facets are properly refreshed when switching tabs

---

refine.bat

Fixes #5795
- Removed the support log in refine.bat and added a "free memory" banner to refine.bat.
```
-------------------------------------------------------------------------------------------------
You have 6275M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://openrefine.org/docs/manual/installing\#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
Java 17 (17.0.2)
22:33:51.883 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
22:33:51.889 [            refine_server] refine.memory size: 1400M JVM Max heap: …
```

Removed the support log in refine.bat and added a "free memory" banner to refine.bat

---

refine
refine.bat

- Made the invalid action output for the Linux refine script consistent with the refine.bat script, and cleaned up some extra comments in refine.bat.

Made the invalid action output for the Linux refine script consistent with refine.bat

---

main/src/com/google/refine/ProjectMetadata.java
main/src/com/google/refine/io/FileProjectManager.java
main/src/com/google/refine/io/ProjectMetadataUtilities.java
main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java

Fixes #3805
Frequent writes to metadata files are due to deprecated class property `written` in `ProjectMetadata.java` which has been assigned null and remain unchanged. When `FileProjectManager` try to judge whether there is changed in metadata, it utilize this property for every project, resulting in metadata files written for every project.
Solution is to store temporary property recording the last save time for each metadata and update it every time `FileProjectManager` writes the metadata.
- Modified property `written` by `_lastSave` in `ProjectMetadata.java`
- Add setter for `_lastSave` which store the current localdatetime in `ProjectMetadata.java`
- Modified `isDirty` method in `ProjectMetadata.java` which compares `_lastSave` and `_modified` …

(I#3805) Fix problem with frequent writes to metadata files

---

.github/workflows/pull_request.yml
.github/workflows/snapshot_release.yml

This reduces the log size in the CI by avoiding the duplication of download progress lines:
```
Progress (1): 1.4/2.1 MB
Progress (1): 1.5/2.1 MB
Progress (1): 1.5/2.1 MB
Progress (1): 1.5/2.1 MB
Progress (1): 1.6/2.1 MB
Progress (1): 1.6/2.1 MB
Progress (1): 1.6/2.1 MB
Progress (1): 1.7/2.1 MB
Progress (1): 1.7/2.1 MB
Progress (1): 1.7/2.1 MB
Progress (1): 1.8/2.1 MB
Progress (1): 1.8/2.1 MB
Progress (1): 1.8/2.1 MB
Progress (1): 1.9/2.1 MB
Progress (1): 1.9/2.1 MB
Progress (1): 1.9/2.1 MB
Progress (1): 2.0/2.1 MB
Progress (1): 2.0/2.1 MB
Progress (1): 2.0/2.1 MB
```

Invoke Maven in batch mode in CI to avoid progress info in logs

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/project/history-apply-dialog.html
main/webapp/modules/core/scripts/project/history-panel.js
main/webapp/modules/core/styles/common.css

Fixes #5022
-     "Import" button added to the Apply Operation History dialogue
-     On clicking import, the user prompted to upload the file
-     Once the file is uploaded the content (assuming can be read correctly) is populated into the operation history window
-     User can then click "Perform operations" as usual
So far I have been able to create the Upload button but when I try to upload the file nothing happens because I need the correct URL to download the file in line 355. Let me know your suggestions on how to best approach this. Thanks.

Apply operation json from a file

---

main/webapp/modules/core/scripts/project/extension-bar.js

tab to select, enter to open(the menu system is not yet keyboard accessible so you can't select or trigger an action)

menu buttons in the extension-bar can now be opened with the keyboard

---

main/webapp/modules/core/styles/jquery-ui-overrides.css

jQueryUI uses a combination of `li`/`a` to build it's tabLists rather than `button` as a result(one of many) it does not get an outline when focused.
This adds such an outline manually using CSS. You can test this by just tabbing through the interface, when the tab navigation buttons now are focused they have an outline just like other elements.

add an outline to tab buttons when focused

---

main/webapp/modules/core/scripts/project.js

Instead of watching for 'mouseover' this checks for 'focus' which ensures both clicking and tabbing generates a new permalink.

project-permalink: keyboard support

---

main/webapp/modules/core/styles/views/data-table-view.css

This ensures that the pointer cursor is only in use for the menu buttons and not the whole column headers.

fix pointer cursor in column headers

---

pom.xml

There are 1 security vulnerabilities found in org.eclipse.jetty:jetty-server 9.4.48.v20220622
- [CVE-2023-26049](https://www.oscs1024.com/hd/CVE-2023-26049)
Upgrade org.eclipse.jetty:jetty-server from 9.4.48.v20220622 to 12.0.0.beta0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.eclipse.jetty:jetty-server to 9.4.51

---

main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
main/webapp/modules/core/scripts/views/data-table/column-header.html
main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/styles/views/data-table-view.css

Fixes #4806. This is an attempt to add support for resizing columns.
It is not ready yet because the initial sizing of the columns has changed and is likely to be less appropriate in some cases. But I would already welcome feedback about the approach!
The initial sizing has changed because I needed to change the way textual content is wrapped inside cells (and in column headers), to allow for columns to resize correctly. This has an effect on the initial sizing as well.
Some details about the approach:
* to change the size of a column, one can either apply inline CSS to the `<th>` and all the `<td>`s in that column, or use the dedicated `<col>` element. The latter felt cleaner (only applying style in one place) but maybe the other approach has other advantages?
* to handle the resizing …

Support for resizing columns

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
main/webapp/modules/core/styles/views/data-table-view.css

This swaps a custom `<details>` implementation for a HTML based one making it keyboard accessiable.

Make it possible to set custom headers using only the keyboard when fetching urls

---

.github/workflows/pull_request.yml

For #5909.
I am not sure why we were previously running the CI checks on the PR branch itself and not on the merge of the PR branch with master, which is the default behavior. That default makes sense to me since it is more faithful to the end result of the merge.
The reason it is related to #5909 is that it creates spurious coverage decreases as in https://coveralls.io/builds/60565681 (see the file [TransposeColumnsIntoRowsOperation.java](https://coveralls.io/builds/60565681/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Foperations%2Fcell%2FTransposeColumnsIntoRowsOperation.java#L80), whose coverage increased in master and therefore is reported as a decrease of coverage).

Run PR CI on merge commits and not on original PR branch

---

extensions/database/pom.xml

There are 1 security vulnerabilities found in org.xerial:sqlite-jdbc 3.39.3.0
- [CVE-2023-32697](https://www.oscs1024.com/hd/CVE-2023-32697)
Upgrade org.xerial:sqlite-jdbc from 3.39.3.0 to 3.41.2.2 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.xerial:sqlite-jdbc to 3.41.2.2

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js

Fixes #5907 
- Both name and id are displayed for the default types now.

now the default types are displayed with both name and id

---

main/src/com/google/refine/operations/recon/ReconOperation.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

Fixes #5908
- Made facet by judgement resizable and scrollable.

Made facet by judgment resizable

---

extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java

Fixes #5385.
In general I try to stay away from working on Wikibase integration in OpenRefine at the moment, but this bug feels pretty important and easy to solve.

Skip Wikibase edits on deleted items

---

packaging/pom.xml
pom.xml

This hopefully fixes #5583, but makes sense independently of it I think.
As mentioned in the issue, the upper bound on Java compatibility is only based on what we test for. Given that Java runtime environments are generally very backwards compatible, it feels wrong to me to refuse launching if Java is more recent than the versions of Java we test OpenRefine with. So I would just propose to drop this maximum version altogether.
I would propose to include this in a 3.7.3 release.

Remove maximum Java version on Windows.

---

main/tests/cypress/cypress/support/commands.js
main/tests/cypress/package.json
main/tests/cypress/yarn.lock

- Removed the following unused dependencies in the Cypress package.json:
- cypress-wait-until
- dotenv
-  fs-extra
- uniqid
- jsdoc

Removed unused dependencies for Cypress

---

main/webapp/modules/core/scripts/project.js

Prior to this the UI would make a call to `get-project-metadata`, then when it finished to `get-models`, then to `get-all-preferences` during project initialization. Now all these requests are all made in parallel, greatly speeding up project initialization.

Make project initialization requests in parallel

---

main/src/com/google/refine/expr/functions/Length.java
main/tests/server/src/com/google/refine/expr/functions/LengthTests.java

Also add tests for other uses of length() function.
Fixes #5991

length() returns # of keys in object. Fixes #5991

---

SECURITY.md

- replace mention of broken mailing list by the advisory committee. We can also consider establishing other groups or email aliases in the future - the priority for me is to have something that actually works
- update supported versions (we probably should add it as a step in the release instructions to keep this up to date)

Refresh SECURITY.md

---

main/resources/com/google/refine/grel/ControlEvalError.properties
main/src/com/google/refine/grel/ast/VariableExpr.java
main/src/com/google/refine/grel/controls/ForEachIndex.java
main/tests/server/src/com/google/refine/grel/controls/ForEachIndexTests.java

Fixes #3147
I'm on the fence as to whether this should be a separate control (name TBD), as I originally spec'd, or if rolling the functionality into the existing `forEachIndex` is close enough semantically given that the array index and the object key are both performing essentially the same function. This pull request adopts the latter approach. Doing it the other way would basically involve cloning the code, giving it a new function name, and making the error messages more specific.
- add tests for `forEachIndex`
- enhance error checking to reject using the same variable name for both index and value
- add support for JSON objects withe same structure, but the object key instead of the array index returned in the index/key variable

Add support for JSON Objects to forEachIndex() control

---

main/tests/cypress/cypress/support/commands.js
main/tests/cypress/package.json
main/tests/cypress/yarn.lock

- Bump Cypress from 12.17.3 to 12.17.4.
- Made it so `waitForProjectTable()` uses `numRows` instead of `arguments.length`.

 Bump Cypress from 12.17.3 to 12.17.4

---

main/src/com/google/refine/importers/TextFormatGuesser.java
main/src/com/google/refine/importing/EncodingGuesser.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/data/csv-with-bom.csv
main/tests/server/src/com/google/refine/importing/EncodingGuesserTests.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java

Fixes #1241
* UTF-8-BOM to the encoding guesser
* Add support for stripping the BOM to the importer

CSV Byte Order Mark (BOM) support. Fixes #1241

---

.github/dependabot.yml

To avoid PRs like #6032, which require changes in Butterfly first.

Fix jetty dependabot ignore

---

.github/workflows/pull_request_e2e.yml
main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js
main/tests/cypress/package.json
main/tests/cypress/yarn.lock

- Bump Cypress from 12.17.4 to 13.1.0.
- Bump Node from 14 to 16 for Cypress since Cypress dropped support for 14.
> Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with Node 16's end-of-life schedule. It is recommended that users update to at least Node 18.
Ref: https://docs.cypress.io/guides/references/changelog#13-0-0.

Bump cypress from 12.17.4 to 13.1.0

---

main/webapp/modules/core/langs/translation-en.json

Follow-up for #6021 
- Add quotes around the column in the title of the split into several columns dialog:

Add double quotes to column in title of split column into several columns dialog

---

main/src/com/google/refine/sorting/StringCriterion.java
main/tests/server/src/com/google/refine/operations/row/RowReorderOperationTests.java

Fixes #6047
- Fix the case sensitive parameter being ignored for string sorts
- Correct parameter ordering for asserts in tests
- Add tests for reversed sort parameter, empty item position, and string sort

Fix case sensitive string sort. Fixes #6047

---

extensions/database/module/langs/translation-cs.json
extensions/database/module/langs/translation-en.json
extensions/database/module/langs/translation-en_GB.json
extensions/database/module/langs/translation-es.json
extensions/database/module/langs/translation-fa.json
extensions/database/module/langs/translation-fr.json
extensions/database/module/langs/translation-he.json
extensions/database/module/langs/translation-id.json
extensions/database/module/langs/translation-it.json
extensions/database/module/langs/translation-ja.json
extensions/database/module/langs/translation-ko.json
extensions/database/module/langs/translation-ml.json
extensions/database/module/langs/translation-nb_NO.json
extensions/database/module/langs/translation-nl.json
extensions/database/module/langs/translation-pl.json
extensions/database/module/langs/translation-pt.json
extensions/database/module/langs/translation-pt_BR.json
extensions/database/module/langs/translation-sv.json
extensions/database/module/langs/translation-tr.json
extensions/database/module/langs/translation-zh_Hans.json
extensions/database/module/scripts/index/database-source-ui.js

Fixes #6019
- Make SQL bad keyword detection more reliable by using regex instead of substring
- Improve localization by not using string concatenation to build messages
BUT I'm not convinced that we shouldn't just remove all this code since it's almost impossible to do reliably and could give users/administrators a false sense of security. They should be using their DB admin privs to restrict user access.

Improve SQL bad keyword detection - fixes #6019

---

extensions/database/src/com/google/refine/extension/database/DatabaseConfiguration.java
extensions/database/tests/src/com/google/refine/extension/database/DatabaseConfigurationTest.java

No issue.
Changes to make the linter happy. It looks like the latest security patch made it through CI without linting?
@wetneb any idea how that happened?

formatter:format changes in database module

---

extensions/wikibase/module/scripts/schema-alignment.js
main/webapp/modules/core/scripts/dialogs/add-column-by-reconciliation.js
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
main/webapp/modules/core/scripts/util/custom-suggest.js
main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

Fixes #3141 
an object variable sanitizedSuggestOptions which only takes some properties used by the suggestOptions object and then I pass this new var sanitizedSuggestOptions for initializing the suggest library.
I am trying to take this approach for all the places where we have suggestOptions or suggestConfig variables.

Introducing a new variable that takes only required properties of suggest options and excludes the flyout properties

---

main/src/com/google/refine/ProjectMetadata.java
main/src/com/google/refine/io/FileProjectManager.java
main/src/com/google/refine/io/ProjectMetadataUtilities.java
main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java

Fixes #3805
- Repairs constructor which sets modified date on projects
- Adds test coverage to make sure we don't write newly read projects before they're modified
- initializes the lastSaved timestamp on project load (#3805)
- check for and log errors on file renames & deletes
- refactor to decide if file write is needed upfront rather than writing file and throwing it away if unneeded
- fix test from PR #4796 to correctly test project removal
- write out workspace on project removal (fixes regression which re-broke #1418)

Don't write newly read projects before they're modified

---

extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java

Fixes #5656 
Hi there!
I've been working on the issue, thanks for your help in the issue thread
- I updated the regex to only disallow control characters, \\p{Cc} will match control characters (ranges 0x00-0x1F and 0x7F-0x9F)
- I updated the validation for the file name length in bytes, encoded as UTF-8
- I updated the tests, adding some that should raise warnings and disabling testInvalidCharactersInFilenameVerticalBar and testInvalidCharactersInFilenameHTMLEscaped
Please let me know what you think

Widen scrutinizer regex pattern - fixes #5656 

---

extensions/wikibase/module/scripts/schema-alignment-tab.html
extensions/wikibase/module/scripts/schema-alignment.js
extensions/wikibase/module/styles/schema-alignment.less
main/webapp/modules/core/scripts/project.js

Fixes #6070
- Backport #5953 from master to 3.7

Backport SchemaAlignment.resize() removal

---

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js
main/tests/cypress/package.json
main/tests/cypress/yarn.lock

-  Bump cypress from 13.2.0 to 13.3.0.
- Fixes the 'Test the mass edit from a Facet' test in facets.cy.

Bump cypress from 13.2.0 to 13.3.0

---

main/src/com/google/refine/RefineServlet.java
main/src/com/google/refine/commands/Command.java

Allow extensions to register commands which can respond to HTTP HEAD requests.

API: Add HTTP HEAD support to commands

---

.github/workflows/pull_request_server.yml
pom.xml

Fixes #6087
Let's see if the Temurin 21 distribution is already available through GitHub Actions.

Bump max Java version to 21

---

main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js

Fixes #3140 
On our end we have been running with this patch (all restrictions) for a few months without any problems. I have also tested the change with the common Wikidata reconciliation service.
I therefore suggest that we opt for all restrictions and hope that if there is a _valid_ use-case for loosened restrictions in use today its discovered during snapshots or pre-releases.

Sandbox the reconciliation preview iframes

---

main/src/com/google/refine/util/HttpClient.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java

Fixes #6137 
- Instead of swallowing URL/URI syntax errors and returning `null` to the user, return an `EvalError` object with the message from the exception
- change the test behavior to match

Return error, not null, on bad URL. Fixes #6137.

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
main/webapp/modules/core/styles/reconciliation/standard-service-panel.css

Follow-up to https://github.com/OpenRefine/OpenRefine/pull/6060
* Reconcile Against Type Mapping
* After selecting a type mapping from the suggest dropdown, the mapping is displayed as "`type` `(Q-id)` edit" (See screenshot below).
* Clicking edit will revert the field back to an editable textbox.
* Start Reconciling... button
* If 'Reconcile against type' was selected reconciling will only begin if the type was successfully mapped  (name, id).  
* If the type mapping contains plaintext, it is invalid so an alert window is popped up 'Reconcile against type xxxx is unmapped.' and the reconciliation is aborted.

Improved type selection in recon dialog

---

main/tests/cypress/cypress/e2e/create-project/preview_project.cy.js
main/tests/cypress/cypress/support/commands.js

Fixes #6158
Changes:
- Remove call to `waitForImportUpdate()`
- Updated command description of `waitForImportUpdate()`
`waitForImportUpdate()` has the same problem as `waitForOrOperation()` which I have been trying to remove.  Both of those methods are waiting for a temporary loading/in-progress element to be visible and then not visible.
The problem is that the element may have been shown and hidden again before this code executes, causing it to wait forever until it times out.
The solution is to not focus on the transient loading indicators, but to just do `cy.get()` and assertions on the expected state after the operation completes. For long running operations,  the timeout on the `cy.get()` command may need to be increased if the operation could exceed the default timeout of 4 …

Fix flaky Cypress test in cypress/e2e/create-project/preview_project.cy.js "Tests disabling of automatic preview" 

---

main/webapp/dependencies.json
main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/scripts/index/open-project-ui.js
main/webapp/package-lock.json
main/webapp/package.json

- Change formatting of dates in Open Project table to use Intl.DateFormat instead of Moment.js.
- Formatting the same except AM/PM is not shown because Intl.DateFormat doesn't support that when 24-hour military time is used.
- Webapp package.json
- Remove datejs-coolite (Unused after https://github.com/OpenRefine/OpenRefine/pull/6157).
- Remove Moment.js (Deprecated https://momentjs.com/).
BEFORE (Moment.js - using 24HR time with AM/PM)
AFTER (Intl.DateFormat using 24HR time without AM/PM)

Remove Datejs and Moment.js dependencies

---

main/src/com/google/refine/history/HistoryEntry.java

Fixes #3047 This should have been included as part of the project metadata changes.
- Changes internal timestamp data type for HistoryEntry from OffsetDateTime (with a business logic enforced Zulu timezone) to the natural type Instant. 
Serialization is unchanged and no tests were changed.

Switch HistoryEntry to Instant from OffsetDateTime(at UTC)

---

main/pom.xml
main/webapp/WEB-INF/velocity.properties
pom.xml

Fixes #4078. Resolves [CVE-2020-13936](https://github.com/advisories/GHSA-59j4-wjwp-mw9m)
- Update Apache Velocity from 1.5 to 2.3
- Set properties for maximum 1.x compatibility per version upgrade notes 
https://velocity.apache.org/engine/2.0/upgrading.html

Update Velocity from 1.5 to 2.3. Fixes #4078 / CVE-2020-13936

---

main/tests/cypress/cypress/e2e/project/grid/column/reconcile/copy_reconciliation_data.cy.js

The copy reconciliation data test copies a column, then counts 'Choose new match' in all TDs, including the original column.  On slower computers the count is 4.  On faster computers the count is 8.
- Fix flaky Cypress test that fails on faster computers.
- Change to first wait for 'duplicated_column' to show up, then count 'Choose new match' occurrences only in the last column.

Fix flaky Cypress test: Copy reconciliation data from species to species_copy

---

extensions/wikibase/module/styles/schema-alignment.less

Closes #6163.
To be released in an upcoming 3.7 patch release (3.7.7)

Fix bad backport of "wikibase: remove the need for SchemaAlignment.resize()"

---

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/add_columns_based_on_this_column.cy.js
main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
main/tests/cypress/cypress/support/commands.js

The Cypress tests related to Jython have become flaky due to the recent change to [using lazy initialization for the Jython interpreter](#6175), resulting in the first server request related to Jython sometimes exceeding the default 4 second timeout.
Ref: https://cloud.cypress.io/projects/s5du3k/analytics/flaky-tests
Changes:
- Added 10 second timeout for Jython related tests, so that the `cy.get()` calls will wait up to 10 seconds.

Added 10s timeout for Jython tests to fix flakiness

---

extensions/gdata/module/authorized.vt
extensions/gdata/module/langs/translation-en.json
extensions/gdata/module/scripts/index/gdata-source-ui.js
extensions/gdata/module/scripts/index/importing-controller.js
extensions/gdata/module/scripts/project/exporters.js
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/util/dialog.js

Fixes #6187
Changes:
* Add `DialogSystem.alert()` to use in place of `alert()`.
* Change all uses of `alert()` and `window.alert()` in gdata extension to use `DialogSystem.alert()`.
Notes:
* The text displayed in `alert()` in Chromium browsers is not selectable if the text contains a newline character.
Before:
After:

Made text selectable in alert dialog

---

main/webapp/modules/core/project.vt

Part of a downstream attempt to nuke Velocity usage.

project client: get the project-id from the URL rather than from Velocity injection

---

extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java

I can't find authoritative documentation about this so this is pretty much example driven. To reflect that, I have lowered the severity of the check so that users are not prevented from uploading if the check incorrectly fails.
Closes #5656.

Widen regex of allowed characters in Commons filenames.

---

refine
refine.bat

This helps developers reformat their code according to our standards.
Closes #6166.
Not tested on Windows yet.

Add 'lint' option to refine(.bat) scripts

---

main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
main/tests/server/src/com/google/refine/importers/ImporterUtilitiesTests.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java

Fixes #6171 
- Made it so the following Maven tests do not depend on locale:
- `readSimpleData_0Header_1Row()`
- `readSimpleData_RowLongerThanHeader()`
- `serializeReconProcess()`
- `readXlsxAsText()`

Fixed Maven tests to work in different locales

---

main/tests/cypress/package.json
main/tests/cypress/yarn.lock

This reverts commit a68ba3b26c96ce116c377612c5f1834145b4c002.
See #6224, #6231.

Revert "Bump cypress from 13.5.1 to 13.6.0"

---

main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js

Fixes #6236
I was able to reproduce the issue by clicking the 'Match this cell' button in the preview overlay. Before the change, refreshing the page after clicking 'Match this cell' updates that cell's contents.
The UI just needed to update when clicking the 'Match this cell' button.
After:
- Make UI update when clicking the 'Match this cell' button.

Make UI update when matching cell

---

main/src/com/google/refine/commands/Command.java

The response encoding was being set after the writer was already created, so it was using the wrong (default) encoding.
Also fix another place where UTF-8 encoding is not being set for a response.
Fixes #6063
I've got a more general refactoring and cleanup of the JSON responses in progress, but this fixes the immediate issue which was reported.

Make sure encoding is set before fetching writer. Fixes #6063

---

.github/workflows/codeql_java.yml
.github/workflows/codeql_javascript.yml
.github/workflows/snapshot_release.yml
.github/workflows/unassign_issues.yml

I am seeing the snapshot release GitHub action workflow being triggered for each cloned repo when a user syncs their master branch with OpenRefine's master branch. The snapshot build fails on these runs and the e2e tests are published to Cypress Dashboard as duplicate runs.
Changes:
- Don't run the following workflows on forks:
- snapshot_release.yml - (Should not be run on forks).
- codeql_java.yml - (Shouldn't be run on forks as these already run on OR's master branch when you commit).
- codeql_javascript.yml - (Shouldn't be run on forks as these already run on OR's master branch when you commit).
- unassign_issues.yml - (Should not be run on forks as well).
The following screenshot shows 4 workflow runs on Cypress Dashboard that have the same commit from when developers sync their …

Fix for workflows running on forks

---

.idea/codeStyles/Project.xml

No issue.
- Sets IntelliJ to match the bulk of our historical Javascript files which use a 2 space indent.
This can be changed to track any new standard we choose.

Set IntelliJ setting for Javascript indent to 2 spaces

---

refine

Fixes #6271 
- provide default specs definition of all specs if one is not provided
- don't set group unless recording
- don't silently fail if an OpenRefine server is already running

Fix e2e_tests (Cypress). Fixes #6271

---

refine.bat
server/src/com/google/refine/Refine.java

Fixes #6286
-  In the existing code, we are using slf4j as below
Logger logger = LoggerFactory.getLogger("refine");
logger.warn("No refine.host specified while binding to interface 0.0.0.0, guessing localhost.");
Whereas for setting the logging level, we were setting it for log4j rootLogger as below
```
org.apache.log4j.Logger.getRootLogger().setLevel(Level.toLevel(Configurations.get("refine.verbosity", "info")));
```
Hence the refine logger was defaulting to the value mentioned in the log4j2.properties.
```
logger.refine.name = refine
logger.refine.level = info
```
- I have used the log4j logger
```
final static org.apache.log4j.Logger logger = LogManager.getLogger("refine");
```
and set the logging level for it. This resolves the issue.
To test …

Fix setting the log level from the command line

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js

Follow-up to #6118 suggested by #6184.
Because the accessing the API directly with the browser is rarely useful for users, I think we don't need to show this link in this dialog. The full URL is visible in the previous step (service selection), which enables users to copy the link (for instance to share it with someone else who would like to install the same service).
@Abbe98 note that the problem you want to solve in #6184 (the dialog being pushed down by the documentation link when it is present) is still here - it might make sense to put this documentation link in a totally different place so that this does not happen. But then the solution will be different from the one you proposed in #6184.

Remove 'Access service API' link from reconciliation dialog

---

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js

Closes #6326.
This does the wiring of event listeners as soon as we set up the dialog, not just once we get the types back.

Fix wiring of event listeners in recon dialog

---

.github/workflows/snapshot_release.yml

Closes #6349.
The "package" goal is redundant because it is already implied by "deploy", so by removing it we get rid of this duplication.

Remove duplicate packaging steps in CI

---

CONTRIBUTING.md

Fix link to https://openrefine.org/docs/technical-reference/contributing and  https://openrefine.org/docs/technical-reference/code-contributions

Fix Broken link in CONTRIBUTING.md

---

GOVERNANCE.md

Update the governance document to include the two new advisory committee members. See the PR for the official announcement via the blog [openrefine.org/pull/290](https://github.com/OpenRefine/openrefine.org/pull/290)

Update Advisory Committee members

---

main/src/com/google/refine/grel/Parser.java
main/src/com/google/refine/grel/Scanner.java
main/src/com/google/refine/grel/ast/OperatorCallExpr.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/grel/GrelTests.java

Fixes #6341. Closes #6340
- restrict string concatenation (+) to cases where at least one operand is a string (to avoid things like concatenating two dates as strings)
- Add support for dates and strings to comparison operators Strings use a collator for the default locale with normalized decomposition for the comparisons.
- Above implementation uses Comparable, so any future data types that implement that interface should get supported for free
- Add a bunch more tests

Improve GREL operators. Fixes #6341 Closes #6340

---

extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/QuantityScrutinizer.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/QuantityScrutinizerTest.java

Fixes #5452 
Fix for removing the warning for Statements which do not have any unit like student count
Added the logic for not showing warning in case Statement does not have any unit
- 
-
-

#5452 Removing missing unit warning

---

refine

Avoid going through HTTP proxy for requests to localhost in refine script

---

refine
refine.bat

Fixes #6087
- Updates `refine` and `refine.bat` scripts from Java 17 to Java 21 as upper bound

Support Java 21 in refine scripts

---

main/src/com/google/refine/commands/expr/GetExpressionHistoryCommand.java
main/src/com/google/refine/commands/expr/LogExpressionCommand.java
main/tests/cypress/cypress/e2e/project/grid/column/edit-cells/transform.cy.js
main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
main/tests/server/src/com/google/refine/commands/expr/ExpressionCommandTestBase.java
main/tests/server/src/com/google/refine/commands/expr/GetExpressionHistoryCommandTests.java
main/tests/server/src/com/google/refine/commands/expr/GetExpressionLanguageInfoCommandTests.java
main/tests/server/src/com/google/refine/commands/expr/GetStarredExpressionsCommandTests.java
main/tests/server/src/com/google/refine/commands/expr/LogExpressionCommandTests.java
main/tests/server/src/com/google/refine/commands/expr/ToggleStarredExpressionCommandTests.java

Fixes #6362
- restores the local (ie project specific) expression history
- adds both unit tests and Cypress e2e tests to cover functionality

Restore project expression history. Fixes #6362.

---

LICENSE.txt

At the moment, the copyright notice only mentions Google Inc., which feels weird given that a lot of work has been done since, so I feel like it's worth adding a mention of "OpenRefine contributors", which has been the way we credit newer contributions in copyright headers throughout the project.
This is motivated by the license being shown in the Windows installer, to be released for the first time in 3.8.

Update license to mention OpenRefine contributors

---

main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/data/notazip.zip
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java

Fixes #6253
- Use ZipFile class to pre-check for errors since it does a better job than ZipInputStream.
- Add test for non-zip format files with .zip extension

Check for invalid Zip file & report to user. Fixes #6253

---

main/src/com/google/refine/exporters/CsvExporter.java
main/src/com/google/refine/importers/ImporterUtilities.java
main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/tests/server/src/com/google/refine/exporters/TsvExporterTests.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java

Fixes #2071
- Don't escape quotes when writing TSV format
- Escape \n and \r as is common practice
- Adjust tests to match desired behavior (they were written over a decade ago to match the observed behavior of the CSV library rather than the industry practice)
- Switch to real TSV parser for case where \t is the separator and there are no "exotic" options (so users can still use the CSV importer with \t if they need fancy quote support or something similar)
- Add test for unescaping of \t, \n, \r

Use real TSV exporter/importer. Fixes #2071

---

main/src/com/google/refine/grel/Scanner.java
main/tests/cypress/cypress/e2e/project/grid/column/edit-cells/replace.cy.js
main/tests/server/src/com/google/refine/grel/GrelTests.java
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js

Fixes #6367 
While using replace from "”" to """, value.replace("”",""") grel expression.
Added code to escape double quotes(") when using replace.

Fixes #6367: replace doesn't work

---

main/src/com/google/refine/commands/Command.java
main/src/com/google/refine/commands/HttpUtilities.java
main/src/com/google/refine/importers/ExcelImporter.java
main/src/com/google/refine/importers/XmlImporter.java
main/src/com/google/refine/importing/DefaultImportingController.java
main/tests/cypress/cypress/e2e/create-project/create_project.cy.js
main/tests/cypress/cypress/fixtures/AAT-with-xsi.xml
main/tests/cypress/cypress/fixtures/AAT.xml
main/webapp/modules/core/scripts/index/default-importing-controller/controller.js

Fixes #6058
- check for errors during createParserUIInitializationData phase
(e.g. XML or JSON parse errors) and pass them to the front end
- DefaultImportingController now extends Command since it's really
a command and it provides direct access to HTTP response methods
- DRY up Command and HttpUtilities redundant code
- add front end error handling for when initial preview parse fails
and display error to the user
- use new error dialog instead of alert()s everywhere
- locally detabify Javascript near diffs to make code more readable
- add XML import e2e tests with both success and error cases
(no XML tests previously & still missing most formats except CSV)

Report importer initialization errors. Fixes #6058

---

extensions/database/tests/src/com/google/refine/extension/database/DatabaseImportControllerTest.java

Addresses the issue found in PR #6407 
- Switch generic test to use SQLite instead of MySQL so no separate database installs are required (and test isn't skipped by default)

Switch generic test to use SQLite instead of MySQL

---

extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
extensions/database/tests/src/com/google/refine/extension/database/DatabaseImportControllerTest.java
extensions/gdata/src/com/google/refine/extension/gdata/GDataImportingController.java
main/src/com/google/refine/commands/Command.java
main/src/com/google/refine/commands/importing/ImportingControllerCommand.java
main/src/com/google/refine/commands/project/CreateProjectCommand.java
main/src/com/google/refine/commands/project/ImportProjectCommand.java
main/src/com/google/refine/importing/DefaultImportingController.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/src/com/google/refine/util/ParsingUtilities.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java

Fixes #6403
Changes proposed in this pull request: 
- Deprecate all methods in `ParsingUtilities` that return `java.util.Properties`.
- Introduce a new method, `static public Map<String, String> parseParameters(HttpServletRequest request)`, as a replacement for `parseUrlParameters`. This new method utilizes the `request.getParameterMap()` functionality for its implementation.
- Modify all uses of `parseUrlParameters` to use the new method.
- Adjust all necessary code to accommodate the new return type `(Map<String, String>)`.
- Deprecate all public methods `ImportingUtilities` that use `java.util.Properties` and make new versions of them using `Map<String, String>` instead.

Remove use of Properties for URL query parsing, fixes #6403

---

main/src/com/google/refine/model/Cell.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
main/tests/server/src/com/google/refine/importers/FixedWidthImporterTests.java
main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
main/tests/server/src/com/google/refine/importers/MarcImporterTests.java
main/tests/server/src/com/google/refine/importers/OdsImporterTests.java
main/tests/server/src/com/google/refine/importers/RdfTripleImporterTests.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java
main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
main/tests/server/src/com/google/refine/operations/cell/JoinMultiValuedCellsTests.java
main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
main/tests/server/src/com/google/refine/operations/cell/SplitMultiValuedCellsTests.java
main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
main/tests/server/src/com/google/refine/operations/column/ColumnReorderOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowReorderOperationTests.java

Closes #6372. Follow-up to #6371.
This is a preparation before backporting more tests from the 4.0 branch.
There are a couple of places which I didn't migrate because checking for equality on reconciliation objects is currently inconvenient (as `equals(Object)` is not overridden on the `Recon` class). I'll follow-up with a fix for that.
The only change in non-test classes is making `Cell` serializable.

Introduce test utility to compare project contents

---

main/src/com/google/refine/importers/JsonImporter.java
main/tests/server/src/com/google/refine/importers/JsonImporterTests.java

Fixes [#3243](https://github.com/OpenRefine/OpenRefine/issues/3243)
- Ignore JSON comments by default while importing JSON files

[#3243] Ignore JSON comments by default

---

.github/workflows/snapshot_release.yml

Following up to the upgrate of maven-gpg-plugin to 3.2.0 (#6435). See https://issues.apache.org/jira/projects/MGPG/issues/MGPG-90?filter=allopenissues.

Fix signing of released artifacts in GitHub Actions

---

main/webapp/modules/core/styles/views/data-table-view.css

Fixes #6440
- `padding: 0` - Removes unwanted padding
- `background-color: transparent` - Converts grey background into transparent color

Removed grey background from button tag

---

extensions/database/pom.xml
extensions/gdata/pom.xml
extensions/jython/pom.xml
extensions/pc-axis/pom.xml
extensions/wikibase/pom.xml
server/src/com/google/util/logging/IndentingLayout.java

Fixes #6475
- Add SLF4J & Jackson modules as "provided" to extension POMs

Provide slf4j-api & jackson to extension modules. Fixes #6475

---

main/src/com/google/refine/ProjectManager.java
main/src/com/google/refine/history/History.java
main/src/com/google/refine/io/FileHistoryEntryManager.java
main/src/com/google/refine/io/FileProjectManager.java
main/src/com/google/refine/io/ProjectMetadataUtilities.java
main/src/com/google/refine/io/ProjectUtilities.java
main/src/com/google/refine/model/Column.java
main/src/com/google/refine/model/ColumnModel.java
main/src/com/google/refine/model/Project.java
main/src/com/google/refine/model/Recon.java
main/src/com/google/refine/model/ReconCandidate.java
main/src/com/google/refine/model/Row.java
main/src/com/google/refine/util/Pool.java
main/tests/server/src/com/google/refine/expr/functions/CrossTests.java
main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java

Fixes #6453
- improve error messages for various types of corruption
- don't automatically recreate missing directories at startup
- don't attempt to process null metadata entries
- extract magic strings into constants
- narrow Exception to IOException in error handling
The second commit and some of the cleanup in the first commit can be moved to a separate refactoring task if there's a need for a minimalist fix for 3.7.x or something else.

Fix project name lookup with missing metadata. Fixes #6453

---

main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index/default-importing-sources/import-from-computer-form.html
main/webapp/modules/core/scripts/index/default-importing-sources/sources.js
main/webapp/modules/core/styles/index/default-importing-sources.css

Added a new way to import files using drag and drop
Fixes #6250
Here is how the UI will look like after adding the drag and drop feature
Before dragging any file:
After dragging and dropping the files you need:
- Added new text below the choose files button
- Added a box to indicate the area to which the files will be dragged to
- Added some css to polish the look of this feature
- Modified some javascript to take the new file input feature into consideration

Added a new feature to import files using drag and drop. Requested in issue #6250

---

main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.html

Fixes #6351 
This change helps all input fields under the parsing options to accept any kind of number input format, such as "1,000" or "1 000".
- Adapt the "parseIntDefault" function to different localized numbers.
1. Remove the numbers after the decimal point
2. Extract all the numbers remained
3. Join them together

Deal with localized numbers. Fixes OpenRefine#6351

---

main/webapp/modules/core/scripts/views/data-table/cell-ui.js

This will let the next cell renderers attempt to render the cell instead of aborting the rendering of the entire grid.
For https://github.com/OpenRefine/CommonsExtension/issues/99.

Avoid crashing when a cell renderer throws an exception

---

main/src/com/google/refine/importers/SeparatorBasedImporter.java

Fixes #6516
* In cases where the Univocity guesser and our guesser disagree, return our separator guess rather than just punting.
* Also remove magic numbers and simplify.

Try harder to return separator guess. Fixes #6516

---

main/src/com/google/refine/io/FileProjectManager.java
main/src/com/google/refine/util/IOUtils.java

This avoids an unnecessary dependency from one of our core classes to the Apache POI library, which should only be relied on to support XLS(X) in importers/exporters.
Also deprecates some old utility functions which can be replaced by functionality from the JDK (since we require Java >= 11).

Remove dependency to POI in FileProjectManager

---

extensions/wikibase/pom.xml
extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/MediaFileUtilsTest.java

Adds function for uploading a file in chunks as described on https://www.mediawiki.org/wiki/API:Upload#Example_3:_Upload_file_in_chunks. The chunks are created as temporary files and are removed once uploaded.
For #4303

Upload files in chunks

---

extensions/database/pom.xml
extensions/gdata/pom.xml
extensions/jython/pom.xml
extensions/pc-axis/pom.xml
extensions/pom.xml
extensions/wikibase/pom.xml
main/pom.xml

Closes #6257.
I tested running it both from the development version (`./refine` in a git clone) and from the packaged version on Linux. Let's see if the CI agrees.
I'd be tempted to include this in 3.8 but because it is likely that this breaks some things, I'd make it another beta instead of releasing 3.8.0 already.

Package Java classes into jars

---

extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java

The threshold is 100,000,000 bytes for now to be below the upload limit for Wikimedia Commons, see
https://commons.wikimedia.org/wiki/Commons:Maximum_file_size. This makes sure that files are chunked if they can't otherwise be uploaded. The value is hard coded for now, but will be read from the manifest in a later patch.
For #4303

Use chunked uploading for files larger than a certain size

---

.github/workflows/pull_request_server.yml
.github/workflows/snapshot_release.yml
pom.xml

Fixes #6493
- Switch to standard Coveralls GitHub action
- Add Java version as job flag
- Remove old Maven plugin integration for Coveralls
Draft until I see if it works...

Switch to standard Coveralls action. Fixes #6493

---

extensions/wikibase/tests/src/org/openrefine/wikibase/testing/WikidataRefineTest.java
main/tests/server/src/com/google/refine/RefineTest.java

Those methods are only part of our test suite, the intention with deprecating them without deleting them was to cater for any in-flight PRs. The only affected PR #6461 is already using the new utilities.
Keeping them longer will block modularization.

tests: Remove createCSVProject utilities

---

main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java

This will be one of the things that the Maven modularization should be able to prevent.

tests: Remove dependency to Jena in FileProjectManagerTests

---

main/tests/server/src/com/google/refine/history/FileHistoryEntryManagerTests.java
main/tests/server/src/com/google/refine/history/HistoryEntryTests.java

Another change that's in the way of Maven modularization.
The HistoryEntry class will belong to the core Maven module, whereas the ColumnAdditionOperation class will be part of the module that implements all our standard operations, so to put the tests in the corresponding modules we need to remove the dependency from HistoryEntryTests to ColumnAdditionOperation.

tests: remove dependency of history entry tests to column addition operation

---

main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java

Moves two test cases implemented in StandardReconConfigTests which are actually testing ReconOperation to ReconOperationTests.

tests: move recon tests according to the class they actually test

---

packaging/pom.xml

- excludes oro dependency for license download (since it fails) during build

exclude oro license from trying to download

---

main/src/com/google/refine/LookupCacheManager.java
main/src/com/google/refine/browsing/facets/TextSearchFacet.java
main/src/com/google/refine/expr/ClojureParser.java
main/src/com/google/refine/expr/MetaParser.java
main/src/com/google/refine/expr/functions/Cross.java
main/src/com/google/refine/grel/Parser.java
main/src/com/google/refine/model/recon/ReconciledDataExtensionJob.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
main/webapp/modules/core/MOD-INF/controller.js

Migrates the registration of expression languages provided by default to the controller.js, and removes references to GREL from functionally independent areas.
This is a first step towards having GREL in its own Maven module.

Decouple expression languages from core infrastructure

---

main/src/com/google/refine/expr/functions/arrays/Join.java
main/src/com/google/refine/grel/controls/ForEachIndex.java
main/tests/server/src/com/google/refine/expr/functions/arrays/JoinTests.java
main/tests/server/src/com/google/refine/grel/controls/ForEachIndexTests.java

Fixes #6598 
- Fix NPE when `forEachIndex` is used with an array containing `null`s
- Make sure tests don't use `join()` which has broken handling for `null`s
Note: this is based off branch for PR #6605 so that should be review/merged first

Fix NullPointerException in forEachIndex

---

main/webapp/modules/core/scripts/util/dialog.js

Fixes #6602
- replace element attribute `aria-role=` with `role=`

Use correct WAI-ARIA role

---

main/src/com/google/refine/expr/MetaParser.java
main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/RangeFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/ScatterplotFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/TimeRangeFacetTests.java
main/tests/server/src/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
main/tests/server/src/com/google/refine/commands/expr/PreviewExpressionCommandTests.java
main/tests/server/src/com/google/refine/exporters/TemplatingExporterTests.java
main/tests/server/src/com/google/refine/grel/FunctionTests.java
main/tests/server/src/com/google/refine/grel/GrelTestBase.java
main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
main/tests/server/src/com/google/refine/operations/cell/MassOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowFlagOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowRemovalOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowStarOperationTests.java

This removes the final dependency from RefineTest to GREL by not registering GREL in it by default.
Instead, we register and unregister it in each test that relies on it.
~Draft because it depends on #6502 and #6571. Once those are merged, the diffs will be smaller.~

Remove grel registration from RefineTest

---

main/src/com/google/refine/importing/ImportingUtilities.java

Simplified the opening of tar archives by removing unnecessary check for the first entry and directly returning the `TarArchiveInputStream` in the `tryOpenAsArchive` method. Also updated the usage of deprecated `getNextTarEntry` to `getNextEntry` in ImportingUtilities.java.
Supports #5792

fix: Opening all files inside .tar.gz

---

extensions/wikibase/module/scripts/wikibase-manager.js
extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
extensions/wikibase/src/org/openrefine/wikibase/manifests/Manifest.java
extensions/wikibase/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperation.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperationTest.java

This falls back on editing with a non-versioned `openrefine` tag instead of `openrefine-${version}` by default, and on editing without a tag if `openrefine` isn't available.
Closes #6551.

wikibase: Better handling of the 'badtags' error

---

.github/dependabot.yml

This is an attempt to save a bit of computation time in the CI and group updates together, by batching dependency updates in weekly batches.
It would also mean a less crowded PR list and less such PRs to approve. I don't know if it's going to be workable, for instance if it's going to be easy to split the updates if the CI fails, but I propose we give it a try and see if we like it.
More info on this feature of dependabot:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

Group dependabot updates and reduce their frequency to weekly

---

main/tests/server/src/com/google/refine/RefineTest.java
main/tests/server/src/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
main/tests/server/src/com/google/refine/expr/functions/strings/PhoneticTests.java
main/tests/server/src/com/google/refine/grel/FunctionTests.java

This cuts the remaining inter-dependencies between GREL and core tests, preparing for the extraction of new Maven modules:
* a `core` module (which could also be named differently to avoid the confusion with the current `main`), containing the core classes defining OpenRefine's data model and main interfaces (what is a project, an operation, an importer, an expression language…). This module will have minimal dependencies to external libraries (such as Butterfly, Jackson and so on)
* a `grel` module which contains the implementation of our default expression language
The `main` module will then contain the implementation of the operations, importers, exporters (and so on) available by default in OpenRefine. This module will depend on the required external libraries to implement this …

tests: Final de-coupling between GREL and core tests

---

main/pom.xml
server/pom.xml

Fixes #6660 (see that issue for an explanation of the move).
This also explicitly adds other dependencies to the `server` module: those dependencies were in fact already pulled in (they are transitive dependencies of the module). The point of adding them to the pom file is to make sure we make the dependency on them explicit as we are (apparently) directly referring to some of their classes (so that we don't break if the transitive dependency chain is broken).

Move commons-lang3 dependency to the server module

---

main/src/com/google/refine/ClassResolver.java
main/src/com/google/refine/preference/PreferenceValue.java
main/tests/server/src/com/google/refine/ClassResolverTests.java

Follow-up of a discussion with @tfmorris.

Fix class mapping mechanism broken by the migration to Jackson

---

main/src/com/google/refine/clustering/binning/UserDefinedKeyer.java
main/src/com/google/refine/clustering/knn/UserDefinedDistance.java
main/src/com/google/refine/commands/browsing/ComputeClustersCommand.java
main/tests/server/src/com/google/refine/clustering/binning/KeyerTests.java
main/tests/server/src/com/google/refine/clustering/knn/DistanceTests.java

The first pr in the GSoC project #4301 
Changes in this pull request:
- Added `UserDefinedKeyer` class + unit tests for it
-  Added `UserDefinedDistance` class + unit tests for it

clustering: User defined distances and keyers

---

main/src/com/google/refine/importers/ImportingParserBase.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java

Fixes #6418
-  In the getFileSource method of the ImportingUtitilities file, use the fileName as the key to the getString method of the JsonUtilities instead of the url, so it returns the name of the file to be used instead of it's download url.
When the Excel importer will be invoked after downloading from the URL, the sheet selection logic will compare against the local filename rather than comparing against the original URL as it had been doing.

Solve Excel importing from URL problem Fixes #6418

---

main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/cell-buttons.cy.js
main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js

Fixes #6695.
- revert #6239 which forces the re-fetching and re-rendering of the entire grid
- add missing `cellUI` parameter to enable in-place rendering of the updated cell after a single match action
- add a Cypress regression test
I would like to backport this to 3.8.

Fix preservation of pagination when matching a single cell

---

pom.xml

- several other open source projects assign the role Developer Emeritus, which we should do properly for David to avoid confusion.

Update pom.xml Adding David as Developer Emeritus

---

main/resources/com/google/refine/grel/ControlEvalError.properties
main/src/com/google/refine/grel/controls/Filter.java
main/tests/server/src/com/google/refine/grel/controls/FilterTests.java

Filter class argument type mismatch
Fixes #6694 
- Filter class now returns proper error if the argument is invalid
- Updated Filter test for params validation

Fix type of error message returned by the Filter GREL control

---

GOVERNANCE.md

As part of my gradual off-boarding I propose that @tfmorris heads the release process for 3.9.
The release process is described here: https://openrefine.org/docs/technical-reference/version-release-process
I would transfer to him the credentials necessary to maintain the release pipeline (Google API credentials, Apple notarization, GPG keys…), so that he's operational on issues such as #6713

Change release manager to Tom

---

CONTRIBUTING.md

Fixes https://github.com/OpenRefine/openrefine.org/issues/326 
I removed the section about new distribution and fork based on the [March 14th, 2024, Advisory Committee](https://forum.openrefine.org/t/march-14th-2024-advisory-committee-only/1428) meeting and following the conversation on the forum.

Update CONTRIBUTING.md to remove mention of other distributions. 

---

extensions/database/module/scripts/index/database-import-controller.js
extensions/wikibase/module/scripts/dialogs/perform-edits-dialog.js
main/src/com/google/refine/browsing/Engine.java
main/src/com/google/refine/browsing/RecordVisitor.java
main/src/com/google/refine/browsing/RowVisitor.java
main/src/com/google/refine/browsing/facets/ScatterplotDrawingRowVisitor.java
main/src/com/google/refine/browsing/util/ConjunctiveFilteredRecords.java
main/src/com/google/refine/browsing/util/ConjunctiveFilteredRows.java
main/src/com/google/refine/browsing/util/RowVisitorAsRecordVisitor.java
main/src/com/google/refine/commands/row/GetRowsCommand.java
main/src/com/google/refine/sorting/SortingRecordVisitor.java
main/src/com/google/refine/sorting/SortingRowVisitor.java
main/tests/cypress/cypress/e2e/project/grid/viewpanel-header/pagination.cy.js
main/tests/server/src/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/langs/translation-es.json
main/webapp/modules/core/langs/translation-fr.json
main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.js
main/webapp/modules/core/scripts/dialogs/common-transform-dialog.js
main/webapp/modules/core/scripts/dialogs/expression-column-dialog.js
main/webapp/modules/core/scripts/index/default-importing-controller/controller.js
main/webapp/modules/core/scripts/project.js
main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

This is a backport of #5411 to the master branch. Closes #33, closes #570, closes #572 (already marked as such by #5411).
For this one, although the change was sort of forced on me by the new architecture, it can be backported with reasonable effort to the master branch.
**Summary:** this changes the grid pagination so that users to not input a page number, but the index of the first row in the view. Why do this?
* it solves #33 and others, because starting row number can be meaningfully preserved for all row-wise operations. In comparison, preserving the page number is not guaranteed to keep the view in the same place because changes to earlier rows can shift page boundaries
* it's generally a better practice for pagination, as is explained by various documents (such as …

Preserve pagination after actions which trigger a grid update

---

main/tests/cypress/cypress/e2e/create-project/preview_project.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.numeric.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/transpose/cell_accross_columns.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/transpose/columnize.cy.js
main/tests/cypress/cypress/support/commands.js
main/tests/cypress/cypress/support/e2e.js

Fixes #6747
- Fix the flaky numeric facet test by waiting for the slider to achieve the desired state rather than trying to catch a transient
- Remove all uses of the deprecated waitForImportUpdate
- Add support for debugging tests (developer feature)
- Remove dead code and clean up a few flagged warnings

Fix flaky Cypress tests

---

extensions/wikibase/module/langs/translation-en.json
extensions/wikibase/pom.xml
extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizer.java
extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/MediaFileUtilsTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizerTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/updates/MediaInfoEditTest.java

Issue: #4303. The following is planned to be added in this PR:

Upload files in chunks (#6510)

---

main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/tests/server/src/com/google/refine/importers/ImporterTest.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java

Fixes #6723 
- Increase TSV/CSV column limit to 32K (from 512)
- Make cryptic test assertion failures easier to understand

Increase TSV/CSV column limit to 32K (from 512). Fixes #6723

---

main/src/com/google/refine/commands/project/ExportRowsCommand.java

Fixes #6549
- don't percent encode period (.) or any other safe characters
- use upper case UTF-8 character set designator per spec
- construct a safe USASCII fallback filename
- for Safari browsers, send the filename as native UTF-8 without rfc5987 encoding since it doesn't support it

Clean up file export. Fixes #6549

---

main/webapp/modules/core/styles/index/default-importing-sources.css

Closes #6735.
The fix avoids the `65%` which was chosen to fix the text approximately as this value can depend on font size and ensures that the width of the containing element matches that of the file input.

fix: Positioning of drop placeholder for file import

---

CONTRIBUTING.md

Copy edit for consistency and more positive & welcoming tone (do this, not don't do that)
No issue, but related to PR #6725 
- test all links and fix several links which are either completely dead or point to wiki stub pages which point somewhere else
- change all headings to be action oriented
- rephrase prohibitions and warnings as positives (ie do it this way, not don't do it that way)
- add a category for peer support
- small grammar and spelling fixes throughout
There was a reference to clicking on the "Edit" button on the docs. I'm guessing that this is left over from the wiki and doesn't actually work on the web site. Anyone know for sure?

Update dead links and copy edit

---

main/tests/server/src/com/google/refine/clustering/binning/FingerprintKeyerTests.java
main/tests/server/src/com/google/refine/clustering/binning/UserDefinedKeyerTests.java

This separates `KeyerTests` into `UserDefinedKeyerTests` and `FingerprintKeyerTests` so that we keep the pattern of one test class per main class.
Required to rebase #6651 properly

Separate out UserDefinedKeyerTests

---

extensions/wikibase/tests/src/org/openrefine/wikibase/manifests/ManifestTest.java
main/tests/server/src/com/google/refine/ProjectManagerTests.java
main/tests/server/src/com/google/refine/expr/functions/strings/LevenshteinDistanceTest.java
main/tests/server/src/com/google/refine/expr/util/CalenderParserTest.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
main/tests/server/src/com/google/refine/importers/XmlImporterTests.java
packaging/THIRD-PARTY.txt

Fixes #6791
- migrates usages of org.junit.Assert to org.testng.Assert
- migrates usages of org.junit.assertThrows to TestNG annotations
- migrates some uses of org.testng.AssertJUnit.assertEquals to org.testng.Assert.assertEquals, swapping the order of parameters (unless they were in the wrong order to start with)
- adds TODOs for remaining uses of org.testng.AssertJUnit (which uses the JUnit parameter order)

Remove uses of JUnit. Fixes #6791.

---

extensions/wikibase/src/org/openrefine/wikibase/schema/WbDateConstant.java

Fixes #6774.
Migrates away from `SimpleDateFormat` which is known not to be thread-safe. The existing tests are hopefully sufficient to guarantee that behavior is preserved.

fix: Ensure thread safety of Wikibase date parsing

---

main/src/com/google/refine/importers/LineBasedFormatGuesser.java
main/src/com/google/refine/importing/ImportingUtilities.java
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java

File format info was not getting set when multiple files are uploaded.
Fixes #6772 
- Set format in the import flow for multiple files
- Identify format based on the file, added guessBetterFormat() method
- Tested with multiple file types the format is getting set correctly

File type detection fails when multiple files are imported at once

---

main/resources/com/google/refine/grel/EvalErrorMessage.properties
main/resources/com/google/refine/grel/FunctionDescription.properties
main/src/com/google/refine/expr/functions/arrays/Zip.java
main/src/com/google/refine/grel/ControlFunctionRegistry.java
main/tests/server/src/com/google/refine/expr/functions/arrays/ZipTests.java

Zip function addition to GREL
Fixes #5440 
- Zip function takes in a 2 or more Array parameters and generates output which is an Array of arrays 
- The length of the output will be that of the shortest input parameter
- Supports text, number, date
- Usage - zip(array 1, array 2, ...)
- Examples
1. zip( [1, 2], ["A", "B"] ) produces [ [ 1, "A" ], [ 2, "B" ] ]
2. zip( [1, 2], ["A", "B"] , [ now(), now() ] ) produces  [ 1, "A", "2024-08-01T09:24:02.063008Z" ], [ 2, "B", "2024-08-01T09:24:02.063017Z" ] ]

GREL Zip function

---

main/tests/cypress/cypress/e2e/project/grid/row/edit_cells.cy.js
main/webapp/modules/core/scripts/views/data-table/cell-ui.js

Fixes #6534 
The date entered in the cell is parsed using the `Date.parse()` method which returns a timestamp. This timestamp is converted to a formatted date string using `toString("YYYY-MM-DDTHH:mm:ss.sssZ")`.
but concerning the below link
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_radix
The `toString` method has an optional parameter radix, which should be an integer between 2 and 36. But here the radix is given a string as an argument.
- use `toISOString` method on a new Date object constructed using the parsed date value.

Fix Uncaught RangeError when using Cell Edit button to change String to Date data type.

---

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/add_columns_based_on_this_column.cy.js

Followup to #6825 (fix for #6824) which is triggering snapshot build failures even though it ran without issue in CI. :(
Looking at the (successful) CI logs, it appears that Clojure initialization takes pretty close to the default 4 sec timeout, which might cause the test to be flaky, depending on host machine & load, so adding 100% buffer to the timeout.

Increase timeout for Clojure initialization in test

---

main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.html

- Add user guide link to "Find out more" in clustering user hint

Add user guide link to "Find out more" in clustering user hint

---

extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java

Closes #6775.
Somehow, empty edits can be scheduled: this makes sure that they are caught and appropriately ignored.

wikibase: Fix NPE when empty edits are scheduled

---

main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java

Closes #6733. The problem was that the connection error was not that of the mocked response, but instead of the attempted retry made by our HTTP client, which was left stalling because no corresponding mocked response had been set up.
<s>Let's see if my assertion is generic enough because I suspect the error message might be platform-dependent.</s> It is indeed platform dependent now that the test is fixed, so I have removed the assertion on the specific error message and just check that some error message is returned.

Fix long-running test in StandardReconConfigTests

---

main/src/com/google/refine/importers/SeparatorBasedImporter.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java

Fixes #6691
- Turn on line separator detection for CSV/TSV import
- Also add test coverage for the CRLF case for Windows

Turn on line separator detection for CSV/TSV import. Fixes #6691

---

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/add_columns_based_on_this_column.cy.js
main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
main/tests/cypress/cypress/support/commands.js

Refs #6824. Improves on #6825.
- Refactor the tests so that there's only a single copy of the Python/Clojure selection code

Dry up Cypress Clojure/Python tests

---

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.numeric.cy.js
main/tests/cypress/cypress/support/commands.js

Fixes #6164 
- Usage of `waitForOrOperation()` helper function has been removed from cypress test.
- The helper function itself as well has been removed.
- In-between checks have been added to achieve waiting and to satisfy test conditions.
Steps taken before commit:
Final result:

fixes #6164 remove waitForOrOperation() usage and the helper itself

---

.gitattributes

For reasons I don't understand, source file line ending normalization was disabled in 9c7cbcb6 (without updating the associated comment). This PR reenables it so that we don't get PRs like the draft #6770 which have every single file listed as modified with whitespace (ie line ending) changes.

Restore line ending normalization

---

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java

Fixes #692 
- adds support for passing dates into and out of Jython
- includes tests for passing dates both directions
- simplifies sequence unwrapping
- add tests for sequences, ints, floats, strings

Add date handling to Jython.  Fixes #692

---

main/src/com/google/refine/commands/project/ExportRowsCommand.java
modules/core/src/main/java/com/google/refine/browsing/FilteredRows.java
modules/core/src/main/java/com/google/refine/commands/Command.java
modules/core/src/main/java/com/google/refine/commands/HttpUtilities.java
modules/core/src/main/java/com/google/refine/exporters/CustomizableTabularExporterUtilities.java
modules/core/src/main/java/com/google/refine/exporters/Exporter.java
modules/core/src/main/java/com/google/refine/exporters/StreamExporter.java
modules/core/src/main/java/com/google/refine/exporters/UrlExporter.java
modules/core/src/main/java/com/google/refine/exporters/WriterExporter.java
modules/core/src/main/java/com/google/refine/model/Project.java

Refs #6419.
This PR includes just the interfaces changes with no changes to the bundled exporters or tests to demonstrate 100% API compatibility:
- replace Properties with Map<String, String> in a new `export` method
- deprecate the old method
- add default implementations for both new and old signature
- add helper utilities
A followup PR based on the work by @karindev in #6460 will migrate the bundled exporters to use the new API. Until the deprecation period expires, exporters which support the new or old interface will continue to work unchanged.

Extend Exporter interfaces to phase out use of Properties

---

main/tests/cypress/package.json
main/tests/cypress/yarn.lock

No issue. Attempt to fix build failure.
This reverts commit b96ae694b66209417c23abf4fa471892f3781ce4.
It doesn't seem like it should be related, but see if his fixes the snapshot build failure during Javadoc generation.

Revert "Bump eslint in /main/tests/cypress in the cypress group (#6866)"

---

modules/core/src/main/java/com/google/refine/exporters/Exporter.java

For #6874.
This only fixes the linting error, not the broader fact that the PR workflow doesn't test javadoc generation and the snapshot release pipeline relies on it working.

Fix Javadoc error

---

main/webapp/modules/core/scripts/facets/facet.js
main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/facets/range-facet.js
main/webapp/modules/core/scripts/facets/scatterplot-facet.js
main/webapp/modules/core/scripts/facets/text-search-facet.js
main/webapp/modules/core/scripts/facets/timerange-facet.js
main/webapp/modules/core/scripts/project/browsing-engine.js
main/webapp/modules/core/scripts/project/process-panel.js

Fixes #6863 following the approach defined there.
A small refactoring was required, to separate out facet UI initialization from facet constructors, so that facets can be checked for duplicates before they appear onscsreen.
Not including a Cypress test because the corresponding operations are not covered in Cypress tests yet, because of their reliance on external services (there used to be a test of reconciliation which spun `reconcile-csv` locally but it was removed because it was flaky and required running the service separately for the test suite to pass).
The diffs shown by GitHub seem off, probably because of CRLF/LF differences (see #6841).

Avoid creating identical facets in reconciliation and Wikibase editing operations

---

main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java

During `mvn test` there's a failure for FetchURLs.
- Increases runOperation timeout from 3000ms to 10000ms in test `ColumnAdditionByFetchingURLsOperationTests`

Increase timeouts on Windows systems for FetchURLs test

---

main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/styles/views/data-table-view.css

Closes #4806. Backports #5840.
<s>Depends on #6546, therefore marked as draft until this one is merged.</s>

Resizeable columns

---

main/tests/cypress/cypress/e2e/create-project/preview_project.cy.js
main/tests/cypress/cypress/fixtures/food-blank-column.mini.csv
main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
main/tests/server/src/com/google/refine/importers/FixedWidthImporterTests.java
main/tests/server/src/com/google/refine/importers/ImporterUtilitiesTests.java
main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js
main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js
main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.js
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js
modules/core/src/main/java/com/google/refine/importers/ImporterUtilities.java
modules/core/src/main/java/com/google/refine/importers/TabularImportingParserBase.java
modules/core/src/main/java/com/google/refine/model/ColumnModel.java

Fixes #1750 
-  Determine whether a column is blank: (based on https://github.com/OpenRefine/OpenRefine/pull/3497): Create a new list<Boolean> in the TabularImportingParserBase class, that represents whether each column has data.
-  If the store blank column is false, delete this column (only happens when store blank column == false): removeColumn method is created in the ColumnModel class. This will use columns.remove(all empty columns), which will remove both data lines and header lines. 
- The checkbox of the store blank column added to the front-end page. After testing with real files (csv, xls, tsv), this function works. I think it should work on other Tabular files as well, since I'm optimizing directly in the TabularImportingParserBase class. …

Option to remove Blank Columns upon project creation

---

modules/core/src/main/java/com/google/refine/expr/Evaluable.java
modules/grel/pom.xml
modules/grel/src/main/java/com/google/refine/grel/ast/ControlCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FieldAccessorExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/OperatorCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/VariableExpr.java
modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
modules/grel/src/test/java/com/google/refine/grel/ast/ControlCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/ExprTestBase.java
modules/grel/src/test/java/com/google/refine/grel/ast/FieldAccessorExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/FunctionCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/LiteralExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/OperatorCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/VariableExprTest.java

This adds support for extracting the columns a GREL expression depends on.
This is a building block towards the support for analyzing the column dependencies of an operation, for instance to check that those columns exist in the project before applying the operation, or to visualize the dependencies of operations in a graph-based view.
As many static analysis tasks, the full problem is undecidable so this is meant to provide an approximation of it which is safe, meaning that if we succeed in extracting a set of columns for an expression, the expression is guaranteed not to rely on other columns. When the heuristics fail to return a set of columns, the expression may rely on any column.

Extract column dependencies of GREL expressions

---

extensions/gdata/module/scripts/index/importing-controller.js
main/src/com/google/refine/commands/row/GetRowsCommand.java
modules/core/src/main/java/com/google/refine/commands/Command.java

Fixes #6897 
- Switch Google extension to use JSON since JSONP has been removed from the GetRows command
- Attempt to provide useful error messages to callers who use JSONP with the GetRows command
-

Fix Google Data extension to use JSON instead of JSONP

---

extensions/wikibase/module/styles/dialogs/add-wikibase-dialog.css
extensions/wikibase/module/styles/dialogs/import-schema-dialog.css
extensions/wikibase/module/styles/dialogs/manage-account-dialog.css
extensions/wikibase/module/styles/dialogs/schema-management-dialog.css
extensions/wikibase/module/styles/schema-alignment.css
main/webapp/modules/core/styles/dialogs/expression-preview-dialog.css
main/webapp/modules/core/styles/project/sidebar.css
main/webapp/modules/core/styles/theme.css
main/webapp/modules/core/styles/views/data-table-view.css

Our color palette does not yet include a shade of red, which is the color we tend to use to report errors.
A lot of places in our CSS use `color: red`, but I assume that's primarily we "wanted to have this text in red" rather than asserting that `#ff0000` is the shade of red we want.
In e4bdca9c95f7645fb4e206031f73bd70e284bae3, @ostephens hasn't been as lazy as the rest of us and picked an explicit color, `#c51244` for errors reported in the facets area. So maybe it's a sensible choice? This PR uses it in all other places I could find via a new CSS variable. I'm happy with other values.

Unify shades of red used for errors

---

main/webapp/modules/core/scripts/views/data-table/menu-facets.js

When running the duplicates facet on a column with a backslash in the column name, the GREL expression which underpins the facet can be wrong as the backslash isn't correctly escaped.
Addresses https://github.com/OpenRefine/OpenRefine/security/code-scanning/29 (which is not publicly visible).

facets: Add missing backslash escaping in duplicate facet expression

---

modules/core/src/main/java/com/google/refine/io/FileProjectManager.java

So it doesn't spam the logs when OpenRefine is inactive:
```
10:45:14.353 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
10:50:14.354 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
10:55:14.354 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
11:00:14.355 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
11:05:14.356 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
11:10:14.356 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
11:15:14.357 [       FileProjectManager] Skipping unnecessary workspace save (300000ms)
```

core: Change log level of "Skipping unnecessary workspace save" message

---

main/tests/cypress/cypress/e2e/project/undo_redo/warn_for_history_deletion.cy.js
main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.js
main/webapp/modules/core/scripts/dialogs/common-transform-dialog.js
main/webapp/modules/core/scripts/dialogs/expression-column-dialog.js
main/webapp/modules/core/scripts/facets/list-facet.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js

Closes #6746.
Somehow I missed a lot of places where the callbacks to dismiss the operation dialog had to be moved to the `Refine.postCoreProcess` call. I am not sure how this went unnoticed, because I remember testing this manually…
I reviewed all calls of `Refine.postCoreProcess` and made the necessary changes.
When running an operation which is configured in a dialog, the new dialog warning against history overwriting is shown when the user validates the operation dialog. I realized that one could instead choose to display the warning when the operation dialog is first opened. This could be a follow-up change if we prefer this design.

ui: Fix dialog warning of history overwriting for some operations

---

main/webapp/modules/core/scripts/util/csrf.js

Fixes #6941
When adding CSRF protection to various new commands (for [GHSA-3jm4-c6qf-jrh3](https://github.com/OpenRefine/OpenRefine/security/advisories/GHSA-3jm4-c6qf-jrh3)), I set up the token passing by GET or POST parameter depending on the situation. Somehow this has led me to believe that the `postCSRF` utility should be adapted to append the CSRF token at the end of a URL with a `?` separator if it does not have any GET parameters yet. But in fact this method is exclusively used with POST and the string in question is never a full URL but the contents of the POST body, where no `?` is expected, so this was a mistake. The passing of CSRF tokens by GET is done by using `wrapCSRF` directly.

ui: Fix CSRF token fetching utility (and Wikibase login)

---

main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.js
main/webapp/modules/core/scripts/util/csrf.js

Follow-up to 090924c.
When writing 090924c, I thought it could be useful to return the jQuery request object created in the `wrapCSRF` utility so that it could be used for further chaining, such as adding error handling with the `.fail(…)` method.
That was a bad idea since this would bind the failure callback to the request that fetches a new CSRF token, not the one that actually does the POST request for which the token is fetched. Instead, the failure callback should be passed to the `postCSRF` / `wrapCSRF` method as last argument. I have reviewed all the places where those are used and made sure we don't rely on the return value.

csrf: Fix callback wiring-up for templating exporter

---

main/webapp/modules/core/scripts/util/csrf.js

Our CSRF tokens are valid for an hour, so it is not necessary to get a fresh token before every time we call a CSRF-protected command. This adds the necessary logic to remeber such tokens and invalidate them well before they expire. This saves a few HTTP requests.

ui: Avoid making unnecessary CSRF token requests

---

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js

Fixes #6940 
- Mimics correct user behavior with using mouse to hover over a facet choice and then edit|include appear
- Previous method used `invoke()` to forceably change css style, instead of correctly triggering jQuery list-facet.js events `mouseenter mouseleave` that will automatically handle visibility, as seen in our code snippet below.  So this improves testing the HTML as well as our JavaScript.
https://github.com/OpenRefine/OpenRefine/blob/dac141c2049e651ff63ac339639add5b7e02ba51/main/webapp/modules/core/scripts/facets/list-facet.js#L484-L490
Reference: https://github.com/cypress-io/cypress-example-recipes/blob/a2e24d19ec70c3fa8ae6a4a47574a239fc32c3e7/examples/testing-dom__hover-hidden-elements/cypress/e2e/hover-hidden-elements-spec.cy.js#L68

Fix flakyness for some Facet tests

---

.github/workflows/pull_request_e2e.yml
.github/workflows/snapshot_release.yml

Closes #6959.
I haven't invalidated the old token yet, it should be done after merging this PR. I believe existing PRs will then start using the new workflow, if not they can be rebased.

ci: Move Cypress record key to a GH Actions secret

---

server/src/com/google/refine/Refine.java

This change makes the client link printed to the terminal during startup clickable/selectable(in most terminals).
Most terminals(tested on a few Linux terminals) needs a protocol in front of links/ips to detect them.
No tested terminals supported a wildcard("//") protocol so this change assumes that one either serves OpenRefine over plain HTTP or that ones ones setup at least redirects plain HTTP calls.

Make the client link clickable in terminals

---

main/webapp/modules/core/MOD-INF/controller.js

This assigns CSS from each module into a different cascade layer while also ensuring that the "core" layer takes priority.
This makes it so that CSS from core got a higher priority than that of extensions. It does not eliminate extensions ability to write over core styles(they might use `!important`) and they can still change rules and defaults provided by the browser, but it makes it slightly harder accidentally break core styles.

Assign different cascade layers to CSS from different modules

---

extensions/wikibase/module/scripts/menu-bar-extension.js

Fixes #6977.
The problem was a race between the addition of the CSRF token to the form and its submission (I didn't realize this form was submitted immediately when I made the change).
It could be worth backporting this to 3.8 and releasing this as a 3.8.6, which would benefit from the Apple signing fix too.

Fix inclusion of CSRF token in QuickStatements export

---

main/webapp/modules/core/styles/dialogs/clustering-dialog.css

Fixes #6840
- Since grid-template-columns: repeat(4, auto); was already right in .clustering-dialog-control-row so no changes required
- padding and gap are changed to 0.25em both
- justify content was unnecessary

fix resultSummary div in Clustering dialog has unnecessary squishyness

---

extensions/wikibase/module/MOD-INF/controller.js
extensions/wikibase/module/scripts/wikibase-manager.js
extensions/wikibase/src/org/openrefine/wikibase/commands/FetchManifestCommand.java

This makes the backend proxy requests for Wikibase manifests to allow them to be hosted in MediaWiki itself(removing the CORS requirement).
MediaWiki hosted manifest example(Wikidata): https://www.wikidata.org/wiki/User:Abbe98/openrefine-manifest.json?action=raw
Setting this to draft for now but I would like to hear what others think about this approach before working out the details.

Wikibase: proxy manifest requests

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
modules/core/src/main/java/com/google/refine/model/AbstractOperation.java

Most operations don't check their parameters before execution, so when they are deserialized from invalid JSON payloads, this can lead to execution errors which ought to be prevented earlier.
This introduces a validate() method on operations giving them the opportunity to check the validity of their parameters. It would intuitively be more natural to do those checks in the operation constructors, as it would guarantee that if you have an instance of an operation, it has suitable parameters, but if we were to do this, we would run into the risk that deserializing operations fail at the loading of a project (for instance: say I use an extension which provides a custom expression language, which I then use in an operation. If I then remove the extension, I wouldn't be able to open my project …

Introduce AbstractOperation::validate() to check operation parameters

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java
main/webapp/modules/core/scripts/project/history-panel.js
main/webapp/modules/core/styles/project/sidebar.css

This adds error reporting to the apply-operations command, for things that are valid JSON but when that JSON does not correspond to a valid operation history (for instance `[{}]`).
This will still accept operations with missing parameters, such as:
```
[
{ "op": "core/mass-edit" }
]
```
Rejecting those sorts of inputs will be done in further PRs.

apply-operations: Report invalid JSON structure from the backend to the frontend

---

extensions/wikibase/module/langs/translation-en.json
extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/editing/MediaFileUtilsTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java

If there's a match for a file an upload request will be made. The response should contain warnings since the file would already exist. If the only warnings are "exists" and "duplicateversions" another request will be made with `ignorewarnings=1`. This will upload the file as a new version. Allowing these warnings means that you can upload a file with the same name as one that already exists even if the new file is that same as and older version.
An issue is shown when a new version is about to be uploaded to prevent this happening by mistake.
Fixes #5959

Allow uploading new file versions

---

GOVERNANCE.md

As mentioned [on the forum](https://forum.openrefine.org/t/transitioning-out-of-the-project/1879), I am in the process of reducing my involvement in OpenRefine. Leaving the advisory committee is one step of that process. I intend to continue development and other activities until the end of March, but I don't need to be in the committee for that.
Perhaps it would be worth thinking about onboarding new members on the advisory committee.
Documents to update

Antonin leaving the advisory committee

---

main/src/com/google/refine/commands/browsing/ComputeClustersCommand.java
main/tests/server/src/com/google/refine/commands/browsing/ComputeClustersCommandTests.java

@tfmorris pointed out that we have this use of `org.json` creeping again in the codebase. We migrated out of org.json years ago to Jackson, so it makes sense to keep relying on that only.
The dependency to org.json was made possible because a new version of odftoolkit depends on it, and there isn't any isolation of dependencies. We originally migrated out of org.json for licensing reasons, but the author has in the meantime re-licensed it as public domain dedication, so a priori it's fine to have it as a transitive dependency again.

fix: Remove usage of org.json in ComputeClustersCommand

---

.github/workflows/pull_request_server.yml

As `doclint=all` includes a lot of warnings for missing elements which are actually reasonable to omit,
see https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html.
Examples of the warnings silenced:
```
[WARNING] extensions/wikibase/src/org/openrefine/wikibase/utils/EntityCache.java:93: warning: no description for @param
[WARNING] * @param mediaWikiApiEndpoint
[WARNING] ^
[WARNING] extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/EnglishDescriptionScrutinizer.java:46: warning: no comment
[WARNING] protected void checkUppercase(LabeledStatementEntityEdit update, String descText) {
[WARNING] ^
```

ci: Silence spurious Javadoc warnings

---

extensions/database/src/com/google/refine/extension/database/DatabaseServiceException.java
extensions/database/src/com/google/refine/extension/database/mariadb/MariaDBConnectionManager.java
extensions/database/src/com/google/refine/extension/database/mariadb/MariaDBDatabaseService.java
extensions/database/src/com/google/refine/extension/database/mysql/MySQLConnectionManager.java
extensions/database/src/com/google/refine/extension/database/mysql/MySQLDatabaseService.java
extensions/database/src/com/google/refine/extension/database/pgsql/PgSQLConnectionManager.java
extensions/database/src/com/google/refine/extension/database/pgsql/PgSQLDatabaseService.java
extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteConnectionManager.java
extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseService.java

We currently have some flaky tests in the database extension:
```
Error:  com.google.refine.extension.database.sqlite.SQLiteDatabaseServiceTest.testGetRows -- Time elapsed: 0.016 s <<< FAILURE!
com.google.refine.extension.database.DatabaseServiceException: stmt pointer is closed
at com.google.refine.extension.database.sqlite.SQLiteDatabaseService.getRows(SQLiteDatabaseService.java:206)
at com.google.refine.extension.database.sqlite.SQLiteDatabaseServiceTest.testGetRows(SQLiteDatabaseServiceTest.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
```
To help debug …

database: Improve exception reporting, to debug flaky tests

---

main/src/com/google/refine/operations/cell/KeyValueColumnizeOperation.java
main/src/com/google/refine/operations/cell/MassEditOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellJoinOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java
main/src/com/google/refine/operations/cell/TextTransformOperation.java
main/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperation.java
main/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperation.java
main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
main/tests/server/src/com/google/refine/operations/cell/MassOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellJoinOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
main/tests/server/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperationTests.java
modules/core/src/main/java/com/google/refine/browsing/EngineConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/FacetConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/ListFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/RangeFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/ScatterplotFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TimeRangeFacet.java
modules/core/src/main/java/com/google/refine/operations/EngineDependentMassCellOperation.java
modules/core/src/main/java/com/google/refine/operations/EngineDependentOperation.java
modules/core/src/test/java/com/google/refine/RefineTest.java

This adds validate() methods for operations in the `com.google.refine.operations.cell` package.
It also introduces the required methods on `EngineConfig` and `FacetConfig` to do the validation there too.

operations: Implement validate() method for a first batch of classes

---

extensions/wikibase/tests/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperationTest.java
extensions/wikibase/tests/src/org/openrefine/wikibase/schema/WikibaseSchemaTest.java
main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowRemovalOperationTests.java
modules/core/src/main/java/com/google/refine/browsing/EngineConfig.java
modules/core/src/main/java/com/google/refine/commands/Command.java
modules/core/src/test/java/com/google/refine/browsing/EngineConfigTests.java

This method returns null when supplied with an invalid argument, which is bad practice. Instead of swallowing the exception and printing its stack trace, it should rather let the exception flow to the caller. Because fixing this behaviour would be a breaking change, I have deprecated the method and introduced a new one with the better behaviour. I have also introduced EngineConfig::defaultRowBased, as the reconstruct was overwhelmingly being used to build a default row-based engine configuration.

chore: Deprecate EngineConfig::reconstruct

---

extensions/database/tests/src/com/google/refine/extension/database/DatabaseImportControllerTest.java

This is a draft PR to debug the CI failure.
Eventually fixes #6935

database: Re-enable test that fails in the CI

---

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java
main/src/com/google/refine/expr/ClojureParser.java
modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
modules/core/src/main/java/com/google/refine/expr/Evaluable.java
modules/core/src/main/java/com/google/refine/expr/LanguageSpecificParser.java
modules/core/src/main/java/com/google/refine/expr/MetaParser.java
modules/core/src/test/java/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
modules/grel/src/main/java/com/google/refine/grel/Parser.java
modules/grel/src/main/java/com/google/refine/grel/ast/ArrayExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/BracketedExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/ControlCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FieldAccessorExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/GrelExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/OperatorCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/VariableExpr.java
modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
modules/grel/src/test/java/com/google/refine/grel/ast/ArrayExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/BracketedExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/ControlCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/FunctionCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/OperatorCallExprTest.java

As a preparation for introducing the ability to rewrite an `Evaluable` after a renaming of the columns it depends on, this introduces getters to enable representing the expression as text again after this rewrite.
This will in turn enable the rewrite of facet configurations and operations and their serialization in JSON (for instance for #133).

core: Introduce getSource() and getLanguagePrefix() on Evaluable

---

main/webapp/modules/core/scripts/util/menu.js
main/webapp/modules/core/styles/util/menu.css

This shouldn't make any difference to users, just simplifies/cleans up the DOM. (The only minor difference I am aware of on Firefox is that the right triangle gets downloaded only once and not requested every time a menu is opened, which seems to be a rather good thing!)
I also changed the introduction of the label to use `$.text()` instead of `$.html()`, which could break some extensions which rely on inserting custom HTML in menus, but makes us safe from special characters in translations of menu entries.

ui: Remove usage of table for layout in menu system

---

modules/core/src/main/java/com/google/refine/expr/Evaluable.java
modules/grel/src/main/java/com/google/refine/grel/ast/ArrayExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/BracketedExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/ControlCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FieldAccessorExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/GrelExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/OperatorCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/VariableExpr.java
modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
modules/grel/src/test/java/com/google/refine/grel/ast/ArrayExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/BracketedExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/ControlCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/ExprTestBase.java
modules/grel/src/test/java/com/google/refine/grel/ast/FieldAccessorExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/FunctionCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/LiteralExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/OperatorCallExprTest.java
modules/grel/src/test/java/com/google/refine/grel/ast/VariableExprTest.java

This adds support for transforming GREL expressions to adapt them after a column rename.
This interface is also made available to other expression languages, in a backwards compatible way thanks to a default implementation which treats all expressions as un-analyzable by default.
The goal is to make it possible to reliably adapt an history recipe to a new project when column names are different. Similar translation methods would be introduced on operation classes. It could also be useful to solve #133.

grel: Translate expressions after a column rename

---

main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/scripts/project/operation-icons.js

This PR makes it possible to associate icons to operations.
Those icons are meant to be added to menu items, dialog headers, history entries and more. They are meant to help users recognize operations visually, instead of relying on text. See [the forum topic about their design](https://forum.openrefine.org/t/operation-logos/1307).
Properly registering the logos and including them in the UI will follow.
There are surely many other ways to associate operations to icons (for instance, supplying the icon at the same time as providing the Java class for it), I am not particularly attached to this approach.

operations: Let core and extensions register icons

---

main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/RangeFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/ScatterplotFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/TextSearchFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/TimeRangeFacetTests.java
modules/core/src/main/java/com/google/refine/browsing/EngineConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/FacetConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/ListFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/RangeFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/ScatterplotFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TimeRangeFacet.java
modules/core/src/test/java/com/google/refine/browsing/EngineConfigTests.java

This adds a method of `FacetConfig` to extract column dependencies from a facet, and to `EngineConfig` to get the set of all columns referenced by facets.
This will then be used to expose a similar method on operation classes.
For #133. Follow-up to #6740.

facets: Add column dependency extraction

---

.github/workflows/pull_request_server.yml

Ref: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
GitHub Runners for Ubuntu have 4 cores.
Maven 3+ has experimental support for parallel builds https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3
I've tested locally on my Windows 11 PC with `mvn -T 8 clean package` and saw no issues, but instead a vastly faster build about 1/4 the time, since we already did a pretty good job of our multi-module project and declaring all the dependencies correctly, it's able to figure out what can run in parallel over the CPU cores I have (8 cores).
The other alternative is to use Maven Daemon (built with GraalVM and fast like Gradle) …

Use all 4 cores during build test for server

---

main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/src/com/google/refine/operations/column/ColumnAdditionOperation.java
main/src/com/google/refine/operations/column/ColumnMoveOperation.java
main/src/com/google/refine/operations/column/ColumnRemovalOperation.java
main/src/com/google/refine/operations/column/ColumnRenameOperation.java
main/src/com/google/refine/operations/column/ColumnReorderOperation.java
main/src/com/google/refine/operations/column/ColumnSplitOperation.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnMoveOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnRemovalOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnRenameOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnReorderOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnSplitOperationTests.java

Following up on #7024, continuing the implementation for other classes in the `com.google.refine.operations.column` package.

operations: Implement validate() method for c.g.r.o.column classes

---

extensions/wikibase/src/org/openrefine/wikibase/qa/EditInspector.java
extensions/wikibase/tests/src/org/openrefine/wikibase/qa/EditInspectorTest.java

Closes #7089.
This clarifies the filtering logic to select which entity ids should be fetched to get their labels, to avoid fetching them for entity ids generated via reconciliation. Those already have associated labels (existing label for existing entities, cell values for new entities).

wikibase: Fix label fetching in QA issues for new entities

---

.github/workflows/snapshot_release.yml

The GitHub Actions workflow that creates our release artifacts was not triggered when first creating a draft release and then publishing it. This fixes it.

ci: Run release workflow when a draft release is published

---

main/webapp/modules/core/images/operations/add-column.svg
main/webapp/modules/core/images/operations/blank-down.svg
main/webapp/modules/core/images/operations/cluster.svg
main/webapp/modules/core/images/operations/data-extension.svg
main/webapp/modules/core/images/operations/delete.svg
main/webapp/modules/core/images/operations/fetch-urls.svg
main/webapp/modules/core/images/operations/fill-down.svg
main/webapp/modules/core/images/operations/join-columns.svg
main/webapp/modules/core/images/operations/join-rows.svg
main/webapp/modules/core/images/operations/key-value-columnize.svg
main/webapp/modules/core/images/operations/magic-wand.svg
main/webapp/modules/core/images/operations/move-first.svg
main/webapp/modules/core/images/operations/move-last.svg
main/webapp/modules/core/images/operations/move-left.svg
main/webapp/modules/core/images/operations/move-right.svg
main/webapp/modules/core/images/operations/reconcile.svg
main/webapp/modules/core/images/operations/rename.svg
main/webapp/modules/core/images/operations/replace.svg
main/webapp/modules/core/images/operations/split-columns.svg
main/webapp/modules/core/images/operations/split-rows.svg
main/webapp/modules/core/images/operations/transform.svg
main/webapp/modules/core/images/operations/transpose-into-columns.svg
main/webapp/modules/core/images/operations/transpose-into-rows.svg
main/webapp/modules/core/scripts/project/operation-icons.js
main/webapp/modules/core/scripts/util/menu.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
main/webapp/modules/core/styles/util/menu.css

This adds icons to the column menu, with the aim:
* to help users identify menu items visually, rather than by reading text
* to help users better relate the menu entries to the history entries (once the icons will be made available there, which requires #7055), and then in the graphical representations of recipes
* open up the possibility to move out of the column menus, by integrating operations in a toolbar for instance
The icons are all made by me based on [the design proposed on the forum](https://forum.openrefine.org/t/operation-logos/1307). I have made a few tweaks, mostly to simplify the icons so that they are recognizable at the small scale needed to fit them in operation menus.
The icons can surely be improved further. I don't know what is the best place to discuss changes to …

Add icons to operations in column menu

---

main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/RangeFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/ScatterplotFacetTests.java
main/tests/server/src/com/google/refine/browsing/facets/TimeRangeFacetTests.java
main/tests/server/src/com/google/refine/commands/browsing/ComputeFacetsCommandTests.java
modules/core/src/main/java/com/google/refine/browsing/EngineConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/FacetConfig.java
modules/core/src/main/java/com/google/refine/browsing/facets/ListFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/RangeFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/ScatterplotFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
modules/core/src/main/java/com/google/refine/browsing/facets/TimeRangeFacet.java
modules/core/src/main/java/com/google/refine/expr/Evaluable.java
modules/core/src/test/java/com/google/refine/browsing/EngineConfigTests.java
modules/grel/src/test/java/com/google/refine/grel/GrelTests.java

For #133.
This doesn't just translate the columns to which the facets are applied, but also the expressions they rely on, in case other columns are mentioned there.
Beyond #133, this will then be used to offer similar functionality on operation classes, so that the column names referenced by a recipe (JSON representation of operation history) can be adapted when applying it. See the design discussions on the forum: https://forum.openrefine.org/t/column-selection-ui-for-applying-recipes/1998

facets: Add a ability to translate after a column rename

---

main/webapp/modules/core/scripts/dialogs/apply-operations-dialog.js

In Chrome-based browsers, the "Browse" button in the "Apply" dialog would open the file selection dialog twice when clicked.
This was because the file selection dialog was only set up after the first click. This PR simplifies that.
Discovered in a testing session with @thadguidry.

fix: Double opening of file selection in 'Apply' dialog

---

main/webapp/modules/core/langs/translation-en.json

In the dialog to apply a recipe, the confirmation button currently reads "Perform operations". In a testing session with @thadguidry, we realized "perform" has somewhat abstract / convoluted tones. @thadguidry suggested "Apply operations" or "Replay operations". I think "Run operations" is even simpler and more straightforward. What do you think?

ui: Use 'Run operations' instead of 'Perform operations' in Apply dialog

---

refine.bat

Fixes #7114
- exit properly if errors during calls to npm and mvn

Fixes #7114 make refine.bat exit on errors from external programs

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java

This PR introduces a simple algorithm to detect any missing columns referenced by a list of operations to be applied (currently supplied as JSON by the user in the "Apply" dialog).
This improves the error reporting in the dialog. Instead of applying each operation until an error is thrown (leaving the project in a state where the recipe has been half-applied), this makes it possible to report the missing column to the user without applying any operation. Later on, the same algorithm will be used to explicitly list those required columns in the UI, letting the user rename them on the fly.
The computation of the required columns is done by scanning the list of operations to be applied while maintaining a list of the column names required to be in the project at the current scanning state. …

history: Validate column dependencies of operations before applying them

---

main/src/com/google/refine/operations/cell/BlankDownOperation.java
main/src/com/google/refine/operations/cell/FillDownOperation.java
main/src/com/google/refine/operations/cell/KeyValueColumnizeOperation.java
main/src/com/google/refine/operations/cell/MassEditOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellJoinOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java
main/src/com/google/refine/operations/cell/TextTransformOperation.java
main/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperation.java
main/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperation.java
main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
main/tests/server/src/com/google/refine/operations/cell/MassOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellJoinOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
main/tests/server/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperationTests.java
modules/core/src/test/java/com/google/refine/RefineTest.java

Following up on #7056, this adds the column dependencies and diffs to all operations in the `com.google.refine.operations.cells` package.

operations: Expose column dependencies in c.g.r.o.cells

---

main/src/com/google/refine/operations/recon/ExtendDataOperation.java
main/src/com/google/refine/operations/recon/ReconClearSimilarCellsOperation.java
main/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperation.java
main/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperation.java
main/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperation.java
main/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperation.java
main/src/com/google/refine/operations/recon/ReconMatchBestCandidatesOperation.java
main/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperation.java
main/src/com/google/refine/operations/recon/ReconOperation.java
main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconClearSimilarCellsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMatchBestCandidatesOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconUseValuesAsIdsOperationTests.java
modules/core/src/main/java/com/google/refine/model/recon/ReconConfig.java
modules/core/src/main/java/com/google/refine/model/recon/StandardReconConfig.java
modules/core/src/test/java/com/google/refine/model/recon/StandardReconConfigTests.java

Following up on #7056, this adds the column dependencies and diffs to operations in the `com.google.refine.operations.recon` package.
The data extension operation does not expose anything yet: this will be tackled in a separate PR, as it requires adaptations to the operation metadata.

operations: Expose column dependencies in c.g.r.o.recon

---

main/src/com/google/refine/operations/row/RowAdditionOperation.java
main/src/com/google/refine/operations/row/RowFlagOperation.java
main/src/com/google/refine/operations/row/RowRemovalOperation.java
main/src/com/google/refine/operations/row/RowReorderOperation.java
main/src/com/google/refine/operations/row/RowStarOperation.java
main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowFlagOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowRemovalOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowReorderOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowStarOperationTests.java

Following up on #7056, this adds the column dependencies and diffs to all operations in the `com.google.refine.operations.rows` package.

operations: Expose column dependencies for c.g.r.o.rows

---

packaging/openrefine.iss

Fixes #7122.
See https://jrsoftware.org/ishelp/index.php?topic=installdeletesection for more details about this `[InstallDelete]` section.
Note: I haven't tried it out yet. I plan to check the behaviour of the installer once this is merged (since the installer will get built in the snapshot releases), because I don't have a Windows dev environment set up.

fix: Windows installer removes previous install

---

packaging/openrefine.iss

After reviewing the install process on Windows, I am proposing to stop offering to open the README file at the end of the process. The current experience feels pretty bad to me, for the following reasons:
* our README.md file has an `.md` extension, meaning that on my fresh Windows install, Windows doesn't know which program to use to open this file. I need to manually select a text editor (if I know that this is indeed the right choice). This is annoying because the checkbox to open the README at the end of the install process is ticked by default, so it will happen even if I didn't explicitly request it, in which case it is burdensome to look for a program to open a file that I don't actually want to open
* the contents of our README.md file are not adapted at all to Windows users. It …

windows: Don't offer to open the readme at the end of the installation

---

refine.bat

Fixes problem where if `refine.bat` is run from a dev environment or PS, that the `wmic` command is not found and doesn't provide free memory amount in megabytes.
```
PS E:\GitHubRepos\OpenRefine> ./refine
'wmic' is not recognized as an internal or external command,
operable program or batch file.
-------------------------------------------------------------------------------------------------
You have M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://openrefine.org/docs/manual/installing\#increasing-memory-allocation
-------------------------------------------------------------------------------------------------
Java 21 (21.0.5)
05:57:02.913 [ …
```

Fixes missing wmic command output running refine.bat if Powershell

---

modules/grel/src/main/java/com/google/refine/expr/functions/strings/Normalize.java
modules/grel/src/main/java/com/google/refine/grel/ControlFunctionRegistry.java
modules/grel/src/main/resources/com/google/refine/grel/FunctionDescription.properties
modules/grel/src/test/java/com/google/refine/expr/functions/strings/NormalizeTests.java

Fixes #6608 
- Made the normalize() public and accessible
- Modified the checkValue() in TextSearchFacet.java
- Introduced the junit tests for diacritic values

fixes #6608 - Expose diacritics normalization used in fingerprint()

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java
modules/core/src/main/java/com/google/refine/operations/Recipe.java
modules/core/src/test/java/com/google/refine/operations/RecipeTests.java

By introducing a `Recipe` class, we group together functionality that relates to lists of operations into a topical class.
This is a first step towards handling recipes in other contexts than `ApplyOperationsCommand`.

Introduce the Recipe class to hold a list of operations

---

main/webapp/modules/core/scripts/project/history-panel.html
main/webapp/modules/core/scripts/project/history-panel.js
main/webapp/modules/core/styles/project/sidebar.css

This changes the way history entries are highlighted when hovering one of them. So far, this was done with event listeners to maintain an absolutely positioned div which would add a special background color on the entries between the currently selected one and the hovered one. This simplifies it by removing that Javascript logic and defining the changes of background via CSS only. This relies on the [`:has()` pseudo-class](https://developer.mozilla.org/fr/docs/Web/CSS/:has), which is a recent CSS feature, but is available in "Baseline 2023".
This is a preparation for including operation icons in the history.
The behaviour remains unchanged as far as I can tell:
Tested on Firefox and Chromium.

Pure CSS alternative to highlighting history entries on hover

---

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
main/src/com/google/refine/operations/cell/MassEditOperation.java
main/src/com/google/refine/operations/cell/TextTransformOperation.java
main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/src/com/google/refine/operations/column/ColumnAdditionOperation.java
main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java
modules/core/src/main/java/com/google/refine/operations/Recipe.java

This improves the error messages shown in the "Apply" dialog so that they better indicate which operation failed validation. The error messages pertaining to invalid expressions are also more explicit, showing which expression is invalid.
As a follow-up improvement, those error messages could be displayed alongside the particular operation which raised the error. I prepared the ground for this improvement by exposing the operation index in the JSON serialization of the exception.

fix: Better error reporting in apply opertations dialog

---

modules/grel/src/main/java/com/google/refine/grel/Parser.java
modules/grel/src/main/java/com/google/refine/grel/Scanner.java
modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
modules/grel/src/test/java/com/google/refine/grel/ast/LiteralExprTest.java

Changing column names in GREL expressions relies on the ability to print back a parsed GREL evaluable to a string. This printing process was incorrect for regular expression literals such as `/.*/`, which it printed back as `.*` (missing the delimiters).
This fixes that, and also introduces the preservation of literals for string constants (whereas single quotes would be translated to double quotes earlier).

grel: More faithful pretty-printing for string and regex literals

---

main/src/com/google/refine/commands/recon/ExtendDataCommand.java
main/src/com/google/refine/operations/recon/ExtendDataOperation.java
main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
modules/core/src/main/java/com/google/refine/model/changes/DataExtensionChange.java

This makes it possible to control the names of the columns created by a data extension operation, using a new field in the operation metadata. The field is added in a backwards compatible way, meaning that operations which are missing that field will still be recognized and run as before.
By introducing this field, the goal is to make it possible to rename the columns created by this operation as part of the column renaming feature in the Apply dialog for recipes. Potentially, we could also expose this feature in the frontend, letting users change the name of the created columns when previewing the effect on the project.

operations: Improve data extension operation to control the created columm names

---

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/rename_remove_column.cy.js
main/tests/cypress/cypress/e2e/project/undo_redo/undo_redo.cy.js
main/tests/cypress/cypress/support/commands.js
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js

Fixes #6280 
**Status Quo**:
Currently the operations "Rename this column" and "Remove this column" are placed within the sub-menu "Edit column".
**Changes proposed in this pull request**:
Operations  "Rename this column" and "Remove this column" are placed within the main column menu.
Before             |  After
:-------------------------:|:-------------------------:
**Notes**:
* left out the corresponding icons of the actions to make the look more coherent 
(pattern is main menu -> no icon, sub-menu -> icon)
* shortened the operation names: "Remove ~this~ column" / "Rename ~this~ column"
While this was straight forward for rename operation as the text is only used once, I added another translation for remove column as the translation is also used in other places

move rename and remove column one menu up

---

main/src/com/google/refine/operations/cell/KeyValueColumnizeOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellJoinOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java
main/src/com/google/refine/operations/cell/TextTransformOperation.java
main/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperation.java
main/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperation.java
main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellJoinOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
main/tests/server/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperationTests.java

This adds support for updating the column names referenced in operations that are classified under the `com.google.refine.operations.cell` package, following up on #7132.

operations: Renaming support for c.g.r.o.cell

---

main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
main/src/com/google/refine/operations/column/ColumnMoveOperation.java
main/src/com/google/refine/operations/column/ColumnRemovalOperation.java
main/src/com/google/refine/operations/column/ColumnRenameOperation.java
main/src/com/google/refine/operations/column/ColumnReorderOperation.java
main/src/com/google/refine/operations/column/ColumnSplitOperation.java
main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnMoveOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnRemovalOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnRenameOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnReorderOperationTests.java
main/tests/server/src/com/google/refine/operations/column/ColumnSplitOperationTests.java

This adds support for updating the column names referenced in operations that are classified under the `com.google.refine.operations.column` package, following up on #7132.

operations: Renaming support for c.g.r.o.column

---

main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html

Fixes #6498
- remove the `width` attribute in the wikidata importer settings HTML to move the labels closer to the check boxes
Although the issue mentions a preference for moving away from using `table` to format the settings, I decided to leave the existing HTML as it's more consistent with the other settings HTML snippets. I think it makes more sense to track the migration of these snippets to more modern styles in a follow-up task.
I've attached a screenshot of the new settings. Given that `Disable auto preview` is below the `Update preview` button, I felt it made sense to leave the indentation for the final checkbox as-is, but I'd be happy to align the button and checkbox with the rest of the settings if others feel that is more appropriate.

fix: weird layout for wikitext importer

---

main/src/com/google/refine/commands/project/GetModelsCommand.java

Fixes #7175 
- This change catches a `ServletException` when looking up a project ID and returns an error. This leverages the existing client-side error-handling mechanisms to show users an error message if the project ID doesn't map to an existing project.
Attached is a screenshot showing the error message shown when loading an invalid or unknown project ID.

Fix infinite loading spinner for invalid or unknown project IDs

---

main/tests/server/src/com/google/refine/commands/history/GetHistoryCommandTests.java
main/webapp/modules/core/scripts/project/history-entry.html
main/webapp/modules/core/scripts/project/history-panel.js
main/webapp/modules/core/styles/project/sidebar.css
modules/core/src/main/java/com/google/refine/history/HistoryEntry.java
modules/core/src/test/java/com/google/refine/history/HistoryEntryTests.java
modules/core/src/test/java/com/google/refine/history/HistoryTests.java

- change the GetHistoryCommand to expose operation ids
- use those operation ids to show operation icons in the undo-redo panel
This requires #7134 to get the hovering behaviour to work correctly.
I'm not sure about the vertical alignment of the icons compared to the other descriptions. Currently they are centered, but perhaps it's better if their top boundaries are aligned.
Another question is whether step indices ("1. ", "2. "…) are really worth retaining. In my opinion they aren't very useful, I remember Zoe also proposed to remove them.
Another question is whether there should be an icon placeholder for steps which are either not associated to an operation (such as edits of single cells) or whose operation doesn't declare an icon. For now, the …

Show operation icons in history panel

---

main/src/com/google/refine/operations/recon/ReconClearSimilarCellsOperation.java
main/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperation.java
main/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperation.java
main/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperation.java
main/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperation.java
main/src/com/google/refine/operations/recon/ReconMatchBestCandidatesOperation.java
main/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperation.java
main/src/com/google/refine/operations/recon/ReconOperation.java
main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java
main/tests/server/src/com/google/refine/operations/recon/ReconClearSimilarCellsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMatchBestCandidatesOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
main/tests/server/src/com/google/refine/operations/recon/ReconUseValuesAsIdsOperationTests.java
modules/core/src/main/java/com/google/refine/model/recon/ReconConfig.java
modules/core/src/main/java/com/google/refine/model/recon/StandardReconConfig.java

This adds support for updating the column names referenced in operations that are classified under the `com.google.refine.operations.recon` package, following up on #7132.

operations: Renaming support for c.g.r.o.recon

---

main/src/com/google/refine/commands/history/GetColumnDependenciesCommand.java
main/tests/server/src/com/google/refine/commands/history/GetColumnDependenciesCommandTest.java

The GetColumnDependenciesCommand, which makes it possible to compute the list of columns required and produced by a recipe, is enhanced to expose the individual column dependencies of each operation mentioned in the recipe. This will make it possible to render a graphical visualization of those dependencies.

Expose annotated operations in GetColumnDependenciesCommand

---

modules/core/src/main/java/com/google/refine/util/OpenDirectoryUtilities.java

Fixes #7010
- Some Java installations come without support for graphics libraries, on which OpenRefine relies to open the file manager for actions like opening extensions and opening the workspace directory. This change will fall back to running shell commands to open the file manager if certain operations (such as `java.awt.Desktop.open`) are not supported.

fixes 7010: open file manager with headless Java

---

main/webapp/modules/core/scripts/views/data-table/data-table-view.js
main/webapp/modules/core/styles/views/data-table-view.css

Closes #7167.
This PR lets the name of the last column to expand to its full width. This is meant to improve the UX in two situations:
* if the grid is narrower than the screen, then it makes little sense to
cut off the last column name because there is free space afterwards,
so better let it expand
* if the grid is wider than the screen, then it is impossible to drag
the edge of the last column to the right, since there is no space on
the right. So better have the column expanded to show the full column
name too.
Also, this PR adds padding to the grid to make it possible to resize the last column, which still makes sense if we want to adapt the column width to better fit the contents of the column.
I will follow up with a toggle to expand / shrink all column headers, and improvements to …

Show all column headers in full by default

---

modules/core/src/main/java/com/google/refine/util/ParsingUtilities.java

Fixes #6680.
To be included in 3.9.1.
I didn't include a test because it would involve loading rather large strings, whose length would be quite arbitrary. But I manually checked that the fix enables the project attached in #6680 to load correctly.

fix: Disable maximum string length in Jackson

---

.gitattributes

This PR makes GitHub detect our Velocity files correctly, as a result they will have syntax highlighting and appear correctly in the languages statistics. 
Documentation:
- https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
- https://github.com/github-linguist/linguist/blob/1cc4b1a09f0bb64266386728966c1f839e386803/lib/linguist/languages.yml#L7832-L7844
**Changes proposed in this pull request:**
- Make GitHub syntax-highlight and index .vt files as Velocity templates

Make GitHub syntax highlight and index .vt files as Velocity templates

---

main/src/com/google/refine/commands/row/GetRowsCommand.java
main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
main/webapp/modules/core/scripts/views/data-table/data-table-view.js

Fixes #7207
- This change addresses how the "last" pagination navigation button sends the ending point. The current behavior is that it sends the index of the last row relative to a faceted search, and this change is to send the index of the absolute last row in the project.
- This also includes a change to omit the `nextPageStart` variable if there are fewer than `limit` elements in the response. This will cause the `next` and `last` pagination buttons to be marked as inactive, as there are no more elements to paginate through.

Send absolute row index in request when "last" pagination button is clicked

---

main/src/com/google/refine/operations/row/RowDuplicatesRemovalOperation.java
main/src/com/google/refine/operations/row/RowKeepMatchedOperation.java
main/tests/server/src/com/google/refine/operations/row/RowDuplicatesRemovalOperationTests.java
main/tests/server/src/com/google/refine/operations/row/RowKeepMatchedOperationTest.java

This adds support for the columnar analysis developed for the reproducibility project, for operations which were added since. This avoids those operations being treated as opaque, degrading the UX for recipes which rely on them.

Implement missing column dependencies and columns diff on new operations

---

main/src/com/google/refine/operations/cell/MultiValuedCellJoinOperation.java
main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellJoinOperationTests.java
main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java

When run on the first column of the project (which is also the one used to define the records), the operations to split or join multi-valued cells would fail to expose their columnar dependencies, because `Set.of(value1, value2)` throws an exception when `value1.equals(value2)`. This fixes it.

Fix: column dependencies in cell split/join operations

---

main/webapp/modules/core/scripts/util/dialog.js

This PR changes `aria-labeledby` to `aria-labelledby`.
I'm making this change because the `aria-labeledby` (with a single `l` in the middle) is the alternate spelling to the correct `aria-labelledby` (with two `l`s in the middle). The two `l`s version is preferred over the single `l` version. Some browsers will only respect the version with two `l`s. 
I discovered this repository by performing a code search for uses of `aria-labeledby` and sending PRs to replace them. (I'm not a bot but someone who is working on fixing this issue). For more on this you could read https://github.com/w3c/aria/issues/2093.

Use aria-labelledby over aria-labeledby

---

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java
main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
main/tests/cypress/cypress/support/commands.js

This addresses #3012, though I'm not sure if I can say it entirely fixes it.
- This change will catch a `PySyntaxError` when initializing a new `JythonEvaluable` object and will return the string "Syntax error" instead of the current "Internal error". It is a small change but I feel it is at least somewhat more helpful in guiding the user towards resolving the issue.
This is the existing error message:
And this is the error message after this change:
I realize this is a relatively small change, so please feel free to reject if you think it's unhelpful, but I feel it at least distinguishes between an internal error specific to OpenRefine and an error that a user could potentially resolve on their own.

Identify syntax errors in Python expressions

---

main/resources/com/google/refine/operations/OperationDescription.properties
main/src/com/google/refine/operations/column/ColumnMultiRemovalOperation.java
main/tests/server/src/com/google/refine/operations/column/ColumnMultiRemovalOperationTests.java
main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/scripts/project/operation-icons.js

For #5576 (but doesn't fix it yet).
This PR introduces a new operation which can remove multiple columns in one go. The columns to be removed are named in the operation metadata. This is meant to provide an alternative to the column reorder operation, where only the retained columns are mentioned in the operation metadata.
Instead of generalizing the existing `column-removal` operation, I have introduced a new class, so that there aren't any breaking changes.
The operation cannot be triggered from the UI yet.

Add operation to remove multiple columns in one step

---

main/src/com/google/refine/importers/SeparatorBasedImporter.java

Since [the current limit seems too low](https://forum.openrefine.org/t/errors-length-of-parsed-input-32769-exceeds-the-maximum-number-of-characters-defined-in-your-parser-settings-32768/2180/3), I think it's worth bumping this up. This makes it possible to store 1 million characters in each cell, which seems ample.

Increase limit for CSV cell size

---

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java
main/src/com/google/refine/clustering/binning/UserDefinedKeyer.java
main/src/com/google/refine/clustering/knn/UserDefinedDistance.java
main/src/com/google/refine/expr/ClojureParser.java
main/tests/server/src/com/google/refine/clustering/binning/UserDefinedKeyerTests.java
main/tests/server/src/com/google/refine/clustering/knn/DistanceTests.java
main/tests/server/src/com/google/refine/expr/ClojureParserTest.java
main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.js
main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.js

Fixes #7234 
In #6612 we introduced custom clustering functions.
But with non-GREL expressions like Jython and Clojure the clustering failed on multiple levels.
1. Several post requests in the new clustering dialogs were missing csrf tokens.
2. Several post requests did only sent the plain expression without the language code.
3. The GREL language code was hard coded in `UserDefinedKeyer.java` and `UserDefinedDistance.java`.
4. The new variables `value1` and `value2` were not made available in Jython and Clojure expressions.
The last one is probably the most problematic.
In GREL all variables in `bindings` are basically available as globals. But in Jython and Clojure we encapsulate the expressions in functions and only pass certain variables as parameters (`value, cell, cells, row, …

Enable custom clustering for non-GREL expressions

---

main/src/com/google/refine/operations/row/RowAdditionOperation.java
main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
modules/core/src/main/java/com/google/refine/model/Cell.java
modules/core/src/main/java/com/google/refine/model/Row.java
modules/core/src/main/java/com/google/refine/model/changes/RowAdditionChange.java
modules/core/src/test/java/com/google/refine/model/CellTests.java
modules/core/src/test/java/com/google/refine/model/RowTests.java
modules/core/src/test/java/com/google/refine/model/changes/RowAdditionChangeTests.java

Fixes #7245.
See [my comment](https://github.com/OpenRefine/OpenRefine/issues/7245#issuecomment-2780552271) for an explanation of the root cause of the issue.
To fix it, I have:
* made sure that the operation doesn't add its own list of rows to the project, but a copy of it, so that its metadata remains unchanged when further changes happen to the grid
* introduced a new serialization format for the operation. The goal with this move is to make sure that we are able to deserialize all values that have already made it into people's workspaces. Using the fact that the row addition operation only lets the user add empty rows for now, I change the deserialization code so that the `rows` parameter of the operation is parsed as a generic array, and only its length is taken into account to …

Fix deserialization of RowAdditionOperation.

---

main/src/com/google/refine/operations/row/RowAdditionOperation.java
main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java

I realized that the serialization and deserialization code of RowAdditionOperation were inconsistent: the index at which the rows should be inserted was called `index` in serialization, but `insertionIndex` in deserialization.
This fixes deserialization. Since any serialized versions of this operation in workspaces will use the `index` field, there shouldn't be any need to keep supporting `insertionIndex`.
This PR conflicts with #7224: depending on which one gets merged first, the other one will need to be adapted to change the frontend to submit `index` instead of `insertionIndex`.

fix: JSON deserialization of RowAdditionOperation

---

main/src/com/google/refine/operations/row/RowAdditionOperation.java
main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
modules/core/src/main/java/com/google/refine/model/Cell.java
modules/core/src/main/java/com/google/refine/model/Row.java
modules/core/src/main/java/com/google/refine/model/changes/RowAdditionChange.java
modules/core/src/test/java/com/google/refine/model/CellTests.java
modules/core/src/test/java/com/google/refine/model/RowTests.java
modules/core/src/test/java/com/google/refine/model/changes/RowAdditionChangeTests.java

Fixes #7245 on branch `3.9`.
Cherry-picked from 1f9d248e3d641ea2509b83909573f375a04e72b8 (PR #7247)

Backport: Fix deserialization of RowAdditionOperation

---

main/tests/cypress/cypress/e2e/project/grid/all-column/collapse_all.cy.js
main/tests/cypress/cypress/e2e/project/grid/all-column/view.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/view/collapse.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/view/collapse_left.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/view/collapse_right.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/view/expand-left.cy.js
main/tests/cypress/cypress/e2e/project/grid/column/view/expand-right.cy.js

- This aligns the cypress tests with the language updates made in #7193. I don't think the cypress tests run automatically on pull requests that update the language files, which might explain why these failures weren't noticed before merging the PR.

Resolve cypress test failures from language updates

---

GOVERNANCE.md

As I am transitioning out of the project, I'd like to pass on the release manager hat.
Rory, feel free to reach out if you need any sort of help, I intend to remain reachable in the coming months.
On a similar note, I will no longer feel responsible for keeping the PR backlog under control, so I encourage you to merge things :) For that also, if you are unsure about something in a PR, feel free to request my review, I will be happy to give opinions :)

Change release manager to Rory

---

main/webapp/modules/core/MOD-INF/controller.js
main/webapp/modules/core/images/facets/list.svg
main/webapp/modules/core/images/facets/range.svg
main/webapp/modules/core/images/facets/scatterplot.svg
main/webapp/modules/core/images/facets/text.svg
main/webapp/modules/core/images/facets/timerange.svg
main/webapp/modules/core/scripts/project/facet-icons.js
main/webapp/modules/core/scripts/views/data-table/menu-facets.js

For #7074.
I'm also thinking that the icons defined here could be used in the visualization, to make it clearer which filters are applied on each operation, but I don't have a precise idea of how that could work yet.

Introduce icons for facet types

---

extensions/wikibase/module/scripts/preview-tab.html
extensions/wikibase/module/scripts/schema-alignment.js
extensions/wikibase/module/styles/schema-alignment.css

closes #6305 
After checking edits in the preview tab, user has to go through the extension menu to upload them (see issue description)
- adds a button directly at the top of the preview tab that refers to the same functionality as directly selecting "Upload edits to Wikibase..." in the extension's dropdown menu
Before:
After:
_Note_:
the CSS for `#schema-preview-divided-header` (max-width & padding) corresponds to the CSS for `schema-alignment-dialog-preview` so both elements align

add upload button to preview tab

---

main/webapp/modules/core/scripts/project.js

So far the operations were listed simply with their description, not their icon. This introduces the icons as shown below.

Add operation icons to the dialog warning of history erasure

---

extensions/wikibase/module/images/wikibase-black-icon.svg
extensions/wikibase/module/images/wikibase-upload-icon.svg
extensions/wikibase/module/scripts/menu-bar-extension.js

So far, Wikibase-related operations didn't have associated icons. This fixes it.

wikibase: Add operation icons

---

extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/EnglishDescriptionScrutinizer.java

Those were inconsistent with the translation files, meaning that the messages would get displayed as translation keys in the UI.

wikibase: Fix translation keys of English description issues

---

main/webapp/modules/core/scripts/util/dialog.js

This is a proposal to annotate our frontend extension points with JSDoc annotations. This PR currently illustrates this by annotating the `DialogSystem`.
**Why**
First and for most this would make it clearer to us which interfaces are public, we already have a naming convention and we are good at catching & avoiding breaking changes, however, we are less good at making sure we don't extend these more than intended. By making our interfaces explicit with JSDoc we would avoid this.
Secondly, we will be able to mark JS extension points as deprecated.
Thirdly, JSDoc is supported by a lot of language servers and IDEs which will provide both extension and core developers with inline documentation, hints, and autocomplete features.
Fourthly (but out-of-scope for my own commitment) we could maybe …

Proposal: Add JSDoc annotations to JavaScript extension points

---

main/webapp/modules/core/index.vt
main/webapp/modules/core/langs/translation-en.json
main/webapp/modules/core/scripts/index.js
main/webapp/modules/core/styles/index.css

This change makes it possibly for users to copy detailed version and system information by clicking the version on the index page.
Example clipboard contents:
```
3.9-SNAPSHOT [TRUNK]
OpenJDK Runtime Environment 21.0.4+7
OpenJDK 64-Bit Server VM 21.0.4+7
Modules: command-palette, core, database, jython, module, pc-axis, wikidata
Client user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
```

Make it possibly for users to quickly copy system and version information

---

main/webapp/modules/core/scripts/util/dom.js

I kinda want to deprecate `getVPaddings` and `getHPaddings` given their confusing naming and extensions ability to do the same natively(or bypassing the entire thing with modern CSS). However, for now even our bundled extensions use them.

docs: add jsdoc annotations to DOM utilities

---

modules/core/src/main/java/com/google/refine/importers/ImportingParserBase.java
modules/core/src/main/java/com/google/refine/importers/tree/TreeImportingParserBase.java

Issue 7319 resolved
Fixes #7319
This change adds a condition to avoid unnecessary looping over project rows if both archiveColumnIndex and filenameColumnIndex are not set. Improves performance as suggested in issue #7319.

Fix: Add check before looping over archive/filename columns (#7319)

---

.github/workflows/snapshot_release.yml
pom.xml

This addresses #7390, but may not be a complete solution, but it's a starting point.
-  Change the server ID from ossrh to ossrh-staging-api
-  Switch URLs from oss.sonatype.org to ossrh-staging-api.sonatype.com
I suspect this will fail due to the use of the OSSRH token, but we'll see ...

Switch to OSSRH Staging API. Refs #7390

---

refine

This fixes the following warning when starting OpenRefine manually in the console:
```console
egrep: warning: egrep is obsolescent; using grep -E
```
Fixes #7404
- Use `grep -E` instead of `egrep` in the `refine` helper script

refine: use grep -E instead of egrep

---

extensions/wikibase/module/scripts/menu-bar-extension.js
main/webapp/modules/core/scripts/project/exporters.js

Prior to this change one would extend the export menu by pushing directly to an array. This comes with several issues:
- The interface isn't actually controlled by us and is incredibly large.
- We can't document the interface in a structured way(with for example JSDoc).
- Extensions ability to modify the menu isn't limited.
This change does not break existing interfaces as the underlying array  is untouched. Some extensions do more than pushing to the array, however, that could be considered a side effect of the interface rather than an intended feature. If there are legitime use-cases beyond pushing additional extension points could be added.

ExporterManager: add an explicite extension point

---

extensions/database/src/com/google/refine/extension/database/DBQueryResultImportReader.java
extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
extensions/database/src/com/google/refine/extension/database/DatabaseService.java
extensions/database/tests/src/com/google/refine/extension/database/DatabaseServiceTest.java
main/webapp/modules/core/scripts/index/create-project-progress-panel.html
main/webapp/modules/core/scripts/index/create-project-ui.js

Fixes #6654 
**Problem**:
DB import uses a counter instead of percentage to track its progress (see corresponding issue)
**Changes proposed in this pull request:**
- before starting the db import, we query the db for the `COUNT(*)` of the specified query, similar to the existing functionality for querying batches using `LIMIT` and `OFFSET`
- case count available: 
we use the total count and an additional counter variable to track progress of the db import and calculate the percentage for the UI
- case count not available:
(e.g. query failed or an extension uses constructor of `DBQueryResultImportReader` that does not include count) then we switch to not showing the progress bar but a spinner instead.
In any case we additionally add the absolute progress "(currentcount / totalCount)" to …

fix db import progress updates

---

main/src/com/google/refine/commands/project/ExportRowsCommand.java
main/src/com/google/refine/exporters/XlsExporter.java
main/src/com/google/refine/exporters/sql/SqlExporterException.java
main/tests/cypress/cypress/e2e/project/project-header/export_project.cy.js
main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java
main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java
modules/core/src/main/java/com/google/refine/exporters/ExporterException.java

Fixes #7368. Fixes #352. Refs #351
This includes a fix for the specific XLS row limit exceeded error (#7368) as well as better error reporting for exporters in general, which we seem to have broken sometime in the recent past. It also fixes #352 (silent truncation of large cells) and provides a better fix for #351 (almost silent truncation of sheets with too many columns).
1. Fix exporter error handling
-  Fix HTTP response headers for error case, so HTML error page gets rendered again. This could be improved, but at least restores the previous behavior.
- Refactor `ExportRowsCommand` so that it doesn't have SQL exporter specific handing by introducing `ExporterException`, which it handles and making SQL exception a subclass of it
- remove obsolete CSRF comment (unrelated non-functional …

Restore exporter error reporting and clean up XLS/XLSX error handling

---

pom.xml

Replaces #7427
Fixes [CVE-2024-9823](https://nvd.nist.gov/vuln/detail/CVE-2024-9823)

Update Jetty to 10.0.19
