OpenRefine/OpenRefine

main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js, main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html
Fix the "on error" label:
https://github.com/OpenRefine/OpenRefine/issues/980
=> to fix the ticket #980

main/webapp/modules/core/scripts/index/default-importing-controller/controller.js
fix issue #540 to skip the empty URL when submit the import form
=> fix issue #540 to skip the empty URL when submit the import form

extensions/jython/module/MOD-INF/controller.js, extensions/jython/module/MOD-INF/module.properties, main/src/com/google/refine/expr/MetaParser.java
=> fix issue #995

main/src/com/google/refine/importers/ExcelImporter.java, main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js
=> Fixed #1046 Combine xls and xlsx formats by inspecting file header information in ExcelImporter

server/src/com/google/refine/Refine.java
fix issue #873 2.6-beta1 does not open browser tab on start on a Mac
=> fix issue #873 2.6-beta1 does not open browser tab on start on a Mac

main/webapp/modules/core/langs/translation-es.json
=> ES translation updated

main/webapp/modules/core/scripts/dialogs/clustering-dialog.html, main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
Hello. I fixed bug.
Select Japanese lang and, when change keying functions on cluster dialog, it does not working.
So I changed for sending value to server from option tag text to option attribute value.
Thanks.
=> fix not working clustering functions when it select japanese lang.

broker/core/src/com/google/refine/broker/RefineBroker.java, extensions/jython/src/com/google/refine/jython/JythonEvaluable.java, main/src/com/google/refine/InterProjectModel.java, main/src/com/google/refine/browsing/Engine.java, main/src/com/google/refine/browsing/util/ConjunctiveFilteredRows.java, main/src/com/google/refine/clustering/binning/BinningClusterer.java, main/src/com/google/refine/clustering/binning/NGramFingerprintKeyer.java, main/src/com/google/refine/commands/project/CreateProjectCommand.java, main/src/com/google/refine/expr/ExpressionUtils.java, main/src/com/google/refine/expr/functions/strings/NGramFingerprint.java, main/src/com/google/refine/importers/FixedWidthImporter.java, main/src/com/google/refine/importers/SeparatorBasedImporter.java, main/src/com/google/refine/importers/tree/ImportRecord.java, main/src/com/google/refine/importing/DefaultImportingController.java, main/src/com/google/refine/importing/ImportingJob.java, main/src/com/google/refine/importing/ImportingUtilities.java, main/src/com/google/refine/model/changes/ColumnReorderChange.java, main/src/com/google/refine/oauth/OAuthUtilities.java, main/src/com/google/refine/operations/EngineDependentMassCellOperation.java, main/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperation.java, main/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperation.java, main/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperation.java, main/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperation.java, main/src/com/google/refine/operations/row/RowFlagOperation.java, main/src/com/google/refine/operations/row/RowStarOperation.java, main/src/com/google/refine/process/ProcessManager.java, main/src/com/google/refine/templating/Parser.java, main/tests/server/src/com/google/refine/tests/importers/ImporterUtilitiesTests.java, main/tests/server/src/com/google/refine/tests/model/changes/MassChangeTests.java
Sending the prior pull request to the new branch
=> (refactor) some opportunities to use the Diamond-operator

main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java, main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java
Closes #1219. Comes with a regression test.
=> Ensure null values are not cached in URL fetching operation.

main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/dialogs/extend-data-preview-dialog.js, main/webapp/modules/core/scripts/views/data-table/extend-data-preview-dialog.html
- removed mention to a missing .less file
- fixed the position of the Reset button in the preview dialog
- fixed the error for empty property selections
=> Small fixes to the data extension interface

.classpath, extensions/jython/.classpath
Related to #1236.
I have no idea why this breaks the URL caching test (this is seemingly unrelated). This should be fixed before merging.
=> Update Jython to 1.7.1.

main/webapp/modules/core/scripts/index.js
=> Alert user if more recent version available from github

main/src/com/google/refine/clustering/binning/FingerprintKeyer.java, main/tests/server/src/com/google/refine/tests/clustering/binning/KeyerTests.java
This closes #1256.
When merged, remember to update the docs:
https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth#fingerprint
=> Perform ASCII normalization earlier in FingerprintKeyer.

licenses/recurser_jquery-i18n.LICENSE.txt
Added recurser/jquery-i18n licence as per #1279
=> Added missing licence for jquery-i18n

main/src/com/google/refine/InterProjectModel.java, main/src/com/google/refine/expr/functions/Cross.java, main/tests/server/src/com/google/refine/tests/expr/functions/CrossFunctionTests.java
=> Extend cross() function to support multiple-value-cell-input

main/src/com/google/refine/InterProjectModel.java, main/src/com/google/refine/expr/functions/Cross.java, main/tests/server/src/com/google/refine/tests/expr/functions/CrossFunctionTests.java
Reverts OpenRefine/OpenRefine#1290 so that team can review more thoroughly.
=> Revert "Extend cross() function to support multiple-value-cell-input"

main/src/com/google/refine/commands/lang/GetLanguagesCommand.java
=> Ignore empty language files introduced by Weblate

main/src/com/google/refine/importers/WikitextImporter.java, main/src/com/google/refine/model/recon/StandardReconConfig.java, main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/scripts/index/open-project-ui.js, main/webapp/modules/core/scripts/preferences.js, main/webapp/modules/core/styles/index/open-project-ui.less
@thadguidry This is to fix the bug you found today that the index page will be blank after creating the userMetadata from the preference page.
=> check if the project has the userMetadata

main/tests/server/src/com/google/refine/tests/operations/cell/JoinMultiValuedCellsTests.java
Increasing test coverage and also ensuring that this function works as expected (see #1113)
=> Add tests for JoinMultiValuedCells

main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html, refine, refine.bat
=> to adjust the width of transform dialog. issue #1332

main/src/com/google/refine/ProjectManager.java, main/src/com/google/refine/commands/row/GetRowsCommand.java, main/src/com/google/refine/io/FileProjectManager.java, main/webapp/modules/core/scripts/index/edit-metadata-dialog.js, main/webapp/modules/core/scripts/index/open-project-ui.js
Will NOT change the auto  save strategy for project. instead will refresh the meta data
=> fix the row count refresh issue

main/src/com/google/refine/process/LongRunningProcess.java, main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java
Tried lots of ways on Appveyor, turns out Appveyor's network cannot reach that web site.  Added the check also to log the error in the cell.
=> fix Issue #1389

main/src/com/google/refine/util/ParsingUtilities.java, main/tests/server/src/com/google/refine/tests/util/ParsingUtilitiesTests.java
=> Fix Issue #1386

.gitignore, extensions/jython/.gitignore, extensions/sample/.gitignore
=> Split .gitignore by extension

main/webapp/modules/core/externals/suggest/suggest-4_3.js
=> Fix URI encoding of flyout parameters

main/tests/data/nobel-prize-winners.csv
This PR fixes spelling details in the CSV data.
=> Nobel prize winners CSV data typos

main/src/com/google/refine/commands/HttpHeadersSupport.java, main/src/com/google/refine/commands/column/AddColumnByFetchingURLsCommand.java, main/src/com/google/refine/commands/project/GetModelsCommand.java, main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java, main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java, main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/dialogs/http-headers-dialog.html, main/webapp/modules/core/scripts/dialogs/http-headers-dialog.js, main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html, main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js, main/webapp/modules/core/styles/common.less, main/webapp/modules/core/styles/views/data-table-view.less
Support setting http headers when using "Add column by fetching URL"
=> Set http req headers

main/webapp/modules/core/scripts/dialogs/extend-data-preview-dialog.js, main/webapp/modules/core/styles/reconciliation/extend-data-preview-dialog.less
=> Fix overflow issue in data extension dialog

openrefine-beam/.gitignore, openrefine-beam/README.md, openrefine-beam/pom.xml, openrefine-beam/src/main/java/com/google/refine/Jsonizable.java, openrefine-beam/src/main/java/com/google/refine/beam/operations/AddColumnFn.java, openrefine-beam/src/main/java/com/google/refine/beam/operations/ExpressionHandler.java, openrefine-beam/src/main/java/com/google/refine/util/ParsingUtilities.java, openrefine-beam/src/test/java/com/google/refine/beam/operations/AddColumnOperationTest.java, openrefine-beam/src/test/resources/log4j.properties
This should fix some problems of the original version
=> Added first Beam integration test

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Reverts OpenRefine/OpenRefine#1527
=> Revert "pass the limit as int from javascript"

main/src/com/google/refine/expr/functions/Coalesce.java, main/src/com/google/refine/grel/ControlFunctionRegistry.java, main/tests/server/src/com/google/refine/tests/expr/functions/CoalesceTests.java
Adds coalesce function to GREL as specified in #1496 .
=> Add coalesce function

main/webapp/modules/core/scripts/views/data-table/cell-ui.js, main/webapp/modules/core/styles/views/data-table-view.less
=> Added display of `null` in data table view

main/src/com/google/refine/io/ProjectMetadataUtilities.java
Adding validation and display error if there is any exception. 
No functional change.
=> refactoring the code to show the error message if there is any

main/src/com/google/refine/expr/functions/strings/Contains.java, main/tests/server/src/com/google/refine/tests/expr/functions/ContainsFunctionTests.java
Closes #1554 
Implementation based on Partition function.
=> Contains function supports now regex as second argument 

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/langs/translation-fr.json, main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
Closes #1376.
Some translations will need to be updated - I think Weblate will flag them as such (by detecting that the English version has changed).
=> Migrate "Match all filtered cells" to use standard reconciliation services

main/src/com/google/refine/grel/ast/FieldAccessorExpr.java, main/tests/server/src/com/google/refine/tests/grel/GrelTests.java
Attempts to get a non-existent field will return null. Applies also to attempt to get a field from null
For #820 #1036
=> No field null

main/webapp/modules/core/langs/translation-en.json
Fixes the JSON structure after merge
=> Fix English translation

README.md
It took me a while to find out what OR is built in and how it runs. Added some small notes to the intro to help others.
=> Clarity in README

AUTHORS.md, README.md
=> Add usage instructions in README, move authors to separate file.

extensions/wikidata/module/scripts/previewrenderer.js
=> Fix aliases rendering in Wikidata schema

main/src/com/google/refine/sorting/BooleanCriterion.java, main/src/com/google/refine/sorting/NumberCriterion.java, main/tests/server/src/com/google/refine/tests/operations/row/RowReorderOperationTests.java
=> Fix exception when sorting the empty string numerically

main/src/com/google/refine/exporters/CustomizableTabularExporterUtilities.java, main/tests/server/src/com/google/refine/tests/exporters/HtmlExporterTests.java
=> Clickable URLs in HTML exporter

main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
=> Improve facet expression for type match.

main/webapp/modules/core/langs/translation-jp.json
=> Fix Wikimedia language code for Japanese

refine
See also discussion at https://groups.google.com/forum/#!topic/openrefine-dev/krDU90W01uA
=> Comment whitespace in command to ensure all arguments used

main/src/com/google/refine/importers/RdfJsonldTripleImporter.java, main/src/com/google/refine/importers/RdfTripleImporter.java, main/tests/server/src/com/google/refine/tests/importers/RdfTripleImporterTests.java, main/webapp/modules/core/MOD-INF/controller.js
To support n-triples, ttl, and JSON-LD
=> Extend RDF imports

extensions/wikidata/src/org/openrefine/wikidata/schema/WbStringVariable.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStringVariableTest.java
=> Fix rendering of integers in Wikidata extension.

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
=> Focus property input when adding qualifiers and references

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
=> Make reference toggle clickable.

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
=> Re-render table view when switching back from Wikidata schema.

extensions/wikidata/module/scripts/previewrenderer.js
=> Fix qualifier order in preview.

extensions/wikidata/module/MOD-INF/controller.js, extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/module/scripts/dialogs/import-schema-dialog.html, extensions/wikidata/module/scripts/dialogs/import-schema-dialog.js, extensions/wikidata/module/scripts/menu-bar-extension.js, extensions/wikidata/module/styles/dialogs/import-schema-dialog.less, extensions/wikidata/src/org/openrefine/wikidata/commands/PreviewWikibaseSchemaCommand.java, extensions/wikidata/src/org/openrefine/wikidata/exporters/SchemaExporter.java, extensions/wikidata/tests/src/org/openrefine/wikidata/exporters/SchemaExporterTest.java
=> Add import and export for Wikidata schema

main/src/com/google/refine/expr/functions/ToDate.java, main/tests/server/src/com/google/refine/tests/expr/functions/strings/ToFromConversionTests.java
I've fixed #1759 and refactored code in toDate function. I think the way I've reorganised the code makes it easier to read and understand, but I'd welcome feedback on the way I've approached this.
=> Fix toDate

main/src/com/google/refine/browsing/facets/ListFacet.java, main/tests/server/src/com/google/refine/tests/browsing/facets/ListFacetTests.java
Thanks @ostephens for noticing this!
Closes #1827.
=> Fix issue of empty list facet choices disappearing.

GOVERNANCE.md
clarify the governance doc as per the discussion in the [dev mailing list](https://groups.google.com/d/msg/openrefine-dev/Csk4QrKrHiE/s_nrZYSICAAJ)
=> clarify role and list of committer

main/webapp/modules/core/scripts/dialogs/expression-column-dialog.html, main/webapp/modules/core/scripts/dialogs/expression-column-dialog.js
Minor fixup to on screen text and underlying html
=> Fix on screen text in Transform All columns dialog

main/pom.xml, main/src/com/google/refine/RefineServlet.java, packaging/pom.xml, server/src/com/google/refine/Refine.java
Changes the version number displayed both in the console and the web UI to be the short git commit id. Closes #1305.
=> Display git commit id instead of "TRUNK"

extensions/wikidata/module/scripts/warningsrenderer.js, main/webapp/modules/core/langs/translation-en.json
This fixes a few untranslated strings in the UI after the migration to the new localization library.
=> Fixes to localized strings in the UI

main/src/com/google/refine/model/recon/StandardReconConfig.java, main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java
=> Fix reconciliation result deserialization

main/src/com/google/refine/importers/XmlImporter.java, main/tests/server/src/com/google/refine/tests/importers/XmlImporterTests.java
Thanks @itsacoderepo for the report! This seems to fix the vulnerability, can you confirm?
Keep up the good work!
=> Disable DTDs in XML importer.

extensions/wikidata/src/org/openrefine/wikidata/editing/NewItemLibrary.java, extensions/wikidata/tests/src/org/openrefine/wikidata/editing/NewItemLibraryTest.java, main/src/com/google/refine/model/recon/StandardReconConfig.java
=> Compute reconciliation features when creating new items

refine
* pass options as proper bash list items so that even if directories
contain spaces, they will be properly passed on to java - #1623
* ignore empty options
=> enable spaces in data directory

main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
=> Fix untranslated string in UI

extensions/database/pom.xml, main/pom.xml
Fixes a security vulnerability.
=> Update Jackson to 2.9.8 per CVE-2018-19360

main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java, main/tests/server/src/com/google/refine/tests/operations/recon/ReconUseValuesAsIdsOperationTests.java
=> Accept URIs in 'Use values as ids' operation.

extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java
Fixes https://github.com/Wikidata/editgroups/issues/4.
=> Increment editgroups hash size for 3.2, fix comma issue in summaries

main/src/com/google/refine/importers/TextFormatGuesser.java
=> Fixer format guesser to return format for N3/Turtle files

extensions/database/pom.xml, extensions/gdata/pom.xml, main/pom.xml
=> Update Jackson to 2.9.9.

appveyor.yml
=> Disable packaging in Appveyor

extensions/wikidata/module/scripts/previewrenderer.js
=> Fix datavalue rendering cache in Wikidata preview

main/src/com/google/refine/browsing/facets/FacetConfig.java, main/src/com/google/refine/clustering/ClustererConfig.java, main/src/com/google/refine/model/AbstractOperation.java, main/src/com/google/refine/preference/PreferenceValue.java, main/src/com/google/refine/sorting/Criterion.java, main/tests/server/src/com/google/refine/tests/preference/TopListTests.java, main/tests/server/src/com/google/refine/tests/util/TestUtils.java
=> Remove duplicate JSON keys.

main/src/com/google/refine/model/recon/StandardReconConfig.java, main/tests/server/src/com/google/refine/tests/model/recon/StandardReconConfigTests.java
Closes #2076. I believe this was already solved by #1967 actually, but this is just to be extra sure.
=> Fix NPE in StandardReconConfig.

main/webapp/modules/core/scripts/facets/text-search-facet.js
My attempt to tackle https://github.com/OpenRefine/OpenRefine/issues/2044
=> Add a unique id to text filter facet checkboxes and labels.

main/pom.xml
=> Fix git commit info extraction to avoid build failures.

main/src/com/google/refine/browsing/facets/ScatterplotFacet.java, main/src/com/google/refine/commands/browsing/GetScatterplotCommand.java, main/tests/server/src/com/google/refine/browsing/facets/ScatterplotFacetTests.java, main/tests/server/src/com/google/refine/commands/browsing/ScatterplotDrawCommandTests.java
closes #2117.
This is a pretty important bug so I think we should consider making a release fairly soon.
=> Fix scatterplot drawing command

main/webapp/modules/core/scripts/facets/list-facet.js, main/webapp/modules/core/scripts/index/lang-settings-ui.js
=> Fix UI language change

main/src/com/google/refine/clustering/binning/BinningClusterer.java, main/tests/server/src/com/google/refine/clustering/binning/BinningClustererTests.java, main/tests/server/src/com/google/refine/clustering/knn/kNNClustererTests.java
=> Fix clusters with single candidates.

main/webapp/modules/core/scripts/dialogs/extend-data-preview-dialog.js
Will resolve https://github.com/OpenRefine/OpenRefine/issues/2177
=> Prefer view.url pattern for data extension preview links

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js, main/webapp/modules/core/scripts/util/custom-suggest.js
Remove Freebase-specific option and default value
Will resolve https://github.com/OpenRefine/OpenRefine/issues/2168
=> Set suggestOptions.type to the selected reconciliation type

extensions/database/pom.xml, extensions/gdata/pom.xml, main/pom.xml, pom.xml
Also refactors the Maven config files to make version changes easier.
=> Update Jackson to 2.9.10

main/webapp/modules/core/styles/views/data-table-view.less
This fixes #2183 by using relative positioning and float.
=> Issue 2183

main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.html
=> #1970 Disable spell check for expressions.

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java, extensions/wikidata/src/org/openrefine/wikidata/editing/ReconEntityRewriter.java, extensions/wikidata/src/org/openrefine/wikidata/schema/exceptions/NewItemNotCreatedYetException.java, extensions/wikidata/src/org/openrefine/wikidata/updates/ItemUpdate.java, extensions/wikidata/tests/src/org/openrefine/wikidata/editing/ReconEntityRewriterTest.java
=> Fix duplicate creations of Wikidata items

main/src/com/google/refine/commands/lang/LoadLanguageCommand.java, main/tests/server/src/com/google/refine/commands/lang/LoadLanguageCommandTests.java
=> Return best loaded language code in LoadLanguageCommand.

main/pom.xml
Sadly this is not enough for #2225, but at least using the latest version should potentially solve other bugs.
=> Update odftoolkit to 0.9.0-RC1

extensions/wikidata/src/org/openrefine/wikidata/schema/WbQuantityExpr.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WbStringVariable.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbQuantityExprTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStringVariableTest.java
=> Fix overflow error for quantities stored as doubles.

main/pom.xml
This could potentially help with #949?
=> Update Apache POI to 4.1.1

main/src/com/google/refine/exporters/CustomizableTabularExporterUtilities.java, main/src/com/google/refine/exporters/XlsExporter.java, main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java
=> More robust URI detection in tabular exporter.

main/src/com/google/refine/ProjectManager.java, main/src/com/google/refine/commands/expr/LogExpressionCommand.java, main/tests/server/src/com/google/refine/commands/expr/LogExpressionCommandTests.java
=> Fix NPE in expression logging.

.github/SUPPORT.md
This will add a special Github popup for first time issue creators, details of how it works are here: https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project
=> Create SUPPORT.md file

refine
=> Update downloaded Maven copy to fix HTTPS issue

extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java
Final part of the fix for #2196, which is now possible now that 3.3 was released.
=> Apply tags directly through the Wikibase API, fixes #2196

.github/workflows/maven.yml, .github/workflows/release_manager.sh
- Initial configuration to build releases
- See [mail list](https://groups.google.com/forum/#!msg/openrefine-dev/8aDWBHUqIGU/oeRwz53NCwAJ) for details and requirements
=> GitHub Actions and Hosted Runners

extensions/database/module/scripts/index/database-import-controller.js, extensions/database/module/scripts/index/database-import-form.html, extensions/database/module/scripts/index/database-source-ui.js, extensions/database/pom.xml, extensions/database/src/com/google/refine/extension/database/DatabaseService.java, extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteConnectionManager.java, extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseService.java, extensions/database/tests/conf/appveyor_tests.xml, extensions/database/tests/conf/tests.xml, extensions/database/tests/conf/travis-sqlite.sql, extensions/database/tests/conf/travis_tests.xml, extensions/database/tests/src/com/google/refine/extension/database/DBExtensionTestUtils.java, extensions/database/tests/src/com/google/refine/extension/database/DBExtensionTests.java, extensions/database/tests/src/com/google/refine/extension/database/DatabaseServiceTest.java, extensions/database/tests/src/com/google/refine/extension/database/DatabaseTestConfig.java, extensions/database/tests/src/com/google/refine/extension/database/sqlite/SQLiteConnectionManagerTest.java, extensions/database/tests/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseServiceTest.java
* Added SQLite support
* Fixed database import javascript code that was sending a null value
This module uses the following values when connecting to SQLite:
_Database_: location of sqlite file
=> Added SQLite support

main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.js, main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.js, main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.js, main/webapp/modules/core/scripts/project/exporters.js
=> fix: cannot export a file if blank tab opened is not closed

extensions/database/tests/src/com/google/refine/extension/database/DBExtensionTestUtils.java, main/pom.xml, main/src/com/google/refine/ProjectManager.java, main/src/com/google/refine/commands/lang/LoadLanguageCommand.java, main/src/com/google/refine/exporters/HtmlTableExporter.java, main/src/com/google/refine/expr/functions/strings/Chomp.java, main/src/com/google/refine/expr/functions/strings/Escape.java, main/src/com/google/refine/expr/functions/strings/SHA1.java, main/src/com/google/refine/expr/functions/strings/ToTitlecase.java, main/src/com/google/refine/expr/functions/strings/Unescape.java, main/src/com/google/refine/importers/ExcelImporter.java, main/src/com/google/refine/importers/JsonImporter.java, main/src/com/google/refine/importers/SeparatorBasedImporter.java, main/src/com/google/refine/importers/XmlImporter.java, main/src/com/google/refine/util/JSONUtilities.java
* Replaced `org.apache.commons.lang3.text` with `org.apache.commons.text`
* Updated `chomp` with `removeEnd`
* Replaced `DigestUtils.shaHex` with `DigestUtils.sha1Hex`
=> Replaced some deprecated methods

server/src/com/google/refine/Refine.java
Fixes #2336 
cc: @thadguidry @wetneb
=> fix: Browser redirection for 0.0.0.0

.github/ISSUE_TEMPLATE/config.yml
GitHub added a few new features for building strong community support and we should take advantage of them, such as Contact Links. https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> Remove blank_issues creation and add Contacts to "New Issue"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- There were some neats in the Issue Templates .
- Some details here should be commented and to be shown just to the issue filer which was not commented and have to be manually removed while filing the issue.
=> enh: Some enhancements in issue template

main/webapp/modules/core/scripts/facets/text-search-facet.js
=> enh: Text Filter waits until user finishes updating

main/webapp/modules/core/scripts/facets/list-facet.js
=> fix: List facets dialogue should be non editable

main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.html
=> Corrects wrong trim label for XML importer config

main/webapp/modules/core/scripts/project.js
=> Removed freebaseapps.com from scripts

refine.ini
Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>
There were some minor typos in the refine.ini file.
=> fixed minor typos

main/webapp/modules/core/scripts/project/exporters.js
=> Removed exportTrippleloader function 

main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.js
=> Fixes no selected record element error

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
=> Reconciliation UI: property not included if checkbox unchecked

main/src/com/google/refine/importers/tree/XmlImportUtilities.java, main/tests/server/src/com/google/refine/importers/JsonImporterTests.java, main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
=> [FIX] json/xml trim whitespace configuration option

extensions/gdata/module/scripts/index/importing-controller.js, extensions/gdata/src/com/google/refine/extension/gdata/GDataImportingController.java
**Refers**: _Can't select a different sheet than the default in a gSheet importation_ #2307
=> Fixed that can't select a different sheet #2307

main/webapp/modules/core/styles/index.less, main/webapp/modules/core/styles/index/create-project-ui.less, main/webapp/modules/core/styles/index/default-importing-file-selection-panel.less, main/webapp/modules/core/styles/index/open-project-ui.less, main/webapp/modules/core/styles/project/facets.less
Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>
I have fixed LESS styling and removed the undefined ones.
=> Fixed wrong and undefined stylings

main/webapp/modules/core/scripts/index/default-importing-sources/import-from-web-form.html, main/webapp/modules/core/scripts/index/default-importing-sources/sources.js
=> Creates project from URL when press ENTER

main/src/com/google/refine/importers/SeparatorBasedImporter.java, main/src/com/google/refine/importers/TabularImportingParserBase.java, main/tests/server/src/com/google/refine/importers/TsvCsvImporterTests.java, main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js
=> Adds trim whitespace option to separator based files

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java, extensions/wikidata/tests/src/org/openrefine/wikidata/editing/EditBatchProcessorTest.java
=> make maxlag configurable

.gitignore
=> ignore .idea/ from intellj

extensions/wikidata/module/styles/dialogs/schema-alignment-dialog.css
=> Grabbing cursor added while adding items for creating wikidata schema

main/src/com/google/refine/util/StringUtils.java, main/tests/server/src/com/google/refine/util/StringUtilsTests.java
=> Provides more intuitive representation for arrays in GREL

.github/workflows/maven.yml
=> Don't try to upload if running in a forked repo

pom.xml
=> Add our Org attributes to parent POM

main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js, main/webapp/modules/core/scripts/views/data-table/replace-dialog.html
Refers: set focus on find-field for replace command #2514
Added a function to focus on input field
=> Fixed to focus on find-field

docs/README.md
Node.js is fully needed for Docusaurus things (package verifying, etc.).
=> make steps a bit more clear

docs/README.md
Reference https://github.com/OpenRefine/OpenRefine/pull/2564
=> Update the docs ReadMe for Yarn Installation

docs/README.md, docs/package.json, docs/siteConfig.js
This is an attempt to deploy the docs with Netlify, which should provide PR previews.
=> Set up docs deployment process with Netlify

docs/siteConfig.js
=> Adds "Edit this Doc" button for each document

main/webapp/modules/core/scripts/views/data-table/cell-ui.js
Fixes the editing of null cells, followup for #2440.
=> Fix null cell editing, followup for #2440

main/src/com/google/refine/exporters/XlsExporter.java, main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java, main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java, main/webapp/modules/core/MOD-INF/controller.js
https://github.com/OpenRefine/OpenRefine/issues/2595
=> correct excel mime types

extensions/wikidata/module/scripts/dialogs/manage-account-dialog.html, extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js
=> Fix Enter key behaviour in Wikidata login form

main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java
* not a big improvement but now the output is checked to see if it is valid xls format
=> small improvement to xls tests

main/src/com/google/refine/exporters/XlsExporter.java, main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java, main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java
https://github.com/OpenRefine/OpenRefine/issues/2600
=> allow xlsx files to have more columns

main/src/com/google/refine/expr/functions/Type.java, main/tests/server/src/com/google/refine/expr/functions/TypeTests.java
(Closes #2510)
Fix the true.type() == "boolean" instead of "java.lang.Boolean".
Regards,
Antoine
=> (Closes #2510) Fix the true.type() == "boolean"

README.md
Make a real link to Authors and add a section for the file Contributing.
Regards, A.
=> Update README.md with a link to Authors and adding a section for the file Contributing

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
=> Make parameter naming consistent - wikibase.upload.maxLag

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizer.java
=> Fix Wikidata entity type constraint violation message

main/webapp/modules/core/langs/translation-es.json, main/webapp/modules/core/langs/translation-fr.json
remove-facet was mentioned twice with 2 different messages
=> Fix duplicate i18n keys for FR & ES

main/webapp/modules/core/error.vt
=> Use absolute path in error.vt

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java, extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinRangeScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinScrutinizerTest.java
Implemented difference-within-range constraint as part of #2354
=> Add difference-within-range Scrutinizer

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java, extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizerTest.java
Implemented conflicts-with scrutinizer as part of #2354
=> Add conflicts-with constraint

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
=> Disables FacetContainer while computing clusters

extensions/jython/pom.xml
=> Update to latest Jython version 2.7.2

main/src/com/google/refine/importers/WikitextImporter.java, main/webapp/modules/core/scripts/reconciliation/recon-manager.js
=> Update URL of Wikidata reconciliation service

.lgtm.yml, .travis.yml
Attempt to fix LGTM build so that it doesn't attempt to do packaging.
=> Fix LGTM build

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js, main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.js, main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.js, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js, main/webapp/modules/core/scripts/project/exporters.js
Fixes #1352. First piece of replacement for #2713.
=> Preserve international characters in project/file names on import/export

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java
=> New implementation for Conflicts-With Scrutinizer

pom.xml
Closes #2266. This time hopefully for real!
=> Fix coverage computation

.lgtm.yml, lgtm.yml
=> Merge LGTM.com configurations

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/langs/translation-fr.json, main/webapp/modules/core/scripts/preferences.js
(Closes #2765)
Fix i18n not working in the Edit Pref Window, added an error message on failure.
Functional. Added an error message localized if possible when there is a problem loading the dictionary. Lots of failbacks.
Regards,
Antoine
=> (I #2765) Fix i18n not working in the Edit Pref Window

main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/langs/translation-fr.json
Fixes #2700 (for real). The previous PR only updated 2 of 3 places needed. This fixes the last remaining one and fixes the French translation to pluralize correctly for Go To page.
=> Add missing wiring for i18n plurals.

extensions/gdata/src/com/google/refine/extension/gdata/SpreadsheetSerializer.java, extensions/gdata/src/com/google/refine/extension/gdata/UploadCommand.java
=> Fix Google Sheets export with empty cells

main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js, main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html
=> Adds a default separator preference for split/join multi valued cells

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ScrutinizerTest.java
Implemented inner class & improved tests using mocks.
=> New implementation for Multivalue Scrutinizer

extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ScrutinizerTest.java
updated test class by creating mocks for ConstraintFetcher
=> Updated Conflicts-with Scrutinizer tests using Mockito

extensions/wikidata/src/org/openrefine/wikidata/qa/Constraint.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/ConstraintTest.java
Added constraint class that can be used as a superclass for the inner class in most of the scrutinizers.
=> Add constraint class

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ScrutinizerTest.java
Changed the return type of [getConstraintsByTpye](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java#L301) method from Stream<Statement> to List<Statement>
=> Change return type of getConstraintsByType method

extensions/wikidata/src/org/openrefine/wikidata/qa/Constraint.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizerTest.java
Updated test class & added inner class to the scrutinizer
=> Implemented SingleValue Scrutinizer tests using mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/Constraint.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizerTest.java
Added inner class to the scrutinizer and updated the tests using mocks.
=> Implemented DistinctValueScrutinizer tests using mockito

main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/langs/translation-en.json
In the reference of #2753 
convert from `.tar or .tar.gz or .zip`  to `.tar or .tar.gz`
=> Fix the typo

extensions/wikidata/src/org/openrefine/wikidata/qa/ConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/MockConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizerTest.java
Updated all the testcases in EntityTypeScrutinizerTest
=> Implemented EntityTypeScrutinizer tests using mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstraintScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstaintScrutinizerTest.java
Updated test cases and added InverseConstraint Class
=> Implemented InverseScrutinizer tests using Mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizerTest.java
Updated test cases & added AlLowedQualifierConstraint and MandatoryQualifierConstraint classes.
=> Implemented QualifierComaptibilty Scrutinizer tests using Mockito

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizerTest.java
Updated implementation of the scrutinzer & tests
=> Implemented Format Scrutinizer tests using Mockito

main/tests/server/src/com/google/refine/RefineTest.java, main/tests/server/src/com/google/refine/expr/functions/ToNumberTests.java, main/tests/server/src/com/google/refine/grel/FunctionTests.java, main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
Add tests for:
- ToNumber conversions
- All functions when passed 0 args
- All functions when passed 8 args
There are a number of functions which don't properly check their parameters, but I haven't fixed them for now until we think about the compatibility implications.
=> Unit test improvements

main/webapp/modules/core/MOD-INF/controller.js
Fixes #2820 
In Extension to format mappings :- change "text/line-based" to "text"(238 line)
In Mime type to format mappings :-  change "text/line-based" to "text"(269 line)
=> Fixed the guessing of JSON for .txt(2820)

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinRangeScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ScrutinizerTest.java
Updated all test cases and added DifferenceWithinRangeConstraint class.
=> Implemented Difference-within-range Scrutinizer tests using mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizerTest.java
Updated test cases and added AllowedUnitsConstraint class.
=> Implemented QuantityScrutinizer tests using Mocks

main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js
=> Internationalize clipboard default project name

main/webapp/modules/core/langs/translation-fr.json
=> remove English sentence from French translation

main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
Increases timeout for test from 1 sec to 3 sec
Fixes #2875
=> Increase test timeout - fixes #2875

extensions/wikidata/src/org/openrefine/wikidata/commands/ConnectionManager.java, extensions/wikidata/tests/src/org/openrefine/wikidata/commands/LoginCommandTest.java
=> Fix Wikidata logout when credentials have expired

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizerTest.java
Added AllowedValueConstraint & DisallowedValueConstraint classes and updated the tests too.
=> Implemented ResctrictedValue Scrutinizer tests using mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizerTest.java
Added RestrictedPositionConstraint class and updated test cases using mocks
=> Implemented RestrictedPosition Scrutinizer tests using mocks

extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizer.java
Removed inner class as for constraint status and exceptions we now have Constraint class.
=> Update MultiValueScrutinizer class

main/webapp/modules/core/langs/translation-en.json
=> update parse-cell text

main/webapp/modules/core/scripts/reconciliation/add-standard-service-dialog.html, main/webapp/modules/core/scripts/reconciliation/recon-dialog.js
=> Add standard service on enter

main/webapp/modules/core/scripts/facets/text-search-facet.js
=> Ignore events which don't change text input - fixes #1134

main/webapp/modules/core/scripts/reconciliation/recon-dialog.js
=> fixes service panel toggling

extensions/wikidata/tests/src/org/openrefine/wikidata/qa/ConstraintTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DifferenceWithinScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/EntityTypeScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/FormatScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstaintScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/MultiValueScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QualifierCompatibilityScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/QuantityScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedPositionScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/RestrictedValuesScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizerTest.java
Reused the hardcoded constraint & parameter IDs from the scrutinizer classes into the test classes respectively.
=> Reused Constraint IDs and Parameter PIDs

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/UseAsQualifierScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/UseAsQualifierScrutinizerTest.java
Implemented one-of qualifier value property constraint as part of #2354
=> Add One-of qualifier value property constraint

main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java, main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java
Refs #2122. Also reenable a couple of disabled tests
=> Add tests for wide XLS/XLSX export

extensions/wikidata/src/org/openrefine/wikidata/qa/WikidataConstraintFetcher.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/WikidataConstraintFetcherTests.java
Tests for getConstraintsByTpe & getConstraintStatements methods.
=> Add test-cases for methods defined in WikidataConstraintFetcher

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/UnsourcedScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/UnsourcedScrutinizerTest.java
Implemented Citation needed Constraint as part of #2354
=> Add Citation needed Scrutinizer

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/index/import-project-ui.html, main/webapp/modules/core/scripts/index/import-project-ui.js
In the preference of #2369 
Add function that control the widow alert
=> Fix the UI related to Import project

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.html, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js
=> Give the name to button 'Back'

extensions/wikidata/src/org/openrefine/wikidata/utils/EntityCache.java, extensions/wikidata/tests/src/org/openrefine/wikidata/utils/EntityCacheTests.java
Added `getMultipleDocuments` method
=> Update EntityCache class

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js
Fixes #2987 
Add message :-
"OpenRefine can only import multiple files into a single project if all selected files have the same number of columns."
=> Add improvement-message for vantage

extensions/wikidata/src/org/openrefine/wikidata/schema/WbItemDocumentExpr.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WbReferenceExpr.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WbStatementExpr.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WbStatementGroupExpr.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WikibaseSchema.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbItemDocumentExprTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbReferenceExprTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStatementExprTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStatementGroupExprTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WikibaseSchemaTest.java
=> Changed List return type to ImmutableList in Wikidata schema package classes

extensions/wikidata/module/scripts/dialogs/schema-alignment-dialog.js
=> Fix race condition in service manifest fetching

extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
fixes #2509  The number format exception will be caught in case of any invalid port numbers.
=> Handle NumberFormatException thrown in DatabaseImportController

main/src/com/google/refine/model/recon/StandardReconConfig.java
=> Set read timeout to 60 sec for reconciliation.

main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
Add a event listener on press of enter key on the column name.
=> Fix for issue #3163, Calling the okbutton.click() on press of enter

main/src/com/google/refine/expr/functions/xml/WholeText.java, main/src/com/google/refine/grel/ControlFunctionRegistry.java, main/tests/server/src/com/google/refine/expr/functions/html/ParseHtmlTests.java
Fixes #3180 
- Ref: https://github.com/jhy/jsoup/blob/master/CHANGES#L275
- Ref: https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#wholeText()
=> Adds new Jsoup wholeText() function and tests

extensions/database/module/langs/translation-en.json, extensions/database/module/langs/translation-fr.json, extensions/database/module/scripts/index/database-import-controller.js, extensions/database/module/scripts/index/database-import-form.html, extensions/database/module/styles/database-import.less, extensions/database/module/styles/pure.css
Fixes #3213.
Also cleans up some funky styling on the same page, but it could definitely use some more love.
=> Add i18n for Database Importer name - fixes #3213

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js, extensions/wikidata/module/scripts/dialogs/password-login-dialog.html
=> Wikidata extension - discourage use of main password

.travis.yml
=> Mark the Mac build as an allowed failure.

main/src/com/google/refine/expr/functions/strings/Reinterpret.java, main/tests/server/src/com/google/refine/expr/functions/strings/ReinterpretTests.java
=> add clarity for reinterpret docs

extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java
=> Fix NPE bug in EditInspector

main/src/com/google/refine/clustering/binning/FingerprintKeyer.java, main/tests/server/src/com/google/refine/clustering/binning/KeyerTests.java
=> Add Wynn to fingerprint to support Old English texts

main/src/com/google/refine/importers/XmlImporter.java, main/tests/data/xml-sample-format-1.xml, main/tests/data/xml-sample-format-2.xml, main/tests/data/xml-sample-format-3.xml, main/tests/data/xml-sample-format-4.xml, main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
* Fixes the issue while importing XML data containing whitespace characters generating empty cells in the table.
* Contains Unit Tests for the Fix
=> Fix: Preventing addition of any empty cells with whitespaces while importing Xml Data with Tests #1095

.github/workflows/pull_request.yml, main/tests/cypress/package.json
=> chore: align test-suite name with npm standards

.github/workflows/pull_request.yml
=> chore: restore caching in pr workflow

.github/workflows/snapshot_release.yml
=> ci: clear cache in snapshot_release workflow

.github/workflows/snapshot_release.yml
=> ci: restore cache for snapshot release workflow

docs/docs/index.md
A baseline of introductory text. Not too sure what needs to be included here but so far it's just a walkthrough of the docs structure.
=> Docs > index page

.github/workflows/pull_request.yml
Reference https://github.com/OpenRefine/OpenRefine/pull/3474#issuecomment-761526641
=> fix: checkout pull_request head always

main/webapp/modules/core/langs/translation-en.json
fixes #3480 
Thought, there could be some error handling issue causing this symbol appearance but it was a pretty easy fix.
=> fix: unwanted characted in version metadata

.github/workflows/release_manager.sh
=> Pass access tokens via header in GitHub workflow.

main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js
"Fixes #3460"
Fix for - $1" in the UI instead of the actual number.
Have attached the screenshot for reference. 
Please let me know if it solves your purpose as I have recently joined this community.
=> Broken counts in file selection dialog #3460

docs/src/css/custom.css
=> feat: move to em from pixels

main/tests/cypress/.prettierignore, main/tests/cypress/.prettierrc.json, main/tests/cypress/cypress.json, main/tests/cypress/cypress/integration/create-project/create_project.spec.js, main/tests/cypress/cypress/integration/import-project/import_project.spec.js, main/tests/cypress/cypress/integration/language/change_language.spec.js, main/tests/cypress/cypress/integration/open-project/list_projects.spec.js, main/tests/cypress/cypress/integration/open-project/open_project.spec.js, main/tests/cypress/cypress/integration/preferences/change_preference.spec.js, main/tests/cypress/cypress/integration/project/grid/column/facet/facets.numeric.spec.js, main/tests/cypress/cypress/integration/project/grid/column/facet/facets.spec.js, main/tests/cypress/cypress/integration/project/grid/column/sort.spec.js, main/tests/cypress/cypress/integration/project/grid/row/edit_cells.spec.js, main/tests/cypress/cypress/integration/project/project-header/export_project.spec.js, main/tests/cypress/cypress/integration/project/undo_redo/apply.spec.js, main/tests/cypress/cypress/integration/project/undo_redo/extract.spec.js, main/tests/cypress/cypress/integration/project/undo_redo/undo_redo.spec.js, main/tests/cypress/cypress/integration/project_management/project_metadata.spec.js, main/tests/cypress/cypress/plugins/index.js, main/tests/cypress/cypress/support/commands.js, main/tests/cypress/cypress/support/index.js, main/tests/cypress/cypress/support/openrefine_api.js, main/tests/cypress/package.json, main/tests/cypress/yarn.lock
reference https://github.com/OpenRefine/OpenRefine/pull/3474#issuecomment-762076476
=> feat: introduct prettier style formatting for cypress test suite

docs/docusaurus.config.js
Got our ID and API key from Algolia. Following the directions here: https://v2.docusaurus.io/docs/search/#using-algolia-docsearch
=> Docs > Algolia search

.github/workflows/release_manager.sh, main/webapp/modules/core/index.vt, main/webapp/modules/core/project.vt, main/webapp/modules/core/scripts/project/history-panel.html
Changing obsolete links to the github wiki to the new docs.
I'm sure I haven't caught them all yet, and there is no rush on this just yet.
=> Updating codebase links

main/webapp/modules/core/scripts/preferences.js
(Closes #2768)
Fix the editing of a pref that proposed the oldest value of a preference, instead of the current value. This is functional.
Regards,
Antoine
=> (I #2768) Fix editing pref that shows a very old value and not the current

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/index.js
=> fix: add additional version translation

main/tests/cypress/package.json
Reverted Cypress, too much instability with the latest version
#3509
=> fix: Reverted Cypress to 6.2.1, #3509

docs/docs/manual/installing.md
and whereby upon it's merge, we can then also see if the snapshot release hopefully IS NOT automatically triggered either :-)
=> fix small typo in installation docs

main/tests/cypress/cypress/integration/open-project/filter_projects.spec.js, main/tests/cypress/cypress/support/openrefine_api.js
=> tests: add test for filtering project through tags

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/blank-down.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/collapse-consecutive-whitespace.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-date.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-number.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/trim-leading-whitespace.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/unescape-html-entities.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/fill-down.spec.js, main/tests/cypress/cypress/support/commands.js
I think this PR gives enough coverage about Edit cells to let the community implement the remaining cases, it's relatively simple
Will split issue #3423 into 2,3 separate issues once this is merged
=> test: Added test cases for edit Cells, #3423

main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js
Added tests for a generic expression panel (Using custom text facet)
=> test: Added tests for expression panels, #3498

.github/workflows/snapshot_release.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#excluding-paths
Reference : https://groups.google.com/d/msgid/openrefine-dev/9e63f87e-0a28-49d7-9d62-0168156661c3n%40googlegroups.com?utm_medium=email&utm_source=footer
=> fix: specify paths-ignore in place of negative pattern

docs/docs/manual/installing.md, docs/docs/technical-reference/build-test-run.md
since the older JDK 14 version page says its been superseded with the new version
=> Update Java version

.github/workflows/pull_request.yml
This hopefully closes #3571, we'll need to try it out.
=> Attempt to run the CI on the test merge instead of the branch

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/blank-down.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/collapse-consecutive-whitespace.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/proper-display.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-date.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-number.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/trim-leading-whitespace.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/unescape-html-entities.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/fill-down.spec.js, main/tests/cypress/cypress/integration/project/grid/column/facet/facets.spec.js, main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js, main/tests/cypress/package-lock.json, main/tests/cypress/package.json, main/webapp/modules/core/scripts/views/data-table/cell-ui.js
fixes #2519
- added <a>href tag creation for URLs in cell text.
- added tests.
=> fixed href tag creation for URLs in cell text

main/tests/cypress/cypress/integration/project/grid/column/text_filter.spec.js
=> fix: UX tests linting

main/tests/cypress/cypress.json, main/tests/cypress/cypress/support/commands.js
Increased retries
Improved method to click on column menus, now waiting for Or to not be updating anything
=> Attempts to fix Flaky tests, Issue 3594

.github/workflows/pull_request.yml, main/tests/cypress/package.json
=> CI: add eslint workflow in the CI

main/tests/cypress/cypress/integration/project/grid/all-column/flag.spec.js, main/tests/cypress/cypress/integration/project/grid/all-column/star.spec.js
=> Add UX Test for controls at the row level 

main/tests/cypress/cypress/integration/project/grid/all-column/flag.spec.js, main/tests/cypress/cypress/integration/project/grid/all-column/star.spec.js
refer https://github.com/OpenRefine/OpenRefine/pull/3626#issuecomment-778817086
- The issue was caused due to the `pull_request_target` as well as the branch which was being merged was not in sync with upstream/master
=> fix: accidental non-linted files in repo

.github/workflows/snapshot_release.yml
refers https://github.com/OpenRefine/OpenRefine/pull/3635#pullrequestreview-590072049
=> chore: add linting step in snapshot_release workflow

extensions/database/tests/conf/tests.xml
=> Fix database extension tests configuration.

lgtm.yml
=> Don't run tests for LGTM build - fixes #3652

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/Replace-Smart-quotes-with-ascii.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-empty-string.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-lowercase.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-null.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-text.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-titlecase.spec.js, main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/to-uppercase.spec.js
Fixes #3553
Added Tests for:
- Convert Smart quotes with ascii
- to titlecase
- to uppercase
- to lowercase
- to text
- to null
- to empty string
=> Added UX Tests for column / Edit cells / Common transforms

docs/docs/manual/reconciling.md
Fixes #3700
- Document other ways to make use of reconciliation services
=> Mention using local reconciliation services

docs/docs/technical-reference/build-test-run.md
Clarifying what lead to my confusion described in OpenRefine Gitter.
=> Some clarification on getting started with Eclipse

main/tests/cypress/cypress/support/openrefine_api.js
Fixes #3734
Fixed the method, that was actually putting the whole json in place of the filename
=> Fixed a testing method (cypress) that was failing for large datasets

docs/docs/manual/running.md
Fixes #3747 
-  Fix typo in doc
=> Fix broken link in automating OpenRefine docs. (fixes #3747)

main/webapp/modules/core/MOD-INF/controller.js
=> Replace deprecated "for each...in" syntax in controller.js

main/tests/cypress/cypress/integration/create-project/create_project.spec.js, main/tests/cypress/cypress/support/commands.js
=> fix: create project tests fails due to less timeout

main/tests/cypress/cypress/support/commands.js
=> fix: flake create_project multiple url test

main/tests/cypress/cypress/integration/project/grid/viewpanel-header/rows_records.spec.js
Fixes https://github.com/OpenRefine/OpenRefine/issues/3416
- https://github.com/OpenRefine/OpenRefine/issues/3416#issuecomment-800635615
=> fix: detached element from dom in row_record_spec

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml
=> fix: add java distribution in ci

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml
- Adds the distribution field for server tests job
=> fix: add distribution for server_tests job

.github/workflows/snapshot_release.yml
Reverts OpenRefine/OpenRefine#3459
Related & fixes #https://github.com/OpenRefine/OpenRefine/issues/3837
=> Revert "feat: add firefox for ui_tests"

docs/docs/technical-reference/maintainer-guidelines.md, docs/sidebars.js
Closes #3864.
This write-up is based on my current understanding of the procedures and conventions. I'd be very happy for some feedback and improvements :)
=> Add maintainer guidelines.

main/webapp/modules/core/scripts/util/encoding.js, main/webapp/modules/core/styles/util/encoding.less
Fixes #3862
- Adds windows-1252 to the list of common encodings
=> Adds windows-1252 to the list of common encodings

extensions/database/README.md
Fixes #3915
- Updated README.md for database extension with current Maven architecture and documentation links.
=> Update the README.md for database extension

main/src/com/google/refine/commands/browsing/GetScatterplotCommand.java, main/tests/server/src/com/google/refine/commands/browsing/ScatterplotDrawCommandTests.java
Fixes #3344
- Parse the rotation as string values
- Add two test to see if the rotation is set correctly
=> fixe rotation parsing in scatterplot facet

docs/docs/manual/expressions.md
Fixes #{3885}
Hi, I also encountered this problem and try to solve the problem according to my understanding. However, as I read the comments, I don't know if this problem is closed now. If it is closed, I'm sorry to waste your time to review and remind you that this problem should be closed.
=> Fix links in documentation

docs/docs/technical-reference/workflow-execution/local-runner.md
=> fix typo and mkdown lint errors

extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
=> Fix for issue #3605  when connecting to database type is SQLite, there's no port number required.

docs/package.json
There are significant updates currently and plans coming on their roadmap.  For now, along with many bug fixes, this allows us to explore more translation opportunities.  https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta and https://docusaurus.io/blog/2021/03/09/releasing-docusaurus-i18n
=> Update to Docusaurus 2 beta1

docs/docs/manual/exporting.md, docs/docs/manual/reconciling.md, docs/docs/manual/wikibase/advanced-schemas.md, docs/docs/manual/wikibase/schema-alignment.md, docs/docusaurus.config.js
Closes #4031
Doing the actual fixing of the links in another commit in the same PR so we can check that the build indeed fails otherwise.
=> Fix docusaurus config so it fails on broken links.

docs/README.md
Based on discussion thread https://groups.google.com/g/openrefine-dev/c/xWLwz88bUTA/m/oInlMfASAwAJ
=> Add Translations section to Docs README

.gitignore
=> ignore node_modules folder during active development

docs/docs/manual/installing.md
... and doesn't work with Java 16 or later versions (see issue [#4106](https://github.com/OpenRefine/OpenRefine/issues/4106))
=> mention it requires java 14

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml
Fixes #4150
Removed Microsoft Edge for CI/CD tests
=> Removed Microsoft Edge for CI/CD tests, #4150

extensions/wikidata/module/scripts/dialogs/import-schema-dialog.js, extensions/wikidata/module/scripts/schema-alignment.js
Fixes #4145 
- Fixed cancel button label
- Added check to avoid exception, which was stopping dialog close after import
=> fixes #4145 Schema import dialog improvement

main/tests/cypress/cypress/integration/project/undo_redo/apply.spec.js, main/tests/cypress/cypress/integration/project/undo_redo/extract.spec.js
=> Improved stability for undo/redo tests

main/tests/cypress/cypress/integration/project/undo_redo/apply.spec.js, main/tests/cypress/cypress/integration/project/undo_redo/extract.spec.js
Reverts OpenRefine/OpenRefine#4158
=> Revert "Improved stability for undo/redo tests"

docs/README.md
=> Mention about yarn upgrade for starting errors

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml, benchmark/pom.xml, extensions/database/pom.xml, extensions/gdata/pom.xml, extensions/jython/pom.xml, extensions/pc-axis/pom.xml, extensions/phonetic/pom.xml, extensions/sample/pom.xml, extensions/wikidata/pom.xml, packaging/pom.xml, pom.xml, server/pom.xml
I have attempted to update all the relevant configuration parameters but might have missed some, let's see!
I have also tried to control all of these parameters by two Maven properties in the root artifact, to make their updating a bit easier.
Closes #4278.
=> Drop support for Java 8.

extensions/wikidata/src/org/openrefine/wikidata/schema/WbEntityVariable.java, extensions/wikidata/src/org/openrefine/wikidata/schema/WbExpression.java, extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbEntityVariableTest.java
Fixes #4268 
- Add a WbEntityVariable class
=> 4268: Add WbEntityVariable class

.github/workflows/pull_request.yml, docs/docs/manual/installing.md, docs/versioned_docs/version-3.5/manual/installing.md, pom.xml
Fixes #4106.
- test with Java 17 in the CI (instead of Java 14).
=> Test for Java 17 in the CI

extensions/wikidata/module/scripts/schema-alignment.js, extensions/wikidata/pom.xml, extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java, extensions/wikidata/src/org/openrefine/wikidata/editing/ReconEntityRewriter.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/ReconItemIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/ReconMediaInfoIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/ReconPropertyIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/SuggestedItemIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/SuggestedMediaInfoIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/SuggestedPropertyIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/UpdateSequence.java
Fixes #4268 
- Make schema editor serialize WbEntityVariable instead of WbItemVariable
=> Make schema editor serialize WbEntityVariable

pom.xml
=> Change odftoolkit version to 0.9.0.

refine
Fixes #4405
Update version number from 3.8.3 to 3.8.4
- 
- 
-
=> fixes #4405 Maven version updated

main/webapp/modules/core/scripts/views/data-table/data-table-view.js
=> fix #4407 down-arrow image path broken on custom installation

main/src/com/google/refine/templating/Template.java, main/tests/server/src/com/google/refine/exporters/TemplatingExporterTests.java
Fixes #3955
- Modify main/src/com/google/refine/templating/Template.java
- Add test
=> Fix issue #3955 Missing Row Separators in Templating Export

main/src/com/google/refine/expr/functions/xml/ScriptText.java, main/tests/cypress/cypress/integration/project/grid/viewpanel-header/sort.spec.js
Fixes #4440.
One test was genuinely flaky, the other one had a legitimate reason to fail (yay!)
=> Fix failing Cypress tests

.github/workflows/pull_request.yml, main/pom.xml, main/tests/server/src/com/google/refine/RefineTest.java, main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java, main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java, pom.xml
Fixes #4384
- remove uses of PowerMock in the test suite
- enable Java 17 in the CI
=> PowerMock removal and Java 17 in CI

README.md
Removed AUTHORS.md related link as AUTHORS.md file doesn't exist anymore
=> Removed AUTHORS.md related link

docs/yarn.lock
Fixes #4477
- Updated with `npx browserslist@latest --update-db`
=> Fixes #4477 Updates caniuse-lite yarn package

docs/docs/manual/facets.md, docs/versioned_docs/version-3.5/manual/facets.md
You need this step to complete the numeric faceting example.
Without it, the numeric facet shows "no numeric value present".
=> Update facets example documentaion

docs/docs/manual/exporting.md, docs/versioned_docs/version-3.5/manual/exporting.md
=> Update documentation after fixing of the templating exporter

extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java, extensions/wikidata/src/org/openrefine/wikidata/editing/NewEntityLibrary.java, extensions/wikidata/src/org/openrefine/wikidata/manifests/Manifest.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EditScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/SnakScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/schema/entityvalues/ReconEntityIdValue.java, extensions/wikidata/src/org/openrefine/wikidata/updates/TermedStatementEntityUpdateBuilder.java, extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/PointerExtractor.java, extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/QuickStatementsUpdateScheduler.java, extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/WikibaseAPIUpdateScheduler.java, extensions/wikidata/tests/src/org/openrefine/wikidata/updates/scheduler/PointerExtractorTest.java
- Refactor PointerExtractor and QuickStatements
- Clean-up notes
=> Refactor clean up

main/webapp/modules/core/scripts/index/edit-metadata-dialog.js, main/webapp/modules/core/styles/index/open-project-ui.less
Fixes #4119 
-Added a sticky table header ,made the table scrollable.
Hopefully also Fixes #3520
=> Make project metadata table scrollable

extensions/wikidata/src/org/openrefine/wikidata/qa/SchemaPropertyExtractor.java
- Refactor property constraints to encompass entities rather than items
=> Constraints refactor

main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.js
Fixes #4271
-  Added update event handler to regenerate option JSON when the order changes
=> Issue #4271 Change column order in Custom Tabular Exporter doesn't update

main/webapp/modules/core/langs/translation-en.json
- Fixes some grammatical and syntactical errors in the `core-about/definition` string.
=> Grammar fixes in `core-about/definition` string

docs/docs/manual/wikibase/configuration.md
This shows how support for federation can be added.
Fixes #4287.
- update docs
=> Update documentation of Wikibase manifests for 2.0 format

server/src/com/google/refine/Refine.java
Fixes #902, which was assigned to me for a long time
- increase the default maximum form content size
=> Increase form max content size

extensions/wikidata/pom.xml
=> Update Wikidata-Toolkit to 0.13.1

extensions/database/module/scripts/index/database-import-form.html, extensions/database/module/scripts/index/database-parsing-panel.html, extensions/gdata/module/scripts/index/gdata-parsing-panel.html, extensions/pc-axis/module/scripts/pc-axis-parser-ui.html, main/webapp/modules/core/scripts/dialogs/clustering-dialog.html, main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html, main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.html, main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.html, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html, main/webapp/modules/core/scripts/index/default-importing-sources/import-from-clipboard-form.html, main/webapp/modules/core/scripts/index/import-project-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html, main/webapp/modules/core/scripts/project/history-apply-dialog.html, main/webapp/modules/core/scripts/project/history-extract-dialog.html, main/webapp/modules/core/scripts/project/history-panel.html, main/webapp/modules/core/scripts/views/data-table/replace-dialog.html
Fixes #3004
- add spellcheck="false" into input text type
=> disable spellcheck on input text type

main/src/com/google/refine/expr/functions/strings/Replace.java
Fixes #4640
- Added a regex example using open and close "/" similar to already stated example case
=> fixes #4640 added example of Regex usage to desc of replace()

CONTRIBUTING.md
=> Grammatical Error

main/webapp/modules/core/langs/translation-ceb.json, main/webapp/modules/core/langs/translation-de.json, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/langs/translation-es.json, main/webapp/modules/core/langs/translation-fil.json, main/webapp/modules/core/langs/translation-fr.json, main/webapp/modules/core/langs/translation-he.json, main/webapp/modules/core/langs/translation-hu.json, main/webapp/modules/core/langs/translation-it.json, main/webapp/modules/core/langs/translation-jp.json, main/webapp/modules/core/langs/translation-nl.json, main/webapp/modules/core/langs/translation-pt.json, main/webapp/modules/core/langs/translation-pt_BR.json, main/webapp/modules/core/langs/translation-ru.json, main/webapp/modules/core/langs/translation-tl.json, main/webapp/modules/core/langs/translation-zh.json, main/webapp/modules/core/scripts/views/data-table/data-table-view.js, main/webapp/modules/core/styles/util/dialog.less
Fixes #4662
- Removed 4px dialog border from dialogs.
- Added missing header for the All Column > Transform... dialog.
=> Removed 4px dialog border and added missing header

main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html, main/webapp/modules/core/scripts/dialogs/export-project-dialog.html, main/webapp/modules/core/scripts/reconciliation/add-namespaced-service-dialog.html, main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html, main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html
- Added missing HTML tags found with code inspection.
=> Added missing HTML tags

docs/docs/technical-reference/build-test-run.md, docs/versioned_docs/version-3.5/technical-reference/build-test-run.md
Mentions the main Java class of our application.
Follow-up to #4676.
=> Add mention of com.google.refine.Refine to our developer docs

main/webapp/modules/core/scripts/views/data-table/cell-ui.js
Fixes #2316
- Use a global variable to store user's choice of radio button
- Checked radio button is set by the user's previous choice
-
=> Fixes #2316 "Match other cells with same content" keeps appearing as the default choice #2316

extensions/gdata/src/com/google/refine/extension/gdata/UploadCommand.java
Fixes #4081
- Closed inputstream resource
- 
-
=> Fixes #4081 Unreleased Resource: Streams

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
Fixes #3172
- Notice added when selecting service
=> fixes #3172 Reconcile > Use values as identifiers" does not reconcile #4655 #4664

docs/docs/manual/reconciling.md, docs/versioned_docs/version-3.5/manual/reconciling.md
Fixes #4666
- Adds clarity with a better term of "known ids".
- Improves detail
=> Clear up some ambiguity in Reconciling with unique ids

docs/docs/technical-reference/contributing.md, docs/versioned_docs/version-3.5/technical-reference/contributing.md
Changes for Functional Tests. Also, more affirmative about Java test case.
- Instructions about Functional Tests and a link to the relevant section in the docs.
- Be more affirmative about the need for Java Test Case
=> Update contributing.md for Functional Tests

server/src/com/google/refine/Refine.java
Fixes #2640 
- Improved browser launch in Linux distribution
=> Improved browser launch in Linux distribution

main/src/com/google/refine/io/ProjectMetadataUtilities.java, main/tests/server/src/com/google/refine/io/ProjectMetadataUtilitiesTest.java
Fixes #4402 
- Modified the reader for loading project metadata to FileInputStream
- Set the charset to UTF-8 in the reader
=> (I#4402) update project metadata file reader

extensions/database/pom.xml, extensions/database/src/com/google/refine/extension/database/cmd/ConnectCommand.java, extensions/database/src/com/google/refine/extension/database/cmd/ExecuteQueryCommand.java, extensions/database/src/com/google/refine/extension/database/cmd/SavedConnectionCommand.java, extensions/database/src/com/google/refine/extension/database/cmd/TestConnectCommand.java, extensions/database/src/com/google/refine/extension/database/cmd/TestQueryCommand.java, extensions/database/tests/src/com/google/refine/extension/database/cmd/SavedConnectionCommandTest.java, extensions/gdata/pom.xml, main/src/com/google/refine/RefineServlet.java, main/src/com/google/refine/commands/project/ExportRowsCommand.java, main/tests/server/src/com/google/refine/RefineServletTests.java, main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java, pom.xml
Fixes #4339
- Upgrade database and gdata extensions dependency to httpclient5
=> (I#4339) Upgrade database and gdata extensions to httpclient5 

main/tests/cypress/cypress/integration/preferences/change_preference.spec.js, main/tests/cypress/cypress/integration/project_management/project_metadata.spec.js
- Updated tests for change preferences and project metadata in preparation for the jQuery migration.
=> Updated tests for jQuery migration

extensions/wikidata/module/scripts/schema-alignment.js
=> Fix serialization of item edits in Wikibase schema

extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java
Fixes #4818 
- Logging level switched from INFO to DEBUG
=> (I#4818) Fix for the Verbose log output when using a Wikibase without quality constraints extension

extensions/pc-axis/module/scripts/pc-axis-parser-ui.js, main/webapp/modules/core/externals/imgareaselect/jquery.imgareaselect.js, main/webapp/modules/core/externals/suggest/suggest-4_3a.js, main/webapp/modules/core/scripts/index/create-project-ui.js, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js, main/webapp/modules/core/scripts/index/import-project-ui.js, main/webapp/modules/core/scripts/index/lang-settings-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.js
- Fixed jQuery deprecations in imgareaselect and suggest external dependencies.
- Fixed more deprecations found from Cypress tests.
=> Fixed jQuery deprecations from Cypress tests and external dependencies

extensions/database/module/scripts/index/database-import-controller.js, extensions/database/module/scripts/index/database-source-ui.js, extensions/gdata/module/scripts/index/importing-controller.js, extensions/pc-axis/module/scripts/pc-axis-parser-ui.js, main/webapp/modules/core/scripts/index/default-importing-sources/sources.js, main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.js, main/webapp/modules/core/scripts/util/encoding.js
- Fixed jQuery deprecations in the UIs of the file parsers under create project through manual testing.
=> Fixed jQuery deprecations in the UIs of the file parsers under create project

extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js
- Fixed jQuery deprecations from manually testing manage wikibase account dialogs.
=> Fixed jQuery deprecations in manage Wikibase account dialogs

extensions/wikidata/module/scripts/bettersuggest.js, extensions/wikidata/module/scripts/dialogs/import-schema-dialog.js, extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js, extensions/wikidata/module/scripts/dialogs/statement-configuration-dialog.js, extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js, extensions/wikidata/module/scripts/previewrenderer.js, extensions/wikidata/module/scripts/schema-alignment.js, extensions/wikidata/module/scripts/wikibase-manager.js, main/webapp/modules/core/externals/suggest/suggest-4_3a.js, main/webapp/modules/core/scripts/project/process-panel.js, main/webapp/modules/core/scripts/reconciliation/recon-manager.js, main/webapp/modules/core/scripts/util/custom-suggest.js
-Fixed jQuery deprecations found through manual testing under the Wikidata menu  in: Edit Wikibase Schema, Import schema, Upload Edits to Wikibase, and Select Wikibase instance.
=> Fixed jQuery deprecations under the Wikidata menu

main/webapp/modules/core/externals/suggest/suggest-4_3a.js, main/webapp/modules/core/scripts/project/process-panel.js, main/webapp/modules/core/scripts/reconciliation/recon-dialog.js, main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js, main/webapp/modules/core/scripts/views/data-table/cell-ui.js, main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
- Fixed jQuery deprecations found through manual testing in the options under column -> reconcile.
=> Fixed jQuery deprecations found in column -> reconcile

extensions/database/src/com/google/refine/extension/database/mysql/MySQLDatabaseService.java, extensions/database/src/com/google/refine/extension/database/pgsql/PgSQLDatabaseService.java, extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseService.java
Fixes #4839 
- Use try-with-resources (where possible) and finally blocks (where not possible), in order to properly close the Statement and ResultSet Resources
=> (I#4839) Fix for the Unclosed Statement and ResultSet Resources

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js, main/webapp/modules/core/scripts/dialogs/common-transform-dialog.js, main/webapp/modules/core/scripts/dialogs/expression-column-dialog.js, main/webapp/modules/core/scripts/dialogs/extend-data-preview-dialog.js, main/webapp/modules/core/scripts/views/data-table/cell-ui.js, main/webapp/modules/core/scripts/views/data-table/data-table-view.js, main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
- Fixed jQuery deprecations under edit column, edit cell, transform, and edit all columns in preparation for the jQuery migration.
=> Fixed jQuery deprecations in edit column, edit cell, transform, and edit all columns

docs/docs/manual/grelfunctions.md, main/src/com/google/refine/expr/functions/strings/ReplaceEach.java, main/src/com/google/refine/grel/ControlFunctionRegistry.java, main/tests/server/src/com/google/refine/expr/functions/strings/ReplaceEachTest.java
Fixes #2606
- a new function `replaceEach` to address the concerns stated in the issue
- tests for this function
- update to the function registry
=> (I#2606) Add 2 new grel functions for replacing strings matching a search list

pom.xml
As discussed on mailing list:  https://groups.google.com/g/openrefine-dev/c/tmaH4dWMbLQ/m/mQh1UVM6BAAJ
=> Updates Jetty to avoid potential security risks

refine, refine.bat
Fixes #4889
-  Remove distclean option from scripts
=> #4889 Remove distclean option

extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js
Fixes #4931
- Added simple fix for Wikibase login buttons.
=> Added fix for Wikibase login buttons

.github/workflows/pull_request.yml
Fixes #4198
- Updated the GitHub PR workflow to ignore langs.
=> Updated GitHub PR workflow to ignore langs

docs/versioned_docs/version-3.5/manual/grelfunctions.md
This should make it easier for folks that might search our user docs for "transliteration" function.
Also quickly mention it's basic algorithmic processing.
- 
- 
-
=> add mention of "transliteration" in our fingerprint() function

extensions/wikidata/module/scripts/schema-alignment.js, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js
- Fixed jQuery deprecations in create project with multiple files found through manual testing.
=> Fixed jQuery deprecations in create project (multiple files)

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js
- Fixed deselect buttons and number of matched file names to display correctly in multiple file import screen.
=> Fixed deselect button and number of matched file names in multiple file import screen.

main/webapp/modules/core/scripts/index/open-project-ui.js
Partial fix for #4972
- Added checks for the project data and warnings to the console to skip any malformed projects so the UI will continue to work with valid projects.
=> Added checks for the project data and warnings to the console to skip any malformed projects

main/webapp/modules/core/scripts/facets/timerange-facet.js
- Fixed jQuery deprecations found through manual testing in timeline facet.
=> Fixed jQuery deprecations that show up when using timeline facet

.github/dependabot.yml, main/webapp/package-lock.json
- Updated dependabot to check dependencies in the main webapp.
=> Updated dependabot to check dependencies in the main webapp.

extensions/gdata/module/scripts/index/gdata-source-ui.js, extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js, extensions/wikidata/module/scripts/schema-alignment.js, main/webapp/modules/core/externals/suggest/suggest-4_3a.js, main/webapp/modules/core/scripts/facets/list-facet.js, main/webapp/modules/core/scripts/index/create-project-ui.js, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js, main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js, main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js, main/webapp/modules/core/scripts/util/filter-lists.js
- Fixed jQuery deprecations through some code inspection and manual testing.
=> Fixed jQuery deprecations 

extensions/sample/pom.xml
Fixes #5087
- Fixed sample extension pom by changing version from 3.6 to 3.7.
=> Fixed sample extension pom

extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java, extensions/wikidata/tests/src/org/openrefine/wikidata/editing/MediaFileUtilsTest.java
Fixes #4472 
- remove `ignorewarnings=0` from code
perhaps additional code is needed to handle upload errors?
MediaWiki upload API: https://www.mediawiki.org/wiki/API:Upload#Upload_warnings
=> remove ignorewarnings=0

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
Fixes #5138
- Added simple fix for cluster and edit dialog.
=> Added fix for UI regression in cluster and edit 

main/webapp/modules/core/MOD-INF/controller.js, main/webapp/modules/core/scripts/index.js, main/webapp/modules/core/scripts/preferences.js, main/webapp/modules/core/scripts/project.js, main/webapp/modules/core/scripts/util/csrf.js
- Cleaned up duplicate CSRF code.
=> Cleaned up duplicate CSRF code

main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
Fixes #5143
- Added the ability to submit the form data by pressing enter on the 'add column based on this column' dialog.
=> Added the ability to submit the form data by pressing enter on the 'add column based on this column' dialog

main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html, main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
- Added ability to confirm and close the dialog by pressing 'enter' in the 'add column by fetching URL' dialog.
=> Added ability to confirm and close by pressing 'enter' in the 'add column by fetching URL' dialog

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js, extensions/wikidata/module/scripts/warningsrenderer.js, extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java, extensions/wikidata/src/org/openrefine/wikidata/qa/QAWarning.java, extensions/wikidata/tests/src/org/openrefine/wikidata/commands/PreviewWikibaseSchemaCommandTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/QAWarningTest.java
Closes #5144
- fix frontend code for setup of the facet (not sure how the current bug made it through my testing…)
- fix facetability of Wikibase issues (not being preserved by merge, and absence of issues should not be facetable either)
=> Fix facetability of Wikibase issues

extensions/wikidata/src/org/openrefine/wikidata/updates/ItemEdit.java, extensions/wikidata/src/org/openrefine/wikidata/updates/LabeledStatementEntityEdit.java, extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java, extensions/wikidata/src/org/openrefine/wikidata/updates/StatementEdit.java, extensions/wikidata/tests/src/org/openrefine/wikidata/updates/ItemEditTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/updates/StatementEditTest.java
Closes #5162.
- fix editing of redirected Wikibase entities
=> Fix editing of redirected Wikibase items.

main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html, main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html
- Removed extra tr tags found from code inspection.
=> Removed extra <tr> tags

docs/docs/manual/grelfunctions.md, docs/versioned_docs/version-3.6/manual/grelfunctions.md
added parent jsoup function in docs ( /manual/grelfunctions#jsoup-xml-and-html-parsing )  #5176
=> added parent jsoup function in docs #5176

extensions/wikidata/module/scripts/schema-alignment.js, extensions/wikidata/module/scripts/wikibase-suggest.js
=> Clean up HTTP calls made when selecting a property in the Wikibase schema

extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
=> Removed debugger statement.

packaging/pom.xml
Closes #5160.
- adapt packaging process to fix file permissions
=> Fix file permissions in DMG

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/cluster-and-edit.spec.js, main/tests/cypress/cypress/integration/project/grid/column/facet/facets.spec.js
Fixes #3422
- Added Cypress tests from @fgiroud's PR (#3422).
=> Added cluster and edit UI tests.

extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java, extensions/wikidata/tests/src/org/openrefine/wikidata/updates/MediaInfoEditTest.java
Closes #5214.
@trnstlntk can you have a look if that solves the problem on your side? I did not try uploading your files because of the copyright issue you mentioned.
=> Fix skipping of fetching of existing state when uploading new files.

main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js, main/webapp/modules/core/scripts/dialogs/clustering-dialog.html, main/webapp/modules/core/scripts/dialogs/clustering-dialog.js, main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.html, main/webapp/modules/core/scripts/index/default-importing-sources/import-from-clipboard-form.html, main/webapp/modules/core/scripts/project/history-apply-dialog.html, main/webapp/modules/core/scripts/project/history-panel.html, main/webapp/modules/core/scripts/reconciliation/add-namespaced-service-dialog.html, main/webapp/modules/core/scripts/reconciliation/add-standard-service-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html
- Added and fixed labels for input fields and text areas.
- Exposed the distance function label that was hidden in the clustering dialog.
Clustering dialog after:
=> Added and fixed labels for input fields and text areas

extensions/database/module/scripts/index/database-import-form.html, extensions/gdata/module/scripts/index/import-from-gdata-form.html, extensions/wikidata/module/scripts/dialogs/save-new-template-dialog.html, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.html, main/webapp/modules/core/scripts/index/import-project-ui.html, main/webapp/modules/core/scripts/index/lang-settings-ui.html, main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.html, main/webapp/modules/core/scripts/views/data-table/copy-recon-across-columns-dialog.html, main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html
- Cleaned up and added labels to more inputs in various dialogs.
=> Accessibility labels cleanup II

extensions/wikidata/src/org/openrefine/wikidata/commands/PreviewWikibaseSchemaCommand.java, extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java, extensions/wikidata/src/org/openrefine/wikidata/qa/QAWarning.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/NewEntityScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/schema/strategies/QualifiersStatementMerger.java, extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java, extensions/wikidata/src/org/openrefine/wikidata/updates/StatementGroupEdit.java, extensions/wikidata/tests/src/org/openrefine/wikidata/commands/SaveWikibaseSchemaCommandTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/manifests/ManifestTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/SchemaPropertyExtractorTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/utils/EntityCacheStub.java
Mainly to remove noise in IDE problem windows.
=> drop unused imports from Wikibase extension

main/tests/cypress/cypress/integration/project/grid/all-column/view.spec.js, main/webapp/modules/core/langs/translation-en.json
Fixes #3415
- Added test for All column -> Show/Hide null values
-  Made wording of the menu option more consistent with the rest of the UI by changing it from 'Show/Hide 'null' values' to 'Show / Hide null values'.
=> Added a test for All column -> 'Show / Hide null values'

main/tests/cypress/cypress/integration/project/project-header/export_project.spec.js, main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.js, main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.js, main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.js, main/webapp/modules/core/scripts/project/exporters.js, main/webapp/modules/core/scripts/util/menu.js
- Fixed flaky export project Cypress tests.
- Prevented opening a new window on those exports.
=> Fixed flaky export project Cypress tests 

extensions/gdata/module/scripts/project/exporters.js
- Fixed console exceptions caused by calling onDone method that doesn't exist for some options under export.
=> Removed onDone calls for some exports that were causing exceptions in the console

main/tests/cypress/cypress/integration/project/grid/column/edit-cells/cluster-and-edit.spec.js, main/webapp/modules/core/scripts/dialogs/clustering-dialog.html
- Fixed flakiest Cypress test in cluster and edit:
=> Fixed flaky cluster and edit Cypress test

extensions/wikidata/module/langs/translation-en.json, extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js, extensions/wikidata/src/org/openrefine/wikidata/commands/PreviewWikibaseSchemaCommand.java, extensions/wikidata/src/org/openrefine/wikidata/functions/WikibaseIssuesFunction.java, extensions/wikidata/src/org/openrefine/wikidata/qa/EditInspector.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EditScrutinizer.java, extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/NewEntityScrutinizer.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/EditInspectorTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/NewEntityScrutinizerTest.java, extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/ScrutinizerTest.java
Closes #5037. Closes #5298.
This also introduces a sample expensive check, which verifies that files to be uploaded have a valid path.
=> Introduce expensive Wikibase QA checks

extensions/wikidata/module/scripts/schema-alignment.js, main/webapp/modules/core/scripts/project.js
Fixes #5333
- Made it so the Wikibase schema panel gets resized when the window gets resized, which fixes the scrollbar problem.
=> Made it so the Wikibase schema panel gets resized when the window gets resized

docs/docs/manual/grelfunctions.md, docs/versioned_docs/version-3.4/manual/grelfunctions.md, docs/versioned_docs/version-3.5/manual/grelfunctions.md, docs/versioned_docs/version-3.6/manual/grelfunctions.md
Fixes #5371
Fixes all instances of the GREL partition  documentation
=> Fix GREL partition documentation

docs/docs/technical-reference/build-test-run.md, docs/versioned_docs/version-3.5/technical-reference/build-test-run.md, docs/versioned_docs/version-3.6/technical-reference/build-test-run.md
Fixes #4873
- added note to build docs about nvm to manage Node/npm on Windows more easily.
=> mention nvm to manage Node/npm versions on Windows

docs/docs/manual/running.md, docs/versioned_docs/version-3.5/manual/running.md, docs/versioned_docs/version-3.6/manual/running.md
Fixes #3877
-  Fixed the version of `ui.browsing.pageSize` to display correctly for the relevant documentation.
=> Fixed the documentation to display the correct version of ui.browsing.pageSize

docs/docs/manual/grelfunctions.md, docs/versioned_docs/version-3.6/manual/grelfunctions.md
This might help a bit for issues such as https://groups.google.com/g/openrefine/c/tsA0FYnOLv4/m/CyUxSzzkAAAJ
=> Add See Also tips for find() match()

extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizer.java, extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizerTest.java
=> Fix Wikibase QA check to allow for valid URLs as file path for mediainfo entities

main/tests/cypress/cypress/integration/project/grid/viewpanel-header/rows_records.spec.js
- Fixed the flaky test 'ensures rows and records are different for 3-level json file' in rows_records.spec.js introduced/highlighted by #5428.
=> Rows and records flaky test fix

main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
Fixes #5497
- Removes the race condition in the date test 
- adds tests for actual date value instead of just type.
=> Fix race. Improve tests. Fixes #5497

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html, main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Also align naming to be consistent.
Fixes #5523
- Clear selected type when "Reconcile against any type" is selected
- Align naming to be consistent
=> Clear selected type when "No Type" is selected. Fixes #5523

main/webapp/modules/core/scripts/index/default-importing-sources/import-from-web-form.html
...and formatting, check the first commit(4f77169b392bd0e0e692e9e407b1eb4acfaf5c86) for the relevant diff.
=> Fix form input missing type

extensions/gdata/module/styles/importing-controller.css, extensions/wikibase/module/styles/schema-alignment.css, main/webapp/modules/core/styles/common.css, main/webapp/modules/core/styles/dialogs/clustering-dialog.css, main/webapp/modules/core/styles/index.css, main/webapp/modules/core/styles/index/create-project-ui.css, main/webapp/modules/core/styles/index/default-importing-file-selection-panel.css, main/webapp/modules/core/styles/index/default-importing-parsing-panel.css, main/webapp/modules/core/styles/index/open-project-ui.css, main/webapp/modules/core/styles/jquery-ui-overrides.css, main/webapp/modules/core/styles/project.css, main/webapp/modules/core/styles/project/facets.css, main/webapp/modules/core/styles/project/sidebar.css, main/webapp/modules/core/styles/reconciliation/recon-dialog.css, main/webapp/modules/core/styles/util/dialog.css, main/webapp/modules/core/styles/util/menu.css, main/webapp/modules/core/styles/widgets/slider-widget.css
=> adopt CSS variables for primary background and text

pom.xml
This lets us use SVG images in the application. It's a feature I seem to have added to Butterfly quite some time ago but did not make it to OpenRefine yet. 
Useful for #3017.
=> Update butterfly to 1.2.4

main/webapp/modules/core/scripts/views/data-table/menu-facets.js
Fixes #557
- internationalize word facet
- 
-
=> Use internationalized word separator. Fixes #557.

main/webapp/modules/core/scripts/facets/list-facet.js, pom.xml
=> change email to url for dfhuynh

README.md, main/webapp/modules/core/scripts/facets/list-facet.js, pom.xml
=> change David Huynh's link to his GitHub profile

refine, refine.bat
Partially fixes #5484
- Updated `mvn_prepare` in the refine script so it doesn't do automatic download, still need to update documentation
- Updated refine.bat with a similar change.
=> Updated Maven in refine script

main/tests/cypress/build-test-matrix.js
Fixes #5654
- Updated build test matrix to use GitHub environment files.
=> Updated build test matrix to use GitHub environment files

main/src/com/google/refine/expr/functions/strings/ReplaceEach.java, main/tests/server/src/com/google/refine/expr/functions/strings/ReplaceEachTest.java
Fixes #5463 
- Fix a bug of object array convertion
- Adjust error message
=> Fix a bug of object array convertion and adjust error message

.github/workflows/pull_request.yml, main/tests/cypress/build-test-matrix.js
Fixes #5654
- Fixes regression introduced by PR #5660 that makes it so the CI doesn't run the ui-tests.
@wetneb , I should have kept the previous PR as a draft. I thought it had passed, but hadn't doublechecked that all the jobs had run. And then it was merged before I could take a look.  I had to tweak the output of the build-test-matrix.js script to work with `$GITHUB_OUTPUT`.
=> Fixed regression that prevents UI tests from running in CI

refine.bat
Fixes #5622
User can specify refine options in refine.ini, or custom.ini if specified with `/c custom.ini`.  Command line options like `/m 5600m` take precedence over the INI file, so even if REFINE_MEMORY is defined in the INI file, you can override it on the command-line.
Tested folowing (and more):
```
refine.bat
refine.bat /?
refine.bat /h
refine.bat run
refine.bat test
refine.bat clean
refine.bat build
refine.bat /c my.ini
refine.bat /c my.ini run
refine.bat /c missing.ini
refine.bat /m 8192m
refine.bat /c my.ini /m 8192m
refine.bat /m 8192m /c my.ini
refine.bat /c missing.ini /m 8192m
refine.bat /p 3344 /i 127.0.0.2 /m 8192m /debug /jmx
refine.bat /c my.ini /p 3344 /i 127.0.0.2 /m 8192m /debug /jmx
```
=> Added fix for command line options in refine.bat

refine
Fixes #5698
- refine script
- 
-
=> update refine script to fail on mvn compile failure

main/src/com/google/refine/LookupCacheManager.java, main/tests/server/src/com/google/refine/expr/functions/CrossTests.java
Fixes #5531
- made the cross function return an empty array if there is no matching rows
=> Updated cross function

main/webapp/modules/core/styles/index/create-project-ui.css
=> Fix style of project creation progress bar.

main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Fixes #4722 
- gives preference to user if they want to automatch candidates with high confidence or not, keeping it true by default .
=> gives preference to user if they want to automatch or not

main/webapp/modules/core/scripts/index/create-project-ui.js, main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.js, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.html, main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js, main/webapp/modules/core/styles/index/default-importing-file-selection-panel.css, main/webapp/modules/core/styles/index/default-importing-parsing-panel.css
Continuing down the path, #5682, #5598.
=> move create project panels ui resize logic from js to css

main/webapp/modules/core/scripts/index/open-project-ui.js, main/webapp/modules/core/styles/index/open-project-ui.css
More of the same, #5682, #5598, #5751.
=> move open project panel's ui resize logic from js to css

main/webapp/modules/core/MOD-INF/controller.js
Removed references to pure.css in controller.js that were causing errors since the file was removed by #5771.
=> Removed references to pure.css in controller.js.

main/tests/cypress/cypress/support/openrefine_api.js
=> Optimize project deletion after Cypress tests

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml, main/tests/cypress/build-test-matrix.js, refine
Fixes #5808
- Updated the names of the CI e2e tests.
- Updated the refine script.
=> Updated the names of the CI tests and updated refine

main/src/com/google/refine/exporters/sql/SqlCreateBuilder.java, main/src/com/google/refine/exporters/sql/SqlInsertBuilder.java, main/tests/server/src/com/google/refine/exporters/sql/SqlExporterTests.java
Fixes https://github.com/OpenRefine/OpenRefine/issues/5388
Added function to wrap a string with double quotes
Added said function in SQLExporter and SQLInsertBuilder
Updated test cases due to which there were ci failures.
=> issue-5388-fix-case-in-sql-column-names-and-ci-failures

main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/project.js, main/webapp/modules/core/styles/project/sidebar.css
side effect: simplified CSS styles
=> make the show/hide left panel button keyboard accessible

main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
- remove the hard coded cluster choice limit to user configurable value
=> Remove hardcoded cluster choice limit

main/webapp/modules/core/styles/common.css
Most notable change in practice is within the open project table.
=> do not remove element outlines set by the browser

main/webapp/modules/core/scripts/views/data-table/column-header.html, main/webapp/modules/core/scripts/views/data-table/data-table-view.js, main/webapp/modules/core/styles/views/data-table-view.css
tab to select, enter to open. Could be improved by adding proper labels.
=> make the column header buttons selectable/openable by keyboard

main/webapp/modules/core/scripts/index.js, main/webapp/modules/core/styles/index.css
It's now possible to tab through the main action area menu.
=> make action area tabs selectable by keyboard

.github/workflows/pull_request.yml, .github/workflows/snapshot_release.yml
This reverts commit bfa8c9af756c5efe570b653067811eadd57bd12d.
Fixes #5013 
- Reenable Coveralls plugin
Seems to work now, so let's see how reliable it is.
=> Reenable Coveralls plugin. Fixes #5013

main/webapp/modules/core/scripts/util/menu.js
Far from full featured but still a major improvement.
=> Make the menu system navigable by keyboard

main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
For #5908
- Added resizing to Best candidate type and name match reconcile facets.
=> Added resizing to other reconcile facets.

pom.xml
=> Exclude generated Java files from coverage statistics

main/webapp/modules/core/scripts/util/url.js
https://en.wikipedia.org/wiki/Geo_URI_scheme
=> render geo: URIs as links in cells

refine.bat
- Made it so refine.bat only shows memory when running OR.
=> Made refine.bat only show memory on run

main/webapp/modules/core/about.js, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/dialogs/clustering-dialog.html, main/webapp/modules/core/scripts/dialogs/clustering-dialog.js, main/webapp/modules/core/styles/dialogs/clustering-dialog.css
Fixes #241
- Implemented auto cluster checkbox for the cluster dialog.
- Added cluster button to the cluster dialog.
After:
Changes to add in a separate PR:
- Add a preference to uncheck auto cluster by default.
=> Added auto cluster checkbox to cluster dialog

main/src/com/google/refine/ProjectMetadata.java, main/tests/server/src/com/google/refine/commands/project/SetProjectMetadataCommandTests.java, pom.xml
Fixes #5772 
- edit setAnyField() method in ProjectMetadata class
- add case to edit customMetadata field
- parse given String to JSON and JSON to HashMap
=> fix custom metadata edit action

.gitignore
=> Add internal Yarn files to .gitignore

main/src/com/google/refine/model/Row.java, main/src/com/google/refine/model/changes/MassRowChange.java, main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java, main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js, main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html
No issue. Ignore the reference in the branch name.
- Performance enhancement to SplitMultiValuedCell which hoists expensive operations out of inner loop
- Add a few explanatory comments about split processing
- Fix a typo & misspelling in variable name
- Add a ToDo
=> Performance enhancement and small cleanups related to SplitMultiValuedCell

main/tests/cypress/cypress/e2e/project/grid/column/reconcile/add_entity_identifiers.cy.js, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
Fixes #5998
- Add quotes (") around column name in title.
- Focus on text input when dialog opens.
- Change "Submit Query" to "OK."
After:
=> Issue 5998 entity identifiers dialog improvements

extensions/database/module/langs/translation-fa.json
No issue. Hotfix for Weblate translation file syntax problem.
=> Remove trailing comma

main/webapp/modules/core/scripts/facets/list-facet.js
Fixes #6071
- Missing space added
=> Add missing space in facet sorting

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js
I found the source of flakiness in the facet tests.  The problem is that every time a facet is added or updated, its HTML gets re-rendered. For some reason a 100ms timer event is setup to delay adding the click handlers for the edit/include/exclude links.  
This is causing problems with the Cypress tests.  I noticed on my fast main computer that the facet tests were failing all the time, and now I'm seeing the some of the tests fail on the CI builds.
The fix is to wait 100ms with `cy.wait(100)` after a facet is added/updated to make sure the click handlers have been added.
When I have time, I'll look at the facet code to to see why did it need to have that timer in the first place to delay setting up the click handlers.  I don't see why we can't add them immediately so the Cypress problem …
=> Fix flaky Cypress tests in facets.cy.js

extensions/gdata/pom.xml, main/webapp/WEB-INF/jetty-web.xml, main/webapp/WEB-INF/web.xml, pom.xml, server/src/com/google/refine/Refine.java, server/src/com/google/util/threads/ThreadPoolExecutorAdapter.java
Fixes #6075 
- Update to Jetty 10
- Adjust config provide gzip support
- Adapt to the updated Scanner API
=> Update to Jetty 10

main/tests/server/src/com/google/refine/importers/RdfTripleImporterTests.java, pom.xml
These tests could probably be improved / generalized, but this gets them passing again.
Fixes #5969
=> Fix RDF tests for Jena 4.9.0 reordering

main/webapp/modules/core/scripts/index/open-project-ui.js
=> Bug: Ensure the "Create project" screen is the default one on startup

main/webapp/modules/core/scripts/util/dialog.js
- Fixed jQuery deprecation in dialog.js.
=> Fixed JQuery deprecation in dialog.js

extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
Fixes #6174
- Initialize Python interpreter when first needed, rather than unconditionally at startup.
=> Defer initialization of Jython interpeter from startup. Fixes #6174

main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
Fixes [6179](https://github.com/OpenRefine/OpenRefine/issues/6179)
As mentioned in the Issue, the ordering is not guaranteed in hashmap, so I sort the choices inside the test so that the order remains constant.
=> Fix flaky tests

main/src/com/google/refine/ProjectManager.java, main/src/com/google/refine/commands/project/DeleteProjectCommand.java, main/src/com/google/refine/commands/project/RenameProjectCommand.java, main/src/com/google/refine/commands/project/SetProjectMetadataCommand.java, main/src/com/google/refine/commands/project/SetProjectTagsCommand.java, main/src/com/google/refine/commands/workspace/GetAllProjectTagsCommand.java, main/src/com/google/refine/io/FileProjectManager.java, main/tests/server/src/com/google/refine/ProjectManagerTests.java, main/tests/server/src/com/google/refine/commands/CommandTestBase.java, main/tests/server/src/com/google/refine/commands/project/RenameProjectCommandTests.java, main/tests/server/src/com/google/refine/commands/project/SetProjectMetadataCommandTests.java, main/tests/server/src/com/google/refine/commands/project/SetProjectTagsCommandTests.java, main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
Fixes #3479 
- refactor & DRY up tag management code
- add some tests for project related commands
- add tests for tag commands
=> Fix DeleteProject NPE during e2e tests. Fixes #3479.

main/webapp/modules/core/scripts/index/open-project-ui.js, main/webapp/modules/core/scripts/util/i18n.js, main/webapp/modules/core/styles/index/open-project-ui.css
Fixes #6172. Built on #6169.
- format dates according the the language the user set in
OpenRefine preferences with browser language as fallback
- right justify numbers in Row Count column
- consolidate CSS for project name
- fix pre-existing CSS off-by-one errors
- fix unrelated typo with user metadata
=> Localize date on Open Project page. Fixes #6172

main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js, main/webapp/modules/core/styles/views/data-table-view.css
Fixes #6110
- Now the cells with errors can be matched manually with "Search For Match" button
=> Adds the Search for match option

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js, main/tests/cypress/cypress/e2e/project_management/project_metadata.cy.js
Also mark flaky test
Fixes #6259
=> Qualify selectors with metadata dialog ID. Fixes #6259

extensions/wikibase/module/scripts/preview-renderer.js, server/src/com/google/refine/Refine.java
Fixes #6304
In this pull request, I have fixed the bug in which the referenceContainer was not unfolding on clicking of the triangle icon.
PFA Evidence.
https://github.com/OpenRefine/OpenRefine/assets/37299522/841f28db-7f15-4ea2-b07e-5d390574def2
=> Issue 6304 unfolding triangle bug

packaging/pom.xml
See https://github.com/OpenRefine/OpenRefine/issues/6349#issuecomment-1935052242
=> Bump notarization timeout from 10m to 15m

main/tests/cypress/cypress/e2e/project/grid/all-column/edit-columns.cy.js, main/tests/cypress/cypress/e2e/project/grid/all-column/view.cy.js, main/tests/cypress/cypress/e2e/project/grid/column/sort.cy.js, main/tests/cypress/cypress/e2e/project/grid/column/transpose/cell_accross_columns.cy.js, main/tests/cypress/cypress/e2e/project/grid/misc/proper-display.cy.js, main/tests/cypress/cypress/e2e/project/grid/row/edit_cells.cy.js, main/tests/cypress/cypress/e2e/project/grid/viewpanel-header/sort.cy.js, main/tests/cypress/cypress/support/commands.js, main/webapp/modules/core/scripts/views/data-table/cell-ui.js, main/webapp/modules/core/styles/views/data-table-view.css
This change makes it possible to edit cells solely by keyboard.
TODOs
=> Keyboard cell editing

main/src/com/google/refine/commands/HttpHeadersSupport.java, main/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperation.java
Fixes #6334
- Add support for Accept-Language, Accept-Charset, Accept-Encoding and If-Modified-Since.
- Also switch to using constants instead of free form strings.
=> Add more HTTP headers. Fixes #6334

server/src/com/google/util/logging/IndentingLayout.java
Fixes #6059 
- Adds support for logging Throwable if it's present in the event
- Modernize & streamline time handling and formatting
It's not entirely clear to me why this fixes the missing stack traces. Perhaps this class wasn't being used before and a change to the logging configuration caused it to start being used again? In any case, adding support for logging a Throwable fixes things. 
Although my commit message says that OpenRefine doesn't use the indenting functionality (using "> " in the log message), Butterfly does use it higher logging levels, so I guess it's worth retaining.
There are no tests, but I manually confirmed that when used with the test cases #6058 and #3638, it restores the console log stack traces. Now we just have to go …
=> Add stack trace support and modernize. Fixes #6059

extensions/database/tests/conf/test-pgsql.sql
=> Remove unneccessary "USE" statement in psql test fixture

main/src/com/google/refine/model/Cell.java, main/src/com/google/refine/model/Recon.java, main/src/com/google/refine/model/ReconCandidate.java, main/tests/server/src/com/google/refine/model/CellTests.java, main/tests/server/src/com/google/refine/model/ReconCandidateTests.java, main/tests/server/src/com/google/refine/model/ReconTests.java
To ease testing and debugging.
Follow-up to #6383.
=> Add equals(), hashCode() and toString() for Cell and subcomponents

main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Follow-up to #6360.
Fixes recent failing builds on the master branch.
=> Fix unmocked HTTP call in tests

main/webapp/modules/core/scripts/project/history-panel.html
Fixes #6432
- Fix inconsistent Extract/Apply button location by making it stick to the top right
=> Fix inconsistent Extract/Apply button location

extensions/wikibase/module/scripts/dialogs/wikibase-dialog.html, main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.html, main/webapp/modules/core/scripts/dialogs/common-transform-dialog.html, main/webapp/modules/core/scripts/dialogs/expression-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-column-by-reconciliation.html, main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/cell-editor.html, main/webapp/modules/core/scripts/views/data-table/cell-recon-search-for-match.html, main/webapp/modules/core/scripts/views/data-table/column-join.html, main/webapp/modules/core/scripts/views/data-table/copy-recon-across-columns-dialog.html, main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html, main/webapp/modules/core/scripts/views/data-table/rename-column.html, main/webapp/modules/core/scripts/views/data-table/replace-dialog.html, main/webapp/modules/core/scripts/views/data-table/sorting-criterion-dialog.html, main/webapp/modules/core/scripts/views/data-table/split-column-dialog.html, main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html, main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html, main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html, main/webapp/modules/core/scripts/views/data-table/warn-of-pending-sort.html, main/webapp/modules/core/styles/common.css, main/webapp/modules/core/styles/reconciliation/recon-dialog.css
Fixes [#6353](https://github.com/OpenRefine/OpenRefine/issues/6353)
- Implemented Windows ordering buttons ("OK" / "Cancel")
- Marked the OK button  as "primary" 
Here's how it looks like :
=> Issue 6353 implement Windows ordering buttons ("OK" / "Cancel")

main/src/com/google/refine/model/Recon.java, main/tests/server/src/com/google/refine/model/ReconTests.java
=> Fix recon deserialization error for matched cells

main/src/com/google/refine/expr/util/CalendarParser.java, main/tests/server/src/com/google/refine/expr/util/CalenderParserTest.java
Fixes #6469 
Improved test coverage of CalendarParser.java class
=> Issue 6469 improve test coverage

main/src/com/google/refine/exporters/ExporterRegistry.java, main/webapp/modules/core/MOD-INF/controller.js
As a preparation for more Maven modularization.
=> Move exporter registration to controller.js

.github/workflows/pull_request_e2e.yml, .github/workflows/snapshot_release.yml, main/tests/cypress/package.json
Fixes #6525
- Update to latest LTS Node 20
- 
-
=> Update to Node 20. Fixes #6525

main/src/com/google/refine/importers/tree/XmlImportUtilities.java, main/webapp/modules/core/externals/suggest/suggest-4_3a.js, packaging/desktop/openrefine.metainfo.xml
remove repetitive words
- 
- 
-
=> chore: remove repetitive words

refine
=> refine script: Abort build early if NPM is missing

server/src/com/google/refine/Refine.java
=> chore: Fix logging messages placeholder counts

main/src/com/google/refine/expr/functions/arrays/Join.java, main/tests/server/src/com/google/refine/expr/functions/arrays/JoinTests.java
Fixes #6683
- Fix join() of arrays containing nulls
=> Fix join() of arrays containing nulls. Fixes #6683

.github/dependabot.yml
Since it requires higher Java versions.
=> Ignore updates to impsort-maven-plugin

extensions/wikibase/tests/src/org/openrefine/wikibase/editing/NewEntityLibraryTest.java, main/pom.xml, main/src/com/google/refine/importers/WikitextImporter.java, main/src/com/google/refine/model/recon/DataExtensionReconConfig.java, main/src/com/google/refine/model/recon/ReconConfig.java, main/src/com/google/refine/model/recon/StandardReconConfig.java, main/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperation.java, main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java, main/src/com/google/refine/util/ParsingUtilities.java, main/tests/server/src/com/google/refine/commands/recon/ReconJudgeOneCellCommandTest.java, main/tests/server/src/com/google/refine/model/ColumnTests.java, main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java, main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java, main/tests/server/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperationTests.java, main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
Draft while I figure out the intricacies of Jackson annotations...
Fixes #6652
- Restore deleted public constructors & getters
=> Restore public API. Fixes #6652

main/tests/cypress/cypress/e2e/language/change_language.cy.js, main/tests/cypress/cypress/e2e/project/undo_redo/undo_redo.cy.js, main/tests/cypress/cypress/support/commands.js
=> chore: fix some comments

extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
@wetneb do you think I worded the parameter description well enough?
=> add missing parameter for JavaDocs in MediaInfoEdit

README.md
- The README file states that it requires NPM 16 or newer, but npm is currently at version 10.8. It is however distributed as part of node.js which itself is at version 22.6.
=> The README states a future NPM version, so this must be about node.js

main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
Another followup to #6825 
- minimal change to (hopefully) unbreak the snapshot build
I'll follow up with a separate PR that can be properly reviewed to DRY up this code.
=> HOTFIX - increase Clojure initialization timeout to unbreak snapshot build

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/add_columns_based_on_this_column.cy.js, main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
Another followup to #6825 . Attempt to unbreak snapshot build one last time. If this doesn't work, we'll just revert the whole mess and let someone else try to figure it out.
=> Increase Clojure timeout back to original 10sec.

main/tests/cypress/cypress/e2e/project/grid/column/edit-column/add_columns_based_on_this_column.cy.js, main/tests/cypress/cypress/e2e/project/grid/misc/expressions.cy.js
Fixes #6824. Patches #6825 
Also revert all previous timeout increases:
- This reverts commit 40dcffb323219c50a2a40c0ce8017e3ba676c843. 
- This reverts commit a6093bc876530c9f4a10399f2496359f4eb5c889.
- This reverts commit b38b1b679f3b0eca13f61566a5cd14acc9bbc87f.
=> Check for less specific error from Clojure

main/src/com/google/refine/clustering/binning/KeyerFactory.java, main/src/com/google/refine/clustering/knn/DistanceFactory.java, main/src/com/google/refine/commands/browsing/ComputeClustersCommand.java, main/tests/cypress/cypress/e2e/project/grid/column/edit-cells/cluster-and-edit.cy.js, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/dialogs/clustering-dialog.js, main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.html, main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.js, main/webapp/modules/core/styles/dialogs/clustering-functions-dialog.css
This is the fifth PR in the GSoC project. 
- Add custom functions from clustering functions dialog to dropdown menu
- Enable clustering based on custom functions selected from the dropdown
https://github.com/user-attachments/assets/370a5835-bf20-4406-979c-bb86a7051c75
=> Enable clustering using custom functions from dropdown menu

extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java, extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
Closes #4273.
- select a better error message than "The save has failed" when the edit is refused because of some spam filter
- also return an error message if a network error happened, which we only reported in the logs before
=> wikibase: More precise editing error messages

.github/workflows/snapshot_release.yml
Fixes #6905
- Update to macos-13
=> Update to macos-13. Fixes #6905

main/src/com/google/refine/importers/JsonImporter.java, main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
Fixes #6454
- Add error reporting to JSON preview parse.
=> Add error reporting to JSON preview parse. Fixes #6454

extensions/wikibase/tests/src/org/openrefine/wikibase/commands/PreviewWikibaseSchemaCommandTest.java
Fixes #6911 
- Set language before test as the test validates label which is language specific
- 
-
=> wikibase: Test failure when run on non-English locales

extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseService.java
Fixes #6922
- Closes SQLite connections remaining open (and db file in use)
=> Fix database import SQLite not closing connections

modules/grel/src/main/java/com/google/refine/expr/functions/ToString.java, modules/grel/src/test/java/com/google/refine/expr/functions/ToStringTests.java
Fixes #6943
- Broaden illegal format exception caught.
=> Broaden illegal format exception caught. Fixes #6943

main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js
Fixes #6940
- increase waits to 150% of client timeout to give some headroom
- simplify facet selection logic
- fix & enable facet collapse test
- delete dead code
=> Attempt to fix flaky facet include/exclude test

README.md
- The README isn't clear enough on the exact location of the `licenses` folder(s).
=> Update license folder locations in README

refine.ini
Update the refine.ini file to use the REFINE_INTERFACE and REFINE_HOST variables.
=> Update refine.ini for REFINE_INTERFACE

.github/workflows/pull_request_e2e.yml, .github/workflows/pull_request_server.yml
We have 2 Actions named the same thing: "CI"
Let's make it easier to distinguish between them.
=> Update CI action names

extensions/wikibase/module/scripts/schema-alignment.js, main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
=> fix: Remove spurious recon logo warnings

main/src/com/google/refine/importers/SeparatorBasedImporter.java
=> fix: issue #7038

extensions/wikibase/module/langs/translation-en.json
=> wikibase: Fix invalid markup in message

main/tests/server/src/com/google/refine/commands/column/RenameColumnCommandTests.java
This just adds a test, as a preparation for further changes to this command (to solve #133).
=> test: Happy path for RenameColumnCommand

main/pom.xml, pom.xml
=> Fix test-jar still being generated if -DskipTests is added

main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java, main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
=> fix: Deserialization of old cell splitting operation

GOVERNANCE.md
See https://forum.openrefine.org/t/openrefine-3-9-release-schedule-contents/1796.
Given that I am in the process of leaving the project, I would like to pass on this role to someone else. If anyone is interested in taking up this role, I am available to help them get up to speed on the process.
=> Change release manager to Antonin

main/webapp/modules/core/scripts/index.js
=> fix: Correct home page behaviour when there are no events to advertise

modules/grel/src/main/resources/com/google/refine/grel/FunctionDescription.properties
=> fix typos for chomp English translation

CODE_OF_CONDUCT.md
Update CODE_OF_CONDUCT.md to remove members that left in the past year.
- Remove Jessica from CS&S
- Remove Juliane
=> Update CODE_OF_CONDUCT.md removing members

main/src/com/google/refine/commands/history/ApplyOperationsCommand.java, main/tests/cypress/cypress/e2e/project/undo_redo/apply.cy.js, main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java, main/webapp/modules/core/langs/translation-en.json, main/webapp/modules/core/scripts/project.js, main/webapp/modules/core/scripts/project/process-panel.js
=> Show Undo notification when applying recipes

main/src/com/google/refine/commands/row/GetRowsCommand.java, main/tests/cypress/cypress/e2e/project/grid/viewpanel-header/pagination.cy.js, main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java, main/webapp/modules/core/scripts/views/data-table/data-table-view.js
With more precise Cypress assertions to catch such problems in the future.
Fixes #7188.
=> Fix pagination controls and row range

main/webapp/modules/core/scripts/util/menu.js, main/webapp/modules/core/styles/util/menu.css
=> Fix layout of menu icons for long descriptions

extensions/wikibase/src/org/openrefine/wikibase/schema/strategies/QualifiersStatementMerger.java
Copied the function body from `org.openrefine.wikibase.schema.strategies.SnakOnlyStatementMerger.match(Snak,Snak)` because it does the same thing without the erroneous casting.
Fixes #7287
Copying the code is not the best solution but it fixes the bug. Ideally, this code should be refactored somewhere else so it can be reused in both classes. However I think that would be a rather larger change and I do not feel comfortable enough in Java to make that change.
=> wikibase: fix NoValueSnak being incorrectly cast

.well-known/funding-manifest-urls, README.md, funding.yml
Needs to be merged after https://github.com/OpenRefine/openrefine.org/pull/466
This PR enhances funding visibility by 
* updating the README with donation badges 
*  adding a `.github/FUNDING.yml` to configure [GitHub’s Sponsor dropdown.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)
=> update funding reference

pom.xml
Attempt to repair CI snapshot build. Follow up fix for #7390
=> Revert snapshot repo ID change. Fixes #7390

extensions/wikibase/pom.xml, extensions/wikibase/src/org/openrefine/wikibase/commands/ConnectionManager.java, extensions/wikibase/src/org/openrefine/wikibase/commands/FetchManifestCommand.java, extensions/wikibase/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperation.java, extensions/wikibase/src/org/openrefine/wikibase/utils/HttpClient.java, extensions/wikibase/src/org/openrefine/wikibase/utils/LanguageCodeStore.java, extensions/wikibase/tests/src/org/openrefine/wikibase/commands/LoginCommandTest.java, pom.xml
Fixes #7383
- Set custom user agent on Wikidata Toolkit calls
- Set custom user agent on raw okhttp calls
=> Set custom user agent for Wikidata calls. Fixes #7383
